ci_ranking.Rmd:
  path: dev/ci_ranking.Rmd
  state: active
  R: R/rank_wt.R
  tests: tests/testthat/test-rank_wt.R
  vignettes: vignettes/ci-ranking-helpers.Rmd
  inflate:
    flat_file: dev/ci_ranking.Rmd
    vignette_name: CI ranking helpers
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
ci_split_search.Rmd:
  path: dev/ci_split_search.Rmd
  state: active
  R: R/best_numeric_split.R
  tests: tests/testthat/test-best_numeric_split.R
  vignettes: vignettes/ci-split-search.Rmd
  inflate:
    flat_file: dev/ci_split_search.Rmd
    vignette_name: CI split search
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
ci_tree_builder.Rmd:
  path: dev/ci_tree_builder.Rmd
  state: active
  R: R/ci_tree_control.R
  tests: tests/testthat/test-ci_tree_control.R
  vignettes: vignettes/ci-tree-builder.Rmd
  inflate:
    flat_file: dev/ci_tree_builder.Rmd
    vignette_name: CI tree builder
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
ci_tree_models.Rmd:
  path: dev/ci_tree_models.Rmd
  state: active
  R: R/ci_splitfun.R
  tests: tests/testthat/test-ci_splitfun.R
  vignettes: vignettes/ci-tree-models.Rmd
  inflate:
    flat_file: dev/ci_tree_models.Rmd
    vignette_name: CI tree models
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
keep:
  path: keep
  state: active
  R:
  - R/doc_kenya.R
  - R/utils-pipe.R
  tests: []
  vignettes: vignettes/inequality-aware-party-trees.Rmd
model_selection.Rmd:
  path: dev/model_selection.Rmd
  state: active
  R: R/ci_tree_control_grid.R
  tests: tests/testthat/test-ci_tree_control_grid.R
  vignettes: vignettes/model-selection.Rmd
  inflate:
    flat_file: dev/model_selection.Rmd
    vignette_name: Model selection
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
plot_tree_helpers.Rmd:
  path: dev/plot_tree_helpers.Rmd
  state: active
  R: R/tree_default_name.R
  tests: tests/testthat/test-tree_default_name.R
  vignettes: vignettes/plots-for-party-trees.Rmd
  inflate:
    flat_file: dev/plot_tree_helpers.Rmd
    vignette_name: Plots for party trees
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
shap_decomposition.Rmd:
  path: dev/shap_decomposition.Rmd
  state: active
  R:
  - R/assert_data_table_available.R
  - R/fractional_rank.R
  - R/shap_conc_decomp.R
  tests: tests/testthat/test-fractional_rank.R
  vignettes: vignettes/shap_decomposition.Rmd
  inflate:
    flat_file: dev/shap_decomposition.Rmd
    vignette_name: shap_decomposition
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
