flat_partytrees.Rmd:
  path: dev/flat_partytrees.Rmd
  state: active
  R: R/rank_wt.R
  tests: tests/testthat/test-rank_wt.R
  vignettes: vignettes/inequality-aware-party-trees.Rmd
  inflate:
    flat_file: dev/flat_partytrees.Rmd
    vignette_name: Inequality-aware party trees
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
plot_tree_helpers.Rmd:
  path: dev/plot_tree_helpers.Rmd
  state: active
  R: R/tree_default_name.R
  tests: tests/testthat/test-tree_default_name.R
  vignettes: vignettes/plots-for-party-trees.Rmd
  inflate:
    flat_file: dev/plot_tree_helpers.Rmd
    vignette_name: Plots for party trees
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
