# WARNING - Generated by {fusen} from dev/flat_partytrees.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("rank_wt computes weighted midpoint ranks", {
  expect_equal(
    rank_wt(c(10, 20, 30), c(1, 1, 2)),
    c(0.125, 0.375, 0.75)
  )
})

test_that("rank_wt returns ranks in the order of retained inputs", {
  expect_equal(
    rank_wt(c(20, 10, 30), c(1, 1, 2)),
    c(0.375, 0.125, 0.75)
  )
})

test_that("rank_wt drops missing and non-positive weights before ranking", {
  expect_equal(
    rank_wt(c(2, NA, 1, 3), c(1, 1, 0, 2)),
    c(1 / 6, 2 / 3)
  )
})

test_that("rank_wt handles edge cases", {
  expect_equal(rank_wt(5, 2), 0.5)
  expect_equal(rank_wt(c(1, 2), c(0, NA)), numeric(0))
  expect_error(rank_wt(1:2, 1))
})

test_that("ci_factory returns scoring functions and validates type", {
  expect_true(is.function(ci_factory("CI")))
  expect_true(is.function(ci_factory("CIg")))
  expect_true(is.function(ci_factory("CIc")))
  expect_error(ci_factory("bad"))
})

test_that("ci_factory computes expected CI variants on a simple example", {
  y <- cbind(c(10, 20, 30), c(1, 0, 1))
  wt <- c(1, 1, 2)

  ci <- ci_factory("CI")
  cig <- ci_factory("CIg")
  cic <- ci_factory("CIc")

  expect_equal(ci(y, wt), 2 / 15)
  expect_equal(cig(y, wt), 0.1)
  expect_equal(cic(y, wt), 0.4)
})

test_that("ci_factory drops incomplete and non-positive-weight rows", {
  y1 <- cbind(c(10, 20, 30, NA), c(1, 0, 1, 1))
  wt1 <- c(1, 1, 2, 1)

  y2 <- cbind(c(10, 20, 30), c(1, 0, 1))
  wt2 <- c(1, 1, 2)

  ci <- ci_factory("CI")
  expect_equal(ci(y1, wt1), ci(y2, wt2))

  y3 <- cbind(c(10, 20, 30, 40), c(1, 0, 1, 1))
  wt3 <- c(1, 1, 2, 0)
  expect_equal(ci(y3, wt3), ci(y2, wt2))
})

test_that("ci_factory returns zero for insufficient valid data", {
  ci <- ci_factory("CI")
  y <- cbind(c(10, NA), c(1, 0))
  wt <- c(1, 1)

  expect_equal(ci(y, wt), 0)
})

test_that("ci_factory handles degenerate denominators", {
  ci <- ci_factory("CI")
  cic <- ci_factory("CIc")

  y_mu0 <- cbind(c(10, 20, 30), c(0, 0, 0))
  expect_equal(ci(y_mu0, c(1, 1, 1)), 0)

  y_rng0 <- cbind(c(10, 20, 30), c(5, 5, 5))
  expect_equal(cic(y_rng0, c(1, 1, 1)), 0)
})

test_that("ci_factory is invariant to rescaling weights", {
  y <- cbind(c(10, 20, 30), c(1, 0, 1))
  ci <- ci_factory("CI")

  expect_equal(ci(y, c(1, 1, 2)), ci(y, c(10, 10, 20)))
})

test_that("weighted_ci_gain computes parent minus weighted child impurity", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  left <- c(TRUE, TRUE, FALSE, FALSE)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_equal(
    weighted_ci_gain(y, wt, left, mock_ci_fun),
    110
  )
})

test_that("weighted_ci_gain returns -Inf for invalid splits", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_equal(
    weighted_ci_gain(y, wt, c(TRUE, TRUE, TRUE, TRUE), mock_ci_fun),
    -Inf
  )
  expect_equal(
    weighted_ci_gain(
      y, c(0, 2, 3, 4),
      c(TRUE, FALSE, FALSE, FALSE), mock_ci_fun
    ),
    -Inf
  )
})

test_that("weighted_ci_gain validates input lengths", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_error(weighted_ci_gain(
    y, wt,
    c(TRUE, FALSE), mock_ci_fun
  ))
  expect_error(weighted_ci_gain(
    y, 1:3,
    c(TRUE, FALSE, TRUE, FALSE), mock_ci_fun
  ))
})

test_that("weighted_ci_gain is invariant to global weight rescaling with CI", {
  y <- cbind(
    ses = c(10, 20, 30, 40, 50, 60),
    health = c(1, 0, 1, 0, 1, 1)
  )
  left <- c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
  ci <- ci_factory("CI")

  expect_equal(
    weighted_ci_gain(y, rep(1, 6), left, ci),
    weighted_ci_gain(y, rep(10, 6), left, ci)
  )
})

test_that("best_numeric_split returns
 NULL when all x values are tied", {
  x <- c(5, 5, 5)
  y <- cbind(ses = c(10, 20, 30), health = c(1, 0, 1))
  wt <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split returns NULL
when no candidate split is admissible", {
  x <- c(1, 2, 3, 4)
  y <- cbind(ses = c(10, 20, 30, 40), health = c(1, 0, 1, 0))
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 3, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split chooses the cutpoint with the largest gain", {
  x <- c(4, 1, 3, 2)
  y <- cbind(
    ses = c(40, 10, 30, 20),
    health = c(10, 1, 3, 2)
  )
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 7, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 7L)
  expect_equal(split$breaks, 3.5)
  expect_equal(split$index, 1:2)
})

test_that("best_numeric_split respects minprob when selecting splits", {
  x <- c(1, 2, 3, 4, 5)
  y <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 5, 10, 20, 40)
  )
  wt <- rep(1, 5)
  ctrl <- list(minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 1, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$breaks, 3.5)
})

test_that(
  "best_factor_split returns NULL when fewer than two levels are present",
  {
    x_full <- factor(c("low", "low", "mid"), levels = c("low", "mid", "high"))
    keep <- c(TRUE, TRUE, FALSE)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 1, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that(
  "best_factor_split returns NULL when no admissible candidate split exists",
  {
    x_full <- factor(c("low", "mid", "high"), levels = c("low", "mid", "high"))
    keep <- rep(TRUE, 3)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 2, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that("best_factor_split chooses the best cumulative level split", {
  x_full <- factor(
    c("high", "low", "mid"),
    levels = c("low", "mid", "high", "unused")
  )
  keep <- rep(TRUE, 3)
  y_full <- cbind(
    ses = c(30, 10, 20),
    health = c(10, 1, 2)
  )
  wt_full <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 4,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 4L)
  expect_equal(split$index, c(1L, 1L, 2L, NA_integer_))
})

test_that("best_factor_split respects minprob when scoring candidates", {
  x_full <- factor(
    c("low", "mid", "mid", "high", "high"),
    levels = c("low", "mid", "high")
  )
  keep <- rep(TRUE, 5)
  y_full <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 2, 2, 10, 10)
  )
  wt_full <- rep(1, 5)
  ctrl <- list(minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 1,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$index, c(1L, 1L, 2L))
})

test_that("ci_splitfun returns the same numeric split as best_numeric_split", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 0, 1, 0, 1),
    income = c(2, 4, 6, 8, 10)
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = 3,
    ctrl = ctrl
  )

  expected <- best_numeric_split(
    x = toy_data$income,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    varid = 3,
    ctrl = ctrl,
    ci_fun = ci_factory("CI")
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$breaks, expected$breaks)
  expect_equal(split$varid, expected$varid)
})

test_that("ci_splitfun returns the same factor split as best_factor_split", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 2, 2, 10, 10),
    group = factor(c("low", "mid", "mid", "high", "high"))
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = 3,
    ctrl = ctrl
  )

  expected <- best_factor_split(
    x_full = toy_data$group,
    keep = seq_len(nrow(toy_data)),
    y_full = as.matrix(toy_data[c("rank", "outcome")]),
    wt_full = rep(1, nrow(toy_data)),
    varid = 3,
    ctrl = ctrl,
    ci_fun = ci_factory("CI")
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$index, expected$index)
  expect_equal(split$varid, expected$varid)
})

test_that(
  "ci_splitfun skips variables without admissible splits and tries next",
  {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 2, 2, 10, 10),
    constant = c(5, 5, 5, 5, 5),
    group = factor(c("low", "mid", "mid", "high", "high"))
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = c(3, 4),
    ctrl = ctrl
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 4L)
})

test_that("ci_splitfun errors when it cannot recover a two-column response", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(income = c(1, 2, 3), group = factor(c("a", "b", "a")))
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  expect_error(
    splitfun(
      model = NULL,
      trafo = NULL,
      data = toy_data,
      subset = seq_len(nrow(toy_data)),
      weights = rep(1, nrow(toy_data)),
      whichvar = 1:2,
      ctrl = ctrl
    ),
    "Unable to recover the two-column response"
  )
})

test_that("ctree_ci rejects negative weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  expect_error(
    ctree_ci(
      formula = cbind(rank, outcome) ~ income,
      data = toy_data,
      rank_name = "rank",
      outcome_name = "outcome",
      weights = c(1, -1, 1, 1)
    ),
    "weights must be non-negative"
  )
})

test_that("ctree_ci rejects non-integer weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  expect_error(
    ctree_ci(
      formula = cbind(rank, outcome) ~ income,
      data = toy_data,
      rank_name = "rank",
      outcome_name = "outcome",
      weights = c(1, 1.5, 1, 1)
    ),
    "integer case weights"
  )
})

test_that("ctree_ci fits a party object without explicit weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = partykit::ctree_control(mincriterion = 0, maxdepth = 1)
  )

  expect_s3_class(fit, "party")
})

test_that("ctree_ci accepts integer weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1, 2, 2, 3, 3),
    control = partykit::ctree_control(mincriterion = 0, maxdepth = 1)
  )

  expect_s3_class(fit, "party")
})

test_that("as_caseweights returns integer weights on the requested scale", {
  out <- as_caseweights(c(1, 2, 3), scale = 60L)

  expect_type(out, "integer")
  expect_equal(out, c(10L, 20L, 30L))
})

test_that("as_caseweights preserves weight proportions up to rounding", {
  out <- as_caseweights(c(0.2, 0.3, 0.5), scale = 100L)

  expect_equal(out, c(20L, 30L, 50L))
  expect_equal(sum(out), 100L)
})

test_that("as_caseweights rejects invalid input weights", {
  expect_error(as_caseweights(c(0, 0, 0)), "all weights are zero")
  expect_error(as_caseweights(c(1, -1, 2)))
})

test_that(
  "cf_ci fits a forest and stores one fitted row per observation", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- cf_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = partykit::ctree_control(mincriterion = 0, maxdepth = 1)
  )

  expect_s3_class(fit, "cforest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
})

test_that("cf_ci accepts explicit weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- cf_ci(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1, 2, 2, 3, 3),
    ntree = 10L,
    control = partykit::ctree_control(mincriterion = 0, maxdepth = 1)
  )

  expect_s3_class(fit, "cforest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
})

test_that("cf_ci honors mtry when supplied", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- cf_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = partykit::ctree_control(mincriterion = 0, maxdepth = 1)
  )

  expect_equal(fit$info$control$mtry, 1)
})
