# WARNING - Generated by {fusen} from dev/ci_tree_models.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_terminal_summary reports terminal-node diagnostics", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  summary <- ci_tree_terminal_summary(fit)
  printed <- utils::capture.output(print(fit))

  expect_s3_class(summary, "data.table")
  expect_true(all(c("node", "n", "ci", "outcome_mean", "rule") %in% names(summary)))
  expect_equal(nrow(summary), length(partykit::nodeids(fit, terminal = TRUE)))
  expect_true(all(nzchar(summary$rule)))
  expect_true(any(grepl("Greedy concentration-index tree", printed)))
  expect_true(any(grepl("Terminal node summary \\(highest criterion first\\)", printed)))
})

test_that("ci_forest_summary and print report ensemble diagnostics", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_forest(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  summary <- ci_forest_summary(fit)
  printed <- utils::capture.output(print(fit))

  expect_s3_class(summary, "data.table")
  expect_equal(summary$ntree, 3L)
  expect_true(all(c("mean_outcome", "prediction_ci") %in% names(summary)))
  expect_true(any(grepl("Greedy concentration-index forest", printed)))
})

test_that(
  "ci_forest fits a forest and stores one fitted row per observation", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
  expect_equal(length(stats::predict(fit)), nrow(toy_data))
  expect_equal(length(fit$trees), 10L)
  expect_true(all(vapply(fit$trees, function(tree) {
    inherits(tree$fit, "ci_tree") && inherits(tree$fit, "party")
  }, logical(1))))
})

test_that("ci_forest stores simple rpart-style variable importance", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  set.seed(20260525)
  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 5L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 2)
  )

  expect_type(fit$variable.importance, "double")
  expect_named(fit$variable.importance)
  expect_gt(length(fit$variable.importance), 0L)
  expect_true(all(fit$variable.importance >= 0))
  expect_equal(
    fit$variable.importance,
    sort(fit$variable.importance, decreasing = TRUE)
  )
})

test_that(".ci_forest_variable_importance returns numeric() with no split trees", {
  forest_vi <- getFromNamespace(".ci_forest_variable_importance", "ineqTrees")
  trees <- list(
    list(fit = list(variable.importance = numeric())),
    list(fit = list(variable.importance = numeric()))
  )

  expect_identical(forest_vi(trees), numeric())
})

test_that(".ci_forest_variable_importance sums trees in decreasing order", {
  forest_vi <- getFromNamespace(".ci_forest_variable_importance", "ineqTrees")
  trees <- list(
    list(fit = list(variable.importance = c(x2 = 1, x1 = 2))),
    list(fit = list(variable.importance = c(x1 = 3))),
    list(fit = list(variable.importance = numeric()))
  )
  out <- forest_vi(trees)

  expect_equal(out, c(x1 = 5, x2 = 1))
  expect_equal(out[["x1"]], 5)
})

test_that("ci_forest accepts explicit weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1, 2, 2, 3, 3),
    ntree = 10L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
})

test_that("ci_forest rejects non-finite weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  for (bad_weights in list(c(1, Inf, 1, 1), c(1, NaN, 1, 1), c(1, -Inf, 1, 1))) {
    expect_error(
      ci_forest(
        formula = cbind(rank, outcome) ~ income,
        data = toy_data,
        rank_name = "rank",
        outcome_name = "outcome",
        weights = bad_weights,
        ntree = 2L,
        control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
      ),
      "finite"
    )
  }
})

test_that("ci_forest validates perturb inputs", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )
  base_args <- list(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 2L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_error(
    do.call(ci_forest, c(base_args, list(perturb = 0.632))),
    "`perturb` must be `NULL` or a list\\."
  )
  expect_error(
    do.call(ci_forest, c(base_args, list(perturb = list(replace = NA)))),
    "perturb\\$replace"
  )
  expect_error(
    do.call(ci_forest, c(base_args, list(perturb = list(fraction = Inf)))),
    "perturb\\$fraction"
  )
  expect_error(
    do.call(ci_forest, c(base_args, list(perturb = list(fraction = 0)))),
    "perturb\\$fraction"
  )
})

test_that("ci_forest predicts on new data with old cforest-style FUN", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  pred <- stats::predict(
    fit,
    newdata = toy_data[c("income", "group")],
    FUN = function(y, w) stats::weighted.mean(y[, "outcome"], w)
  )

  expect_s3_class(fit, "ci_forest")
  expect_type(pred, "double")
  expect_equal(length(pred), nrow(toy_data))
  expect_true(all(is.finite(pred)))
})

test_that("ci_forest honors mtry when supplied", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_equal(fit$control$mtry, 1)
  expect_equal(fit$control$maxdepth, 1)
})

test_that("cf_ci remains a compatibility alias for ci_forest", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
})

test_that("ci_forest accepts level-dependent L split scoring", {
  toy_data <- data.frame(
    ses = c(1, 2, 3, 4, 5, 6),
    outcome = c(1, 1, 0, 0, 0, 1),
    x = c(1, 1, 2, 2, 3, 3)
  )

  fit <- ci_forest(
    formula = cbind(ses, outcome) ~ x,
    data = toy_data,
    rank_name = "ses",
    outcome_name = "outcome",
    type = "L",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(fit$type, "L")
})
