# WARNING - Generated by {fusen} from dev/model_selection.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_control_grid creates greedy controls only", {
  grid <- ci_tree_control_grid(
    minsplit = c(4, 6),
    minbucket = 2,
    minprob = c(0, 0.1),
    maxdepth = 1:2,
    min_gain = c(0, 0.01),
    mtry = c(1, 2),
    ntree = c(5, 10)
  )

  expect_s3_class(grid, "data.table")
  expect_equal(nrow(grid), 64L)
  expect_true(all(c(
    "minsplit", "minbucket", "minprob", "maxdepth", "min_gain", "mtry",
    "min_relative_gain", "ntree"
  ) %in% names(grid)))
  expect_false("mincriterion" %in% names(grid))
})

test_that("ci_dials_grid converts tidymodels-style names", {
  dials_grid <- data.frame(
    mtry = c(1L, 2L),
    min_n = c(5L, 10L),
    tree_depth = c(2L, 3L),
    trees = c(7L, 9L)
  )

  grid <- ci_dials_grid(dials_grid, minprob = 0.05)

  expect_s3_class(grid, "data.table")
  expect_equal(grid$minbucket, c(5L, 10L))
  expect_equal(grid$minsplit, c(10L, 20L))
  expect_equal(grid$maxdepth, c(2L, 3L))
  expect_equal(grid$mtry, c(1L, 2L))
  expect_equal(grid$ntree, c(7L, 9L))
  expect_equal(grid$minprob, c(0.05, 0.05))
  expect_equal(grid$min_relative_gain, c(0, 0))
})

test_that("ci_cv_folds creates reproducible folds", {
  folds_a <- ci_cv_folds(12, v = 3, seed = 99)
  folds_b <- ci_cv_folds(12, v = 3, seed = 99)

  expect_equal(folds_a, folds_b)
  expect_equal(sort(unique(folds_a)), 1:3)
  expect_equal(length(folds_a), 12L)
})

test_that("ci_cv_folds validates input", {
  expect_error(ci_cv_folds(3, v = 4), "`v` cannot exceed `n`")
  expect_error(ci_cv_folds(5, strata = 1:4), "`strata` must have length `n`")
})

test_that("predict_ci_tree_terminal_mean returns one prediction per row", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  pred <- predict_ci_tree_terminal_mean(fit, toy_data, outcome_name = "outcome")

  expect_type(pred, "double")
  expect_equal(length(pred), nrow(toy_data))
  expect_true(all(pred >= 0 & pred <= 1))
})

test_that("predict_ctree_ci_terminal_mean remains a compatibility alias", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_equal(
    predict_ctree_ci_terminal_mean(fit, toy_data, outcome_name = "outcome"),
    predict_ci_tree_terminal_mean(fit, toy_data, outcome_name = "outcome")
  )
})

test_that("ci_tree_validation_gain scores a fitted partition", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  score <- ci_tree_validation_gain(fit, toy_data, "rank", "outcome")

  expect_type(score, "double")
  expect_length(score, 1L)
  expect_true(is.finite(score))
})

test_that("relative validation gain scales validation gain by root impurity", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )
  weights <- rep(1, nrow(toy_data))
  y <- as.matrix(toy_data[c("rank", "outcome")])
  root_impurity <- ci_factory("CI")(y, weights)
  validation_gain <- ci_tree_validation_gain(
    fit, toy_data, "rank", "outcome",
    weights = weights,
    type = "CI",
    root_impurity = root_impurity
  )
  relative_gain <- getFromNamespace(
    ".ci_score_relative_validation_gain",
    "ineqTrees"
  )(
    fit = fit,
    new_data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = weights,
    type = "CI",
    root_impurity = root_impurity
  )

  expect_equal(relative_gain, validation_gain / abs(root_impurity))
})

test_that("ci_forest_validation_gain averages internal tree gains", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b"))
  )
  set.seed(11)
  forest <- ci_forest(
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 4L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )
  weights <- rep(1, nrow(toy_data))
  root_impurity <- ci_root_impurity(
    toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = weights,
    type = "CI"
  )

  score <- ci_forest_validation_gain(
    forest,
    toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = weights,
    type = "CI",
    root_impurity = root_impurity
  )
  manual <- mean(vapply(
    forest$trees,
    function(tree) {
      ci_tree_validation_gain(
        tree$fit,
        toy_data,
        rank_name = "rank",
        outcome_name = "outcome",
        weights = weights,
        type = "CI",
        root_impurity = root_impurity
      )
    },
    numeric(1)
  ))

  expect_equal(score, manual)
})

test_that("ci prediction metrics score simple binary predictions", {
  truth <- c(0, 1, 1, 0)
  estimate <- c(0.1, 0.8, 0.7, 0.2)

  expect_lt(ci_brier_score(truth, estimate), 0.1)
  expect_lt(ci_log_loss(truth, estimate), 0.4)
  expect_equal(ci_roc_auc(truth, estimate), 1)

  out <- ci_prediction_metrics(truth, estimate)
  expect_s3_class(out, "data.table")
  expect_true(all(c("brier", "log_loss", "roc_auc") %in% names(out)))
})
