# WARNING - Generated by {fusen} from dev/tidymodels_bridge.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("decision_tree can fit ci_tree through ineqTrees engine", {
  skip_if_not_installed("parsnip")
  skip_if_not_installed("hardhat")

  register_ineqtrees_parsnip()

  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b")),
    weight = 1
  )

  spec <- parsnip::decision_tree(tree_depth = 1, min_n = 1) |>
    parsnip::set_engine(
      "ineqTrees",
      rank_name = "rank",
      outcome_name = "outcome",
      type = "CIg",
      minsplit = 1,
      minprob = 0
    ) |>
    parsnip::set_mode("regression")

  fit <- parsnip::fit(
    spec,
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    case_weights = hardhat::importance_weights(toy_data$weight)
  )

  expect_s3_class(fit$fit, "ci_tree")

  pred <- predict(fit, new_data = toy_data)
  expect_s3_class(pred, "tbl_df")
  expect_true(".pred" %in% names(pred))
  expect_equal(nrow(pred), nrow(toy_data))

  nodes <- predict(fit, new_data = toy_data, type = "raw")
  expect_type(nodes, "integer")
  expect_equal(length(nodes), nrow(toy_data))
})

test_that("decision_tree engine maxdepth can override tree_depth", {
  skip_if_not_installed("parsnip")

  register_ineqtrees_parsnip()

  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16)
  )

  spec <- parsnip::decision_tree(tree_depth = 1, min_n = 1) |>
    parsnip::set_engine(
      "ineqTrees",
      rank_name = "rank",
      outcome_name = "outcome",
      minsplit = 1,
      minprob = 0,
      maxdepth = 2
    ) |>
    parsnip::set_mode("regression")

  fit <- parsnip::fit(
    spec,
    cbind(rank, outcome) ~ income,
    data = toy_data
  )

  expect_equal(unclass(fit$fit)$info$control$maxdepth, 2L)
})

test_that("parsnip wrappers accept a single-outcome formula", {
  skip_if_not_installed("parsnip")

  register_ineqtrees_parsnip()

  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16)
  )

  spec <- parsnip::decision_tree(tree_depth = 1, min_n = 1) |>
    parsnip::set_engine(
      "ineqTrees",
      rank_name = "rank",
      outcome_name = "outcome",
      minsplit = 1,
      minprob = 0
    ) |>
    parsnip::set_mode("regression")

  fit <- parsnip::fit(
    spec,
    outcome ~ income,
    data = toy_data
  )

  expect_s3_class(fit$fit, "ci_tree")
})

test_that("rand_forest can fit ci_forest through ineqTrees engine", {
  skip_if_not_installed("parsnip")
  skip_if_not_installed("hardhat")

  register_ineqtrees_parsnip()

  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b")),
    weight = 1
  )

  spec <- parsnip::rand_forest(trees = 3, mtry = 1, min_n = 1) |>
    parsnip::set_engine(
      "ineqTrees",
      rank_name = "rank",
      outcome_name = "outcome",
      type = "CIg",
      minsplit = 1,
      minprob = 0,
      maxdepth = 1
    ) |>
    parsnip::set_mode("regression")

  fit <- parsnip::fit(
    spec,
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    case_weights = hardhat::importance_weights(toy_data$weight)
  )

  expect_s3_class(fit$fit, "ci_forest")

  pred <- predict(fit, new_data = toy_data)
  expect_s3_class(pred, "tbl_df")
  expect_true(".pred" %in% names(pred))
  expect_equal(nrow(pred), nrow(toy_data))

  nodes <- predict(fit, new_data = toy_data, type = "raw")
  expect_true(is.matrix(nodes))
  expect_equal(nrow(nodes), nrow(toy_data))
})

test_that("ci_gain computes a yardstick-style metric", {
  toy_pred <- data.frame(
    truth = c(1, 0, 1, 0, 1, 1),
    pred = c(0.8, 0.2, 0.7, 0.3, 0.6, 0.9),
    rank = c(10, 20, 30, 40, 50, 60),
    node = c(1, 1, 2, 2, 2, 2),
    weight = 1
  )

  out <- ci_gain(
    toy_pred,
    truth = truth,
    estimate = pred,
    rank = rank,
    node = node,
    case_weights = weight,
    type = "CIg"
  )

  expect_s3_class(out, "tbl_df")
  expect_equal(out$.metric, "ci_gain")
  expect_true(is.finite(out$.estimate))
})

test_that("ci_gain_vec rejects non-finite case weights", {
  truth <- c(1, 0, 1)
  estimate <- c(0.8, 0.2, 0.7)
  rank <- c(10, 20, 30)
  node <- c(1, 1, 2)

  for (bad_weights in list(c(1, Inf, 1), c(1, NaN, 1), c(1, -Inf, 1))) {
    expect_error(
      ci_gain_vec(
        truth = truth,
        estimate = estimate,
        rank = rank,
        node = node,
        case_weights = bad_weights
      ),
      "finite"
    )
  }
})

test_that("ci_prediction_index computes prediction inequality", {
  toy_pred <- data.frame(
    truth = c(1, 0, 1, 0, 1, 1),
    pred = c(0.8, 0.2, 0.7, 0.3, 0.6, 0.9),
    rank = c(10, 20, 30, 40, 50, 60),
    weight = 1
  )

  out <- ci_prediction_index(
    toy_pred,
    truth = truth,
    estimate = pred,
    rank = rank,
    case_weights = weight,
    type = "CIg"
  )

  expect_s3_class(out, "tbl_df")
  expect_equal(out$.metric, "ci_prediction_index")
  expect_true(is.finite(out$.estimate))
})

test_that("ci_prediction_index_vec rejects non-finite case weights", {
  estimate <- c(0.8, 0.2, 0.7)
  rank <- c(10, 20, 30)

  for (bad_weights in list(c(1, Inf, 1), c(1, NaN, 1), c(1, -Inf, 1))) {
    expect_error(
      ci_prediction_index_vec(
        estimate = estimate,
        rank = rank,
        case_weights = bad_weights
      ),
      "finite"
    )
  }
})
