# WARNING - Generated by {fusen} from dev/ci_tree_builder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_control stores greedy tree controls", {
  ctrl <- ci_tree_control(
    minsplit = 10,
    minbucket = 3,
    minprob = 0.1,
    maxdepth = 2,
    min_gain = 0.01,
    mtry = 1
  )

  expect_equal(ctrl$minsplit, 10)
  expect_equal(ctrl$minbucket, 3)
  expect_equal(ctrl$minprob, 0.1)
  expect_equal(ctrl$maxdepth, 2)
  expect_equal(ctrl$min_gain, 0.01)
  expect_equal(ctrl$mtry, 1)
  expect_equal(ctrl$split_engine, "cpp")
})

test_that(".ci_tree_normalize_control accepts shared ctree controls", {
  ctrl <- ineqTrees::.ci_tree_normalize_control(
    partykit::ctree_control(
      minsplit = 5,
      minbucket = 2,
      minprob = 0,
      maxdepth = 1,
      mtry = 1
    )
  )

  expect_equal(ctrl$minsplit, 5L)
  expect_equal(ctrl$minbucket, 2L)
  expect_equal(ctrl$minprob, 0)
  expect_equal(ctrl$maxdepth, 1)
  expect_equal(ctrl$mtry, 1L)
  expect_equal(ctrl$split_engine, "cpp")
})

test_that("ci_tree_control accepts R split engine fallback", {
  ctrl <- ci_tree_control(split_engine = "R")
  norm <- ineqTrees::.ci_tree_normalize_control(ctrl)

  expect_equal(norm$split_engine, "R")
})

test_that(".ci_tree_normalize_control rejects unknown split engines", {
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(split_engine = "fortran")),
    "split_engine"
  )
})
