# WARNING - Generated by {fusen} from dev/ci_split_search.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("best_numeric_split returns
 NULL when all x values are tied", {
  x <- c(5, 5, 5)
  y <- cbind(ses = c(10, 20, 30), health = c(1, 0, 1))
  wt <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split returns NULL
when no candidate split is admissible", {
  x <- c(1, 2, 3, 4)
  y <- cbind(ses = c(10, 20, 30, 40), health = c(1, 0, 1, 0))
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 3, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split chooses the cutpoint with the largest gain", {
  x <- c(4, 1, 3, 2)
  y <- cbind(
    ses = c(40, 10, 30, 20),
    health = c(10, 1, 3, 2)
  )
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 7, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 7L)
  expect_equal(split$breaks, 3.5)
  expect_equal(split$index, 1:2)
})

test_that("best_numeric_split respects minprob when selecting splits", {
  x <- c(1, 2, 3, 4, 5)
  y <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 5, 10, 20, 40)
  )
  wt <- rep(1, 5)
  ctrl <- list(minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 1, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$breaks, 3.5)
})

test_that("best_numeric_split can return a reusable split candidate", {
  x <- c(4, 1, 3, 2)
  y <- cbind(
    ses = c(40, 10, 30, 20),
    health = c(10, 1, 3, 2)
  )
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  candidate <- best_numeric_split(
    x = x,
    y = y,
    wt = wt,
    varid = 7,
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    return = "candidate"
  )

  expect_type(candidate$gain, "double")
  expect_s3_class(candidate$partysplit, "partysplit")
  expect_equal(candidate$left, c(FALSE, TRUE, TRUE, TRUE))
})

test_that(
  "best_factor_split returns NULL when fewer than two levels are present",
  {
    x_full <- factor(c("low", "low", "mid"), levels = c("low", "mid", "high"))
    keep <- c(TRUE, TRUE, FALSE)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 1, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that(
  "best_factor_split returns NULL when no admissible candidate split exists",
  {
    x_full <- factor(c("low", "mid", "high"), levels = c("low", "mid", "high"))
    keep <- rep(TRUE, 3)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 2, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that("best_factor_split chooses the best cumulative level split", {
  x_full <- factor(
    c("high", "low", "mid"),
    levels = c("low", "mid", "high", "unused")
  )
  keep <- rep(TRUE, 3)
  y_full <- cbind(
    ses = c(30, 10, 20),
    health = c(10, 1, 2)
  )
  wt_full <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 4,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 4L)
  expect_equal(split$index, c(1L, 1L, 2L, NA_integer_))
})

test_that("best_factor_split respects minprob when scoring candidates", {
  x_full <- factor(
    c("low", "mid", "mid", "high", "high"),
    levels = c("low", "mid", "high")
  )
  keep <- rep(TRUE, 5)
  y_full <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 2, 2, 10, 10)
  )
  wt_full <- rep(1, 5)
  ctrl <- list(minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 1,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$index, c(1L, 1L, 2L))
})

test_that("best_factor_split can return a reusable split candidate", {
  x_full <- factor(
    c("high", "low", "mid"),
    levels = c("low", "mid", "high", "unused")
  )
  keep <- rep(TRUE, 3)
  y_full <- cbind(
    ses = c(30, 10, 20),
    health = c(10, 1, 2)
  )
  wt_full <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  candidate <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 4,
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    return = "candidate"
  )

  expect_type(candidate$gain, "double")
  expect_s3_class(candidate$partysplit, "partysplit")
  expect_equal(candidate$left, c(FALSE, TRUE, TRUE))
})

test_that("best_global_ci_split searches variables globally by CI gain", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 5, 10, 20, 40),
    weak = c(1, 1, 1, 1, 1),
    strong = c(1, 2, 3, 4, 5)
  )
  ctrl <- ci_tree_control(minsplit = 1, minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_global_ci_split(
    x = toy_data,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    vars = 3:4
  )

  expect_equal(split$varid, 4L)
  expect_s3_class(split$partysplit, "partysplit")
})

test_that("best_global_ci_split respects min_gain", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 2, 3, 4),
    x = c(1, 2, 3, 4)
  )
  ctrl <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    min_gain = Inf
  )

  split <- best_global_ci_split(
    x = toy_data,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    ctrl = ctrl,
    ci_fun = ci_factory("CI"),
    vars = 3
  )

  expect_null(split)
})
