# WARNING - Generated by {fusen} from dev/ci_tree_models.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_splitfun returns the same numeric split as best_numeric_split", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 0, 1, 0, 1),
    income = c(2, 4, 6, 8, 10)
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = 3,
    ctrl = ctrl
  )

  expected <- best_numeric_split(
    x = toy_data$income,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    varid = 3,
    ctrl = ctrl,
    ci_fun = ci_factory("CI")
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$breaks, expected$breaks)
  expect_equal(split$varid, expected$varid)
})

test_that("ci_splitfun returns the same factor split as best_factor_split", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 2, 2, 10, 10),
    group = factor(c("low", "mid", "mid", "high", "high"))
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = 3,
    ctrl = ctrl
  )

  expected <- best_factor_split(
    x_full = toy_data$group,
    keep = seq_len(nrow(toy_data)),
    y_full = as.matrix(toy_data[c("rank", "outcome")]),
    wt_full = rep(1, nrow(toy_data)),
    varid = 3,
    ctrl = ctrl,
    ci_fun = ci_factory("CI")
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$index, expected$index)
  expect_equal(split$varid, expected$varid)
})

test_that(
  "ci_splitfun skips variables without admissible splits and tries next",
  {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 2, 2, 10, 10),
    constant = c(5, 5, 5, 5, 5),
    group = factor(c("low", "mid", "mid", "high", "high"))
  )
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  split <- splitfun(
    model = NULL,
    trafo = NULL,
    data = toy_data,
    subset = seq_len(nrow(toy_data)),
    weights = rep(1, nrow(toy_data)),
    whichvar = c(3, 4),
    ctrl = ctrl
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 4L)
})

test_that("ci_splitfun errors when it cannot recover a two-column response", {
  splitfun <- ci_splitfun("rank", "outcome", "CI")
  toy_data <- data.frame(income = c(1, 2, 3), group = factor(c("a", "b", "a")))
  ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)

  expect_error(
    splitfun(
      model = NULL,
      trafo = NULL,
      data = toy_data,
      subset = seq_len(nrow(toy_data)),
      weights = rep(1, nrow(toy_data)),
      whichvar = 1:2,
      ctrl = ctrl
    ),
    "Unable to recover the two-column response"
  )
})

test_that("ci_tree rejects negative weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  expect_error(
    ci_tree(
      formula = cbind(rank, outcome) ~ income,
      data = toy_data,
      rank_name = "rank",
      outcome_name = "outcome",
      weights = c(1, -1, 1, 1)
    ),
    "weights must be non-negative"
  )
})

test_that("ci_tree accepts non-integer weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  fit <- ci_tree(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1.5, 1, 1),
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_tree")
})

test_that("ci_tree fits a party object without explicit weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_tree(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "party")
  expect_s3_class(fit, "ci_tree")
  expect_s3_class(fit, "constparty")
  expect_true(fit$info$greedy)
  expect_equal(max(partykit::nodeids(fit, terminal = TRUE)), 3L)
})

test_that("ci_tree accepts integer weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_tree(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1, 2, 2, 3, 3),
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "party")
  expect_s3_class(fit, "ci_tree")
})

test_that("ci_tree returns partykit predictions and terminal nodes", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_tree(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_equal(length(predict(fit, type = "node")), nrow(toy_data))
  expect_equal(length(predict(fit, type = "response")), nrow(toy_data))
  expect_equal(length(partykit::nodeids(fit, terminal = TRUE)), 2L)
})

test_that("ctree_ci remains a compatibility alias for ci_tree", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_tree(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_tree")
})

test_that("as_caseweights returns integer weights on the requested scale", {
  out <- as_caseweights(c(1, 2, 3), scale = 60L)

  expect_type(out, "integer")
  expect_equal(out, c(10L, 20L, 30L))
})

test_that("as_caseweights preserves weight proportions up to rounding", {
  out <- as_caseweights(c(0.2, 0.3, 0.5), scale = 100L)

  expect_equal(out, c(20L, 30L, 50L))
  expect_equal(sum(out), 100L)
})

test_that("as_caseweights rejects invalid input weights", {
  expect_error(as_caseweights(c(0, 0, 0)), "all weights are zero")
  expect_error(as_caseweights(c(1, -1, 2)))
})
