# WARNING - Generated by {fusen} from dev/model_selection.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("tune_ci_tree selects greedy tree controls and CI type", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b"))
  )
  tree_grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1
  )
  forest_grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1:2
  )

  tuned <- tune_ci_tree(
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = c("CI", "CIg"),
    control_grid = tree_grid,
    v = 2,
    seed = 1,
    refit = TRUE
  )

  expect_s3_class(tuned, "ci_tree_tuning")
  expect_s3_class(tuned$fold_results, "data.table")
  expect_s3_class(tuned$summary, "data.table")
  expect_equal(nrow(tuned$fold_results), nrow(tree_grid) * 2L * 2L)
  expect_s3_class(tuned$best_fit, "ci_tree")
  expect_true(tuned$best_type %in% c("CI", "CIg"))
  expect_true("type" %in% names(tuned$best_params))
  expect_false("mincriterion" %in% names(tuned$best_params))
})

test_that("tune_ci_tree can minimize Brier score", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16)
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1
  )

  tuned <- tune_ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = "CI",
    control_grid = grid,
    v = 2,
    seed = 2,
    metric = "brier",
    refit = FALSE
  )

  expect_equal(tuned$metric_direction, "minimize")
  expect_null(tuned$best_fit)
  expect_true(is.finite(tuned$summary$mean_score[1]))
})

test_that("tune_ci_forest tunes greedy forests and returns a surrogate", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b"))
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1:2,
    mtry = 1:2,
    ntree = c(3L, 5L)
  )

  tuned <- tune_ci_forest(
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = c("CI", "CIg"),
    control_grid = grid,
    v = 2,
    seed = 3,
    refit = TRUE
  )

  expect_s3_class(tuned, "ci_forest_tuning")
  expect_equal(tuned$model, "forest")
  expect_s3_class(tuned$best_fit, "ci_forest")
  expect_s3_class(tuned$best_surrogate, "ci_tree")
  expect_equal(nrow(tuned$fold_results), nrow(grid) * 2L * 2L)
  expect_true("ntree" %in% names(tuned$best_params))
  expect_true("type" %in% names(tuned$best_params))
  expect_true("forest_risk" %in% names(tuned$best_surrogate_data))
  expect_true(tuned$best_type %in% c("CI", "CIg"))
  expect_true(is.finite(tuned$summary$mean_score[1]))
})

test_that("legacy tuning names remain compatibility aliases", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16)
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1,
    ntree = 3L
  )

  tree_tuned <- tune_ctree_ci(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = "CI",
    control_grid = grid,
    v = 2,
    seed = 4,
    refit = FALSE
  )
  forest_tuned <- tune_cf_ci(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = "CI",
    control_grid = grid,
    v = 2,
    seed = 5,
    refit = FALSE
  )

  expect_s3_class(tree_tuned, "ci_tree_tuning")
  expect_s3_class(forest_tuned, "ci_forest_tuning")
})
