# WARNING - Generated by {fusen} from dev/ci_tree_models.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_terminal_summary reports terminal-node diagnostics", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_tree(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  summary <- ci_tree_terminal_summary(fit)
  printed <- utils::capture.output(print(fit))

  expect_s3_class(summary, "data.table")
  expect_true(all(c("node", "n", "ci", "outcome_mean", "rule") %in% names(summary)))
  expect_equal(nrow(summary), length(partykit::nodeids(fit, terminal = TRUE)))
  expect_true(all(nzchar(summary$rule)))
  expect_true(any(grepl("Greedy concentration-index tree", printed)))
  expect_true(any(grepl("Terminal node summary \\(highest criterion first\\)", printed)))
})

test_that("ci_forest_summary and print report ensemble diagnostics", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ci_forest(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  summary <- ci_forest_summary(fit)
  printed <- utils::capture.output(print(fit))

  expect_s3_class(summary, "data.table")
  expect_equal(summary$ntree, 3L)
  expect_true(all(c("mean_outcome", "prediction_ci") %in% names(summary)))
  expect_true(any(grepl("Greedy concentration-index forest", printed)))
})

test_that(
  "ci_forest fits a forest and stores one fitted row per observation", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
  expect_equal(length(stats::predict(fit)), nrow(toy_data))
  expect_equal(length(fit$trees), 10L)
  expect_true(all(vapply(fit$trees, function(tree) {
    inherits(tree$fit, "ci_tree") && inherits(tree$fit, "party")
  }, logical(1))))
})

test_that("ci_forest parallel fitting preserves the serial object structure", {
  skip_if_not_installed("future")
  skip_if_not_installed("future.apply")

  old_plan <- future::plan()
  on.exit(future::plan(old_plan), add = TRUE)
  future::plan(future::sequential)

  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  set.seed(10)
  serial_fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 4L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )
  set.seed(10)
  parallel_fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 4L,
    mtry = 1L,
    parallel = TRUE,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(parallel_fit, "ci_forest")
  expect_named(parallel_fit, names(serial_fit))
  expect_equal(length(parallel_fit$trees), length(serial_fit$trees))
  expect_equal(dim(parallel_fit$inbag), dim(serial_fit$inbag))
  expect_named(parallel_fit$trees[[1]], names(serial_fit$trees[[1]]))
  expect_s3_class(parallel_fit$trees[[1]]$fit, "ci_tree")
})

test_that("ci_forest accepts explicit weights", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    weights = c(1, 1, 2, 2, 3, 3),
    ntree = 10L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(nrow(stats::fitted(fit)), nrow(toy_data))
})

test_that("ci_forest predicts on new data with old cforest-style FUN", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  pred <- stats::predict(
    fit,
    newdata = toy_data[c("income", "group")],
    FUN = function(y, w) stats::weighted.mean(y[, "outcome"], w)
  )

  expect_s3_class(fit, "ci_forest")
  expect_type(pred, "double")
  expect_equal(length(pred), nrow(toy_data))
  expect_true(all(is.finite(pred)))
})

test_that("ci_forest honors mtry when supplied", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 10L,
    mtry = 1L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_equal(fit$control$mtry, 1)
  expect_equal(fit$control$maxdepth, 1)
})

test_that("cf_ci remains a compatibility alias for ci_forest", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )

  fit <- ci_forest(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
})

test_that("ci_forest accepts level-dependent L split scoring", {
  toy_data <- data.frame(
    ses = c(1, 2, 3, 4, 5, 6),
    outcome = c(1, 1, 0, 0, 0, 1),
    x = c(1, 1, 2, 2, 3, 3)
  )

  fit <- ci_forest(
    formula = cbind(ses, outcome) ~ x,
    data = toy_data,
    rank_name = "ses",
    outcome_name = "outcome",
    type = "L",
    ntree = 3L,
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(fit, "ci_forest")
  expect_equal(fit$type, "L")
})
