# WARNING - Generated by {fusen} from dev/ci_ranking.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("rank_wt computes weighted midpoint ranks", {
  expect_equal(
    rank_wt(c(10, 20, 30), c(1, 1, 2)),
    c(0.125, 0.375, 0.75)
  )
})

test_that("rank_wt returns ranks in the order of retained inputs", {
  expect_equal(
    rank_wt(c(20, 10, 30), c(1, 1, 2)),
    c(0.375, 0.125, 0.75)
  )
})

test_that("rank_wt drops missing and non-positive weights before ranking", {
  expect_equal(
    rank_wt(c(2, NA, 1, 3), c(1, 1, 0, 2)),
    c(1 / 6, 2 / 3)
  )
})

test_that("rank_wt handles edge cases", {
  expect_equal(rank_wt(5, 2), 0.5)
  expect_equal(rank_wt(c(1, 2), c(0, NA)), numeric(0))
  expect_error(rank_wt(1:2, 1))
})

test_that("ci_factory returns scoring functions and validates type", {
  expect_true(is.function(ci_factory("CI")))
  expect_true(is.function(ci_factory("CIg")))
  expect_true(is.function(ci_factory("CIc")))
  expect_error(ci_factory("bad"))
})

test_that("ci_factory computes expected CI variants on a simple example", {
  y <- cbind(c(10, 20, 30), c(1, 0, 1))
  wt <- c(1, 1, 2)

  ci <- ci_factory("CI")
  cig <- ci_factory("CIg")
  cic <- ci_factory("CIc")

  expect_equal(ci(y, wt), 2 / 15)
  expect_equal(cig(y, wt), 0.1)
  expect_equal(cic(y, wt), 0.4)
})

test_that("ci_factory drops incomplete and non-positive-weight rows", {
  y1 <- cbind(c(10, 20, 30, NA), c(1, 0, 1, 1))
  wt1 <- c(1, 1, 2, 1)

  y2 <- cbind(c(10, 20, 30), c(1, 0, 1))
  wt2 <- c(1, 1, 2)

  ci <- ci_factory("CI")
  expect_equal(ci(y1, wt1), ci(y2, wt2))

  y3 <- cbind(c(10, 20, 30, 40), c(1, 0, 1, 1))
  wt3 <- c(1, 1, 2, 0)
  expect_equal(ci(y3, wt3), ci(y2, wt2))
})

test_that("ci_factory returns zero for insufficient valid data", {
  ci <- ci_factory("CI")
  y <- cbind(c(10, NA), c(1, 0))
  wt <- c(1, 1)

  expect_equal(ci(y, wt), 0)
})

test_that("ci_factory handles degenerate denominators", {
  ci <- ci_factory("CI")
  cic <- ci_factory("CIc")

  y_mu0 <- cbind(c(10, 20, 30), c(0, 0, 0))
  expect_equal(ci(y_mu0, c(1, 1, 1)), 0)

  y_rng0 <- cbind(c(10, 20, 30), c(5, 5, 5))
  expect_equal(cic(y_rng0, c(1, 1, 1)), 0)
})

test_that("ci_factory is invariant to rescaling weights", {
  y <- cbind(c(10, 20, 30), c(1, 0, 1))
  ci <- ci_factory("CI")

  expect_equal(ci(y, c(1, 1, 2)), ci(y, c(10, 10, 20)))
})

test_that("weighted_ci_gain computes parent minus weighted child impurity", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  left <- c(TRUE, TRUE, FALSE, FALSE)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_equal(
    weighted_ci_gain(y, wt, left, mock_ci_fun),
    110
  )
})

test_that("weighted_ci_gain returns -Inf for invalid splits", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_equal(
    weighted_ci_gain(y, wt, c(TRUE, TRUE, TRUE, TRUE), mock_ci_fun),
    -Inf
  )
  expect_equal(
    weighted_ci_gain(
      y, c(0, 2, 3, 4),
      c(TRUE, FALSE, FALSE, FALSE), mock_ci_fun
    ),
    -Inf
  )
})

test_that("weighted_ci_gain validates input lengths", {
  y <- cbind(ses = 1:4, health = c(10, 20, 30, 40))
  wt <- c(1, 2, 3, 4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)

  expect_error(weighted_ci_gain(
    y, wt,
    c(TRUE, FALSE), mock_ci_fun
  ))
  expect_error(weighted_ci_gain(
    y, 1:3,
    c(TRUE, FALSE, TRUE, FALSE), mock_ci_fun
  ))
})

test_that("weighted_ci_gain is invariant to global weight rescaling with CI", {
  y <- cbind(
    ses = c(10, 20, 30, 40, 50, 60),
    health = c(1, 0, 1, 0, 1, 1)
  )
  left <- c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
  ci <- ci_factory("CI")

  expect_equal(
    weighted_ci_gain(y, rep(1, 6), left, ci),
    weighted_ci_gain(y, rep(10, 6), left, ci)
  )
})
