# WARNING - Generated by {fusen} from dev/ci_tree_builder.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_control stores greedy tree controls", {
  default_ctrl <- ci_tree_control()
  ctrl <- ci_tree_control(
    minsplit = 10,
    minbucket = 3,
    minprob = 0.1,
    maxdepth = 2,
    min_gain = 0.01,
    min_relative_gain = 0.05,
    mtry = 1
  )

  expect_equal(ctrl$minsplit, 10)
  expect_equal(ctrl$minbucket, 3)
  expect_equal(ctrl$minprob, 0.1)
  expect_equal(ctrl$maxdepth, 2)
  expect_equal(ctrl$min_gain, 0.01)
  expect_equal(ctrl$min_relative_gain, 0.05)
  expect_equal(ctrl$mtry, 1)
  expect_equal(ctrl$split_engine, "cpp")
  expect_equal(ctrl$factor_split, "auto")
  expect_equal(
    ctrl$max_factor_levels_partition,
    default_ctrl$max_factor_levels_partition
  )
  expect_equal(ctrl$max_factor_partitions, default_ctrl$max_factor_partitions)
})

test_that(".ci_tree_normalize_control accepts shared ctree controls", {
  ctrl <- ineqTrees::.ci_tree_normalize_control(
    partykit::ctree_control(
      minsplit = 5,
      minbucket = 2,
      minprob = 0,
      maxdepth = 1,
      mtry = 1
    )
  )

  expect_equal(ctrl$minsplit, 5L)
  expect_equal(ctrl$minbucket, 2L)
  expect_equal(ctrl$minprob, 0)
  expect_equal(ctrl$maxdepth, 1)
  expect_equal(ctrl$mtry, 1L)
  expect_equal(ctrl$split_engine, "cpp")
})

test_that("ci_tree_control accepts R split engine fallback", {
  ctrl <- ci_tree_control(split_engine = "R")
  norm <- ineqTrees::.ci_tree_normalize_control(ctrl)

  expect_equal(norm$split_engine, "R")
})

test_that(".ci_tree_normalize_control rejects unknown split engines", {
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(split_engine = "fortran")),
    "split_engine"
  )
})

test_that(".ci_tree_normalize_control rejects non-finite structural controls", {
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(minsplit = Inf)),
    "control\\$minsplit.*finite"
  )
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(minbucket = Inf)),
    "control\\$minbucket.*finite"
  )
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(maxdepth = Inf)),
    "control\\$maxdepth.*finite"
  )
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(minprob = Inf)),
    "control\\$minprob.*finite"
  )
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(min_relative_gain = Inf)),
    "control\\$min_relative_gain.*finite"
  )
})

test_that("ci_tree_control validates factor split controls", {
  ctrl <- ci_tree_control(
    factor_split = "partition",
    max_factor_levels_partition = 12,
    max_factor_partitions = 2048
  )
  norm <- ineqTrees::.ci_tree_normalize_control(ctrl)

  expect_equal(norm$factor_split, "partition")
  expect_equal(norm$max_factor_levels_partition, 12L)
  expect_equal(norm$max_factor_partitions, 2048)
  expect_error(
    ineqTrees::.ci_tree_normalize_control(list(factor_split = "random")),
    "factor_split"
  )
})

test_that(".ci_tree_variable_importance returns numeric() for a no-split tree", {
  tree_vi <- getFromNamespace(".ci_tree_variable_importance", "ineqTrees")
  node <- partykit::partynode(id = 1L, info = list())

  expect_identical(tree_vi(node), numeric())
})

test_that(".ci_tree_variable_importance returns one named score for one split", {
  tree_vi <- getFromNamespace(".ci_tree_variable_importance", "ineqTrees")
  leaf_node <- function(id) partykit::partynode(id = id, info = list())
  node <- partykit::partynode(
    id = 1L,
    split = partykit::partysplit(varid = 1L, breaks = 0, index = 1:2),
    kids = list(leaf_node(2L), leaf_node(3L)),
    info = list(varname = "x1", gain = 2)
  )

  expect_equal(tree_vi(node), c(x1 = 2))
})

test_that(".ci_tree_variable_importance sums repeated gains in decreasing order", {
  tree_vi <- getFromNamespace(".ci_tree_variable_importance", "ineqTrees")
  leaf_node <- function(id) partykit::partynode(id = id, info = list())
  left_child <- partykit::partynode(
    id = 2L,
    split = partykit::partysplit(varid = 2L, breaks = 0, index = 1:2),
    kids = list(leaf_node(4L), leaf_node(5L)),
    info = list(varname = "x2", gain = 1)
  )
  right_child <- partykit::partynode(
    id = 3L,
    split = partykit::partysplit(varid = 1L, breaks = 0, index = 1:2),
    kids = list(leaf_node(6L), leaf_node(7L)),
    info = list(varname = "x1", gain = 1)
  )
  root <- partykit::partynode(
    id = 1L,
    split = partykit::partysplit(varid = 1L, breaks = 0, index = 1:2),
    kids = list(left_child, right_child),
    info = list(varname = "x1", gain = 2)
  )
  out <- tree_vi(root)

  expect_equal(out, c(x1 = 3, x2 = 1))
  expect_equal(out[["x1"]], 3)
})
