# WARNING - Generated by {fusen} from dev/shap_decomposition.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fractional_rank computes average fractional ranks", {
  expect_equal(
    fractional_rank(c(10, 20, 20, 40)),
    c(0.125, 0.5, 0.5, 0.875)
  )
})

test_that("fractional_rank handles missing values and validates inputs", {
  expect_equal(
    fractional_rank(c(1, NA, 3), na_rm = TRUE),
    c(0.25, 0.75)
  )

  expect_error(fractional_rank(c(1, NA, 3)), "missing values")
  expect_error(fractional_rank(c(1, 2), ties_method = "first"), "ties_method")
  expect_error(fractional_rank(list(1, 2)), "atomic vector")
})

test_that("shap_conc_decomp decomposes a wide SHAP table", {
  shap <- data.frame(
    education = c(1, 0, -1),
    water = c(0, 1, 1)
  )

  out <- shap_conc_decomp(
    shap = shap,
    rank = c(1, 2, 3),
    baseline = 2
  )

  expect_s3_class(out, "shap_ci_decomposition")
  expect_equal(out$diagnostics$n, 3)
  expect_equal(out$diagnostics$weight_sum, 3)
  expect_equal(out$diagnostics$mean_prediction, 8 / 3)
  expect_equal(out$diagnostics$concentration_index, 1 / 12)
  expect_equal(out$diagnostics$signed_concentration_index, -1 / 12)
  expect_equal(out$diagnostics$score_direction, -1)
  expect_equal(out$diagnostics$shap_sum, 1 / 12)
  expect_equal(out$diagnostics$additivity_gap, 0, tolerance = 1e-12)
  expect_equal(out$diagnostics$centered_rank_sum, 0, tolerance = 1e-12)
  expect_equal(out$diagnostics$prediction_source, "baseline + rowSums(shap)")

  expect_equal(out$contributions$feature, c("education", "water"))
  expect_equal(out$contributions$D_k_SHAP, c(1 / 6, -1 / 12))
  expect_equal(out$contributions$pct_contribution, c(200, -100))
  expect_equal(out$contributions$abs_contribution, c(1 / 6, 1 / 12))
})

test_that("shap_conc_decomp reshapes DALEX-like SHAP tables", {
  wide_shap <- data.frame(
    education = c(1, 0, -1),
    water = c(0, 1, 1)
  )
  dalex_like <- data.frame(
    "_id_" = rep(1:3, each = 3),
    "_vname_" = rep(c("_baseline_", "education", "water"), times = 3),
    "_attribution_" = c(2, 1, 0, 2, 0, 1, 2, -1, 1),
    check.names = FALSE
  )

  from_wide <- shap_conc_decomp(
    shap = wide_shap,
    rank = c(1, 2, 3),
    baseline = 2
  )
  from_dalex <- shap_conc_decomp(
    shap = dalex_like,
    rank = c(1, 2, 3),
    baseline = 2,
    from_dalex = TRUE
  )

  expect_equal(from_dalex$diagnostics, from_wide$diagnostics)
  expect_equal(
    from_dalex$contributions[, c("feature", "D_k_SHAP")],
    from_wide$contributions[, c("feature", "D_k_SHAP")]
  )
})

test_that("shap_conc_decomp drops incomplete rows with na_rm", {
  shap <- data.frame(
    x1 = c(1, NA, 0, 2),
    x2 = c(0, 1, 1, 1)
  )
  prediction <- c(2, 3, NA, 4)

  out <- shap_conc_decomp(
    shap = shap,
    rank = c(1, 2, 3, 4),
    prediction = prediction,
    na_rm = TRUE,
    sort = FALSE
  )

  expect_equal(out$diagnostics$n, 2)
  expect_equal(out$diagnostics$prediction_source, "prediction")
  expect_equal(out$diagnostics$concentration_index, 1 / 6)
  expect_equal(out$diagnostics$additivity_gap, 0, tolerance = 1e-12)
  expect_equal(out$contributions$feature, c("x1", "x2"))
  expect_equal(out$contributions$D_k_SHAP, c(1 / 12, 1 / 12))
})

test_that("shap_conc_decomp uses ci_factory scores for weighted variants", {
  shap <- data.frame(
    education = c(1, 0, -1, 1),
    water = c(0, 1, 1, -1)
  )
  rank <- c(4, 1, 3, 2)
  weights <- c(1, 2, 1, 3)
  prediction <- 2 + rowSums(shap)

  for (type in c("CI", "CIg", "CIc")) {
    out <- shap_conc_decomp(
      shap = shap,
      rank = rank,
      type = type,
      baseline = 2,
      weights = weights,
      sort = FALSE
    )

    expect_equal(
      out$diagnostics$concentration_index,
      ci_factory(type)(cbind(rank = rank, outcome = prediction), weights)
    )
    expect_equal(
      out$diagnostics$shap_sum,
      out$diagnostics$concentration_index,
      tolerance = 1e-12
    )
    expect_equal(out$diagnostics$weight_sum, sum(weights))
  }
})

test_that("shap_conc_decomp supports level-dependent L decomposition", {
  shap <- data.frame(
    education = c(1, 0, -1),
    water = c(0, 1, 1)
  )

  out <- shap_conc_decomp(
    shap = shap,
    rank = c(1, 2, 3),
    type = "L",
    baseline = 2,
    sort = FALSE
  )

  expect_equal(out$diagnostics$type, "L")
  expect_equal(out$diagnostics$concentration_index, 1 / 6)
  expect_equal(out$diagnostics$signed_concentration_index, -1 / 6)
  expect_equal(out$diagnostics$shap_sum, 1 / 6)
  expect_equal(out$diagnostics$additivity_gap, 0, tolerance = 1e-12)
  expect_equal(out$diagnostics$centered_rank_sum, 0, tolerance = 1e-12)

  expect_equal(out$contributions$feature, c("education", "water"))
  expect_equal(out$contributions$D_k_SHAP, c(1 / 3, -1 / 6))
  expect_equal(out$contributions$pct_contribution, c(200, -100))
})

test_that("shap_conc_decomp validates key inputs", {
  shap <- data.frame(x1 = c(1, -1), x2 = c(0, 0))

  expect_error(
    shap_conc_decomp(shap = shap, rank = 1:3, baseline = 0),
    "length equal"
  )
  expect_error(
    shap_conc_decomp(shap = shap, rank = c(1, 2)),
    "Supply either `prediction` or `baseline`"
  )
  expect_error(
    shap_conc_decomp(shap = shap, rank = c(1, 2), baseline = 0),
    "mean prediction is numerically zero"
  )
  expect_error(
    shap_conc_decomp(
      shap = data.frame(x1 = c(1, NA)),
      rank = c(1, 2),
      baseline = 1
    ),
    "Columns with NA"
  )
  expect_error(
    shap_conc_decomp(shap = shap, rank = c(1, NA), baseline = 1),
    "missing values"
  )
  expect_error(
    shap_conc_decomp(shap = shap, rank = c(1, 2), baseline = 1,
      weights = c(1, NA)
    ),
    "weights"
  )
  expect_error(
    shap_conc_decomp(shap = shap, rank = c(-1, 1), type = "L", baseline = 1),
    "mean socioeconomic level"
  )
})
