# WARNING - Generated by {fusen} from dev/ci_split_search.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("best_numeric_split returns
 NULL when all x values are tied", {
  x <- c(5, 5, 5)
  y <- cbind(ses = c(10, 20, 30), health = c(1, 0, 1))
  wt <- rep(1, 3)
  ctrl <- list(minbucket = 1, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split returns NULL
when no candidate split is admissible", {
  x <- c(1, 2, 3, 4)
  y <- cbind(ses = c(10, 20, 30, 40), health = c(1, 0, 1, 0))
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 3, minprob = 0)

  expect_null(best_numeric_split(x, y, wt, 1, ctrl, ci_factory("CI")))
})

test_that("best_numeric_split chooses the cutpoint with the largest gain", {
  x <- c(4, 1, 3, 2)
  y <- cbind(
    ses = c(40, 10, 30, 20),
    health = c(10, 1, 3, 2)
  )
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 7, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 7L)
  expect_equal(split$breaks, 3.5)
  expect_equal(split$index, 1:2)
})

test_that("best_numeric_split respects minprob when selecting splits", {
  x <- c(1, 2, 3, 4, 5)
  y <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 5, 10, 20, 40)
  )
  wt <- rep(1, 5)
  ctrl <- list(minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_numeric_split(x, y, wt,
    varid = 1, ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$breaks, 3.5)
})

test_that("best_numeric_split can return a reusable split candidate", {
  x <- c(4, 1, 3, 2)
  y <- cbind(
    ses = c(40, 10, 30, 20),
    health = c(10, 1, 3, 2)
  )
  wt <- rep(1, 4)
  ctrl <- list(minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  candidate <- best_numeric_split(
    x = x,
    y = y,
    wt = wt,
    varid = 7,
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    return = "candidate"
  )

  expect_type(candidate$gain, "double")
  expect_s3_class(candidate$partysplit, "partysplit")
  expect_equal(candidate$left, c(FALSE, TRUE, TRUE, TRUE))
})

test_that("best_numeric_split rejects non-finite weights", {
  x <- c(1, 2, 3)
  y <- cbind(ses = c(10, 20, 30), health = c(1, 0, 1))
  ctrl <- list(minbucket = 1, minprob = 0)

  for (bad_weights in list(c(1, Inf, 1), c(1, NaN, 1), c(1, -Inf, 1))) {
    expect_error(
      best_numeric_split(x, y, bad_weights, 1, ctrl, ci_factory("CI")),
      "finite"
    )
  }
})

test_that(
  "best_factor_split returns NULL when fewer than two levels are present",
  {
    x_full <- factor(c("low", "low", "mid"), levels = c("low", "mid", "high"))
    keep <- c(TRUE, TRUE, FALSE)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 1, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that(
  "best_factor_split returns NULL when no admissible candidate split exists",
  {
    x_full <- factor(c("low", "mid", "high"), levels = c("low", "mid", "high"))
    keep <- rep(TRUE, 3)
    y_full <- cbind(ses = c(10, 20, 30), health = c(1, 2, 3))
    wt_full <- rep(1, 3)
    ctrl <- list(minbucket = 2, minprob = 0)

    expect_null(best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI")
    ))
  }
)

test_that("best_factor_split chooses the best cumulative level split", {
  x_full <- factor(
    c("high", "low", "mid"),
    levels = c("low", "mid", "high", "unused")
  )
  keep <- rep(TRUE, 3)
  y_full <- cbind(
    ses = c(30, 10, 20),
    health = c(10, 1, 2)
  )
  wt_full <- rep(1, 3)
  ctrl <- ci_tree_control(factor_split = "order", minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 4,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_s3_class(split, "partysplit")
  expect_equal(split$varid, 4L)
  expect_equal(split$index, c(1L, 1L, 2L, NA_integer_))
})

test_that("best_factor_split respects minprob when scoring candidates", {
  x_full <- factor(
    c("low", "mid", "mid", "high", "high"),
    levels = c("low", "mid", "high")
  )
  keep <- rep(TRUE, 5)
  y_full <- cbind(
    ses = c(10, 20, 30, 40, 50),
    health = c(1, 2, 2, 10, 10)
  )
  wt_full <- rep(1, 5)
  ctrl <- ci_tree_control(factor_split = "order", minbucket = 1, minprob = 0.4)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 1,
    ctrl = ctrl,
    ci_fun = mock_ci_fun
  )

  expect_equal(split$index, c(1L, 1L, 2L))
})

test_that("best_factor_split can return a reusable split candidate", {
  x_full <- factor(
    c("high", "low", "mid"),
    levels = c("low", "mid", "high", "unused")
  )
  keep <- rep(TRUE, 3)
  y_full <- cbind(
    ses = c(30, 10, 20),
    health = c(10, 1, 2)
  )
  wt_full <- rep(1, 3)
  ctrl <- ci_tree_control(factor_split = "order", minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  candidate <- best_factor_split(
    x_full = x_full,
    keep = keep,
    y_full = y_full,
    wt_full = wt_full,
    varid = 4,
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    return = "candidate"
  )

  expect_type(candidate$gain, "double")
  expect_s3_class(candidate$partysplit, "partysplit")
  expect_equal(candidate$left, c(FALSE, TRUE, TRUE))
})

test_that("best_factor_split exact partition can beat ordered search", {
  x_full <- factor(rep(letters[1:4], each = 4), levels = letters[1:4])
  keep <- rep(TRUE, 16)
  y_full <- cbind(
    rank = c(
      0.208, 0.307, 0.331, 0.199, 0.236, 0.275, 0.591, 0.253,
      0.123, 0.230, 0.598, 0.211, 0.464, 0.647, 0.961, 0.676
    ),
    outcome = c(
      2.281, 1.853, 2.333, 2.283, 1.301, 3.502, 2.120, 1.706,
      2.906, 4.838, 3.343, 3.161, 4.298, 3.896, 4.187, 0.548
    )
  )
  wt_full <- c(
    1.649, 1.998, 2.799, 2.957, 0.595, 1.945, 2.333, 1.122,
    1.252, 2.334, 2.767, 1.025, 1.395, 1.621, 2.766, 1.474
  )
  ci <- ci_factory("CI")
  ctrl_order <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    factor_split = "order"
  )
  ctrl_partition <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    factor_split = "partition",
    max_factor_partitions = 1e6
  )

  ordered <- best_factor_split(
    x_full, keep, y_full, wt_full, 1, ctrl_order, ci,
    return = "candidate"
  )
  partition <- best_factor_split(
    x_full, keep, y_full, wt_full, 1, ctrl_partition, ci,
    return = "candidate"
  )

  expect_equal(partition$factor_split, "partition")
  expect_gt(partition$gain, ordered$gain)
  expect_equal(partition$left_levels, c("a", "b", "c"))
})

test_that("best_factor_split auto falls back when partition search is too large", {
  x_full <- factor(rep(letters[1:4], each = 2), levels = letters[1:4])
  keep <- rep(TRUE, 8)
  y_full <- cbind(
    rank = seq_len(8),
    outcome = c(1, 2, 4, 3, 7, 6, 8, 5)
  )
  wt_full <- rep(1, 8)
  ctrl <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    factor_split = "auto",
    max_factor_partitions = 1
  )

  candidate <- best_factor_split(
    x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI"),
    return = "candidate"
  )

  expect_equal(candidate$factor_split, "order")
})

test_that("best_factor_split explicit partition errors when search is too large", {
  x_full <- factor(rep(letters[1:4], each = 2), levels = letters[1:4])
  keep <- rep(TRUE, 8)
  y_full <- cbind(
    rank = seq_len(8),
    outcome = c(1, 2, 4, 3, 7, 6, 8, 5)
  )
  wt_full <- rep(1, 8)
  ctrl <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    factor_split = "partition",
    max_factor_partitions = 1
  )

  expect_error(
    best_factor_split(
      x_full, keep, y_full, wt_full, 1, ctrl, ci_factory("CI"),
      return = "candidate"
    ),
    "Exact factor partition search"
  )
})

test_that("best_factor_split rejects non-finite weights", {
  x_full <- factor(c("a", "b", "c"), levels = c("a", "b", "c"))
  keep <- rep(TRUE, 3)
  y_full <- cbind(rank = c(10, 20, 30), outcome = c(1, 0, 1))
  ctrl <- ci_tree_control(minsplit = 1, minbucket = 1, minprob = 0)

  for (bad_weights in list(c(1, Inf, 1), c(1, NaN, 1), c(1, -Inf, 1))) {
    expect_error(
      best_factor_split(x_full, keep, y_full, bad_weights, 1, ctrl, ci_factory("CI")),
      "finite"
    )
  }
})

test_that("best_global_ci_split searches variables globally by CI gain", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50),
    outcome = c(1, 5, 10, 20, 40),
    weak = c(1, 1, 1, 1, 1),
    strong = c(1, 2, 3, 4, 5)
  )
  ctrl <- ci_tree_control(minsplit = 1, minbucket = 1, minprob = 0)
  mock_ci_fun <- function(y, wt) sum(y[, 2] * wt)^2

  split <- best_global_ci_split(
    x = toy_data,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    ctrl = ctrl,
    ci_fun = mock_ci_fun,
    vars = 3:4
  )

  expect_equal(split$varid, 4L)
  expect_s3_class(split$partysplit, "partysplit")
})

test_that("best_global_ci_split respects min_gain", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 2, 3, 4),
    x = c(1, 2, 3, 4)
  )
  ctrl <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    min_gain = Inf
  )

  split <- best_global_ci_split(
    x = toy_data,
    y = as.matrix(toy_data[c("rank", "outcome")]),
    wt = rep(1, nrow(toy_data)),
    ctrl = ctrl,
    ci_fun = ci_factory("CI"),
    vars = 3
  )

  expect_null(split)
})

test_that("best_global_ci_split respects min_relative_gain", {
  toy_data <- data.frame(
    rank = c(20, 10, 40, 30, 70, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 0, 1),
    x = c(1, 2, 3, 4, 5, 6, 7)
  )
  y <- as.matrix(toy_data[c("rank", "outcome")])
  wt <- c(1, 3, 2, 4, 1, 2, 5)
  ci_fun <- ci_factory("CIg")

  ctrl <- ci_tree_control(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    min_relative_gain = 0
  )

  split <- best_global_ci_split(
    x = toy_data,
    y = y,
    wt = wt,
    ctrl = ctrl,
    ci_fun = ci_fun,
    vars = 3
  )

  expect_true(is.finite(split$relative_gain))
  expect_equal(split$parent_impurity, ci_fun(y, wt))
  expect_equal(split$relative_gain, split$gain / abs(split$parent_impurity))

  ctrl$min_relative_gain <- split$relative_gain + 1e-8
  expect_null(best_global_ci_split(
    x = toy_data,
    y = y,
    wt = wt,
    ctrl = ctrl,
    ci_fun = ci_fun,
    vars = 3
  ))
})

test_that("best_global_ci_split rejects non-finite weights", {
  predictors <- data.frame(x = c(1, 2, 3))
  y <- cbind(rank = c(10, 20, 30), outcome = c(1, 0, 1))
  ctrl <- ci_tree_control(minsplit = 1, minbucket = 1, minprob = 0)

  for (bad_weights in list(c(1, Inf, 1), c(1, NaN, 1), c(1, -Inf, 1))) {
    expect_error(
      best_global_ci_split(
        x = predictors,
        y = y,
        wt = bad_weights,
        ctrl = ctrl,
        ci_fun = ci_factory("CI")
      ),
      "finite"
    )
  }
})
