# WARNING - Generated by {fusen} from dev/plot_tree_helpers.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("tree_compact_split_label keeps short labels readable", {
  expect_equal(
    tree_compact_split_label("wealth_index", "lowest"),
    "wealth index\nlowest"
  )
})

test_that("tree_compact_split_label summarizes long level lists", {
  expect_equal(
    tree_compact_split_label(
      "water_source",
      "piped, borehole, well, river",
      var_labels = c(water_source = "Water source"),
      plural_overrides = c("Water source" = "sources")
    ),
    "Water source\n4 sources\npiped, borehole, well, ..."
  )
})

test_that("tree_edge_panel_compact is a graph-content generator", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(tree_edge_panel_compact, "grapcon_generator")
  expect_true(is.function(tree_edge_panel_compact(fit)))
})

test_that("tree_inner_panel_labeled is a graph-content generator", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_s3_class(tree_inner_panel_labeled, "grapcon_generator")
  expect_true(is.function(tree_inner_panel_labeled(fit)))
})

test_that("tree_build_terminal_stats computes one row per terminal node", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  stats_df <- tree_build_terminal_stats(
    fit,
    toy_data,
    stat_funs = list(
      n = nrow,
      mean_outcome = function(df) mean(df$outcome)
    )
  )

  node_ids <- sort(unique(stats::predict(
    fit,
    newdata = toy_data,
    type = "node"
  )))

  expect_equal(names(stats_df), c("node_id", "n", "mean_outcome"))
  expect_equal(stats_df$node_id, node_ids)
  expect_equal(nrow(stats_df), length(node_ids))
  expect_equal(sum(stats_df$n), nrow(toy_data))
})

test_that(
  paste(
    "tree_build_terminal_stats rejects summaries returning",
    "multiple values"
  ),
  {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40),
    outcome = c(1, 0, 1, 0),
    income = c(2, 4, 6, 8)
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  expect_error(
    tree_build_terminal_stats(
      fit,
      toy_data,
      stat_funs = list(bad = function(df) c(1, 2))
    ),
    "single value"
  )
})

test_that("tree_terminal_panel_stats is a graph-content generator", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  stats_df <- tree_build_terminal_stats(
    fit,
    toy_data,
    stat_funs = list(
      n = nrow,
      mean_outcome = function(df) mean(df$outcome)
    )
  )

  expect_s3_class(tree_terminal_panel_stats, "grapcon_generator")
  expect_true(is.function(tree_terminal_panel_stats(fit, stats_df)))
})

test_that("plot dispatches for ci_tree without error", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12),
    group = factor(c("low", "low", "mid", "mid", "high", "high"))
  )

  fit <- ctree_ci(
    formula = cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  pdf_file <- tempfile(fileext = ".pdf")
  grDevices::pdf(pdf_file)
  on.exit(grDevices::dev.off(), add = TRUE)

  expect_invisible(plot(fit))
  expect_invisible(
    plot(
      fit,
      data = toy_data,
      terminal_stats = list(
        n = nrow,
        mean_outcome = function(df) mean(df$outcome)
      )
    )
  )
})
