# WARNING - Generated by {fusen} from dev/model_selection.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ci_tree_control_grid creates greedy controls only", {
  grid <- ci_tree_control_grid(
    minsplit = c(4, 6),
    minbucket = 2,
    minprob = c(0, 0.1),
    maxdepth = 1:2,
    min_gain = c(0, 0.01),
    mtry = c(1, 2),
    ntree = c(5, 10)
  )

  expect_s3_class(grid, "data.table")
  expect_equal(nrow(grid), 64L)
  expect_true(all(c(
    "minsplit", "minbucket", "minprob", "maxdepth", "min_gain", "mtry",
    "ntree"
  ) %in% names(grid)))
  expect_false("mincriterion" %in% names(grid))
})

test_that("ci_cv_folds creates reproducible folds", {
  folds_a <- ci_cv_folds(12, v = 3, seed = 99)
  folds_b <- ci_cv_folds(12, v = 3, seed = 99)

  expect_equal(folds_a, folds_b)
  expect_equal(sort(unique(folds_a)), 1:3)
  expect_equal(length(folds_a), 12L)
})

test_that("ci_cv_folds validates input", {
  expect_error(ci_cv_folds(3, v = 4), "`v` cannot exceed `n`")
  expect_error(ci_cv_folds(5, strata = 1:4), "`strata` must have length `n`")
})

test_that("predict_ctree_ci_terminal_mean returns one prediction per row", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ctree_ci(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  pred <- predict_ctree_ci_terminal_mean(fit, toy_data, outcome_name = "outcome")

  expect_type(pred, "double")
  expect_equal(length(pred), nrow(toy_data))
  expect_true(all(pred >= 0 & pred <= 1))
})

test_that("ci_tree_validation_gain scores a fitted partition", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60),
    outcome = c(1, 0, 1, 0, 1, 1),
    income = c(2, 4, 6, 8, 10, 12)
  )
  fit <- ctree_ci(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
  )

  score <- ci_tree_validation_gain(fit, toy_data, "rank", "outcome")

  expect_type(score, "double")
  expect_length(score, 1L)
  expect_true(is.finite(score))
})

test_that("ci prediction metrics score simple binary predictions", {
  truth <- c(0, 1, 1, 0)
  estimate <- c(0.1, 0.8, 0.7, 0.2)

  expect_lt(ci_brier_score(truth, estimate), 0.1)
  expect_lt(ci_log_loss(truth, estimate), 0.4)
  expect_equal(ci_roc_auc(truth, estimate), 1)

  out <- ci_prediction_metrics(truth, estimate)
  expect_s3_class(out, "data.table")
  expect_true(all(c("brier", "log_loss", "roc_auc") %in% names(out)))
})

test_that("tune_ctree_ci selects greedy tree controls and CI type", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b"))
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1:2
  )

  tuned <- tune_ctree_ci(
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = c("CI", "CIg"),
    control_grid = grid,
    v = 2,
    seed = 1,
    refit = TRUE
  )

  expect_s3_class(tuned, "ci_tree_tuning")
  expect_s3_class(tuned$fold_results, "data.table")
  expect_s3_class(tuned$summary, "data.table")
  expect_equal(nrow(tuned$fold_results), nrow(grid) * 2L * 2L)
  expect_s3_class(tuned$best_fit, "ci_tree")
  expect_true(tuned$best_type %in% c("CI", "CIg"))
  expect_true("type" %in% names(tuned$best_params))
  expect_false("mincriterion" %in% names(tuned$best_params))
})

test_that("tune_ctree_ci can minimize Brier score", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16)
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1
  )

  tuned <- tune_ctree_ci(
    cbind(rank, outcome) ~ income,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = "CI",
    control_grid = grid,
    v = 2,
    seed = 2,
    metric = "brier",
    refit = FALSE
  )

  expect_equal(tuned$metric_direction, "minimize")
  expect_null(tuned$best_fit)
  expect_true(is.finite(tuned$summary$mean_score[1]))
})

test_that("tune_cf_ci tunes greedy forests and returns a surrogate", {
  toy_data <- data.frame(
    rank = c(10, 20, 30, 40, 50, 60, 70, 80),
    outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
    income = c(2, 4, 6, 8, 10, 12, 14, 16),
    group = factor(c("a", "a", "b", "b", "a", "a", "b", "b"))
  )
  grid <- ci_tree_control_grid(
    minsplit = 1,
    minbucket = 1,
    minprob = 0,
    maxdepth = 1:2,
    mtry = 1:2,
    ntree = c(3L, 5L)
  )

  tuned <- tune_cf_ci(
    cbind(rank, outcome) ~ income + group,
    data = toy_data,
    rank_name = "rank",
    outcome_name = "outcome",
    type = c("CI", "CIg"),
    control_grid = grid,
    v = 2,
    seed = 3,
    refit = TRUE
  )

  expect_s3_class(tuned, "ci_forest_tuning")
  expect_equal(tuned$model, "forest")
  expect_s3_class(tuned$best_fit, "ci_forest")
  expect_s3_class(tuned$best_surrogate, "ci_tree")
  expect_equal(nrow(tuned$fold_results), nrow(grid) * 2L * 2L)
  expect_true("ntree" %in% names(tuned$best_params))
  expect_true("type" %in% names(tuned$best_params))
  expect_true("forest_risk" %in% names(tuned$best_surrogate_data))
  expect_true(tuned$best_type %in% c("CI", "CIg"))
  expect_true(is.finite(tuned$summary$mean_score[1]))
})
