// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ci_best_numeric_split_cpp_engine
List ci_best_numeric_split_cpp_engine(NumericVector x, NumericMatrix y, NumericVector wt, double minbucket, double minprob, std::string type);
RcppExport SEXP _ineqTrees_ci_best_numeric_split_cpp_engine(SEXP xSEXP, SEXP ySEXP, SEXP wtSEXP, SEXP minbucketSEXP, SEXP minprobSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type minbucket(minbucketSEXP);
    Rcpp::traits::input_parameter< double >::type minprob(minprobSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(ci_best_numeric_split_cpp_engine(x, y, wt, minbucket, minprob, type));
    return rcpp_result_gen;
END_RCPP
}
// ci_best_factor_split_cpp_engine
List ci_best_factor_split_cpp_engine(IntegerVector code, NumericMatrix y, NumericVector wt, int n_levels, double minbucket, double minprob, std::string type);
RcppExport SEXP _ineqTrees_ci_best_factor_split_cpp_engine(SEXP codeSEXP, SEXP ySEXP, SEXP wtSEXP, SEXP n_levelsSEXP, SEXP minbucketSEXP, SEXP minprobSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type code(codeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type n_levels(n_levelsSEXP);
    Rcpp::traits::input_parameter< double >::type minbucket(minbucketSEXP);
    Rcpp::traits::input_parameter< double >::type minprob(minprobSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(ci_best_factor_split_cpp_engine(code, y, wt, n_levels, minbucket, minprob, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ineqTrees_ci_best_numeric_split_cpp_engine", (DL_FUNC) &_ineqTrees_ci_best_numeric_split_cpp_engine, 6},
    {"_ineqTrees_ci_best_factor_split_cpp_engine", (DL_FUNC) &_ineqTrees_ci_best_factor_split_cpp_engine, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ineqTrees(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
