# WARNING - Generated by {fusen} from dev/shap_decomposition.Rmd: do not edit by hand # nolint: line_length_linter.

#' Assert that the data.table package is available
#' @return Invisibly returns `NULL` if the check passes. Otherwise, throws an
#'   error.
#' @details This function is used internally to ensure that the `data.table`
#'   package is available before attempting to use it. If `data.table` is not
#'   installed, an informative error message is thrown instructing the user to
#'   install the package.
#' @export
.assert_data_table_available <- function() {
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop(
      paste(
        "Package `data.table` is required.",
        "Install it with install.packages(\"data.table\")."
      ),
      call. = FALSE
    )
  }
}

#' Assert that an input is a single logical value
#' @param x The input to check.
#' @param arg The name of the argument being checked, used in error messages.
#' @return Invisibly returns `NULL` if the check passes. Otherwise, throws an
#'   error.
#' @details This function is used internally to validate that certain inputs
#'   are single logical values (flags). It checks that `x` is of type
#'   logical, has length 1, and is not NA. If any of these conditions fail,
#'   an informative error message is thrown indicating the argument name and
#'   the nature of the issue.
#' @export
.assert_scalar_flag <- function(x, arg) {
  if (!is.logical(x) || length(x) != 1L || is.na(x)) {
    stop(sprintf("`%s` must be TRUE or FALSE.", arg), call. = FALSE)
  }
}

#' Assert that an input is a single finite numeric value
#' @param x The input to check.
#' @param arg The name of the argument being checked, used in error messages.
#' @return Invisibly returns `NULL` if the check passes. Otherwise, throws an
#'   error.
#' @details This function is used internally to validate that certain inputs
#'   are single numeric values that are not NA or infinite. It checks that
#'   `x` is numeric, has length 1, and is not NA or infinite. If any of these
#'   conditions fail, an informative error message is thrown indicating the
#'   argument name and the nature of the issue.
#' @export
.assert_scalar_numeric <- function(x, arg) {
  if (!is.numeric(x) || length(x) != 1L || is.na(x) || !is.finite(x)) {
    stop(
      sprintf("`%s` must be a single finite numeric value.", arg),
      call. = FALSE
    )
  }
}

#' Reshape a DALEX-like long SHAP table to wide format
#'
#' Convert a long-format SHAP table with observation IDs, feature names, and
#' SHAP values to a wide format with one row per observation and one column per
#' feature. Baseline rows can be optionally dropped based on common baseline
#' labels.
#'
#' @param shap A long-format SHAP table containing observation IDs, feature
#'   names, and SHAP values.
#' @param id_col Optional column name identifying observations. If `NULL`,
#'   common ID column names will be searched for.
#' @param variable_col Optional column name containing feature names. If
#'   `NULL`, common variable column names will be searched for.
#' @param value_col Optional column name containing SHAP values. If
#'   `NULL`, common value column names will be searched for.
#' @param drop_baseline Logical scalar. If `TRUE`, rows with feature names
#'   matching common baseline labels will be dropped before reshaping.
#' @param baseline_labels Character vector of feature names to treat as
#'   baseline rows when `drop_baseline = TRUE`. Matching is case-sensitive.
#' @return A wide-format `data.table` with one row per observation and one
#'   numeric column per SHAP feature.
#' @details The function attempts to identify the ID, variable, and value
#'   columns based on common naming conventions. If `drop_baseline = TRUE`,
#'   rows with feature names in `baseline_labels` are removed before
#'   reshaping. The resulting wide table contains only numeric SHAP feature
#'   columns. Aliases for the identified columns are as follows:
#' - ID column candidates: `"_id_"`, `"id"`, `"row_id"`,
#'   `"observation_id"`, `"observation"`, `"case_id"`
#' - Variable column candidates: `"_vname_"`, `"variable"`,
#'   `"variable_name"`, `"feature"`
#' - Value column candidates: `"_attribution_"`, `"contribution"`,
#'   `"phi"`, `"shap"`, `"value"`
#' @export
.dalex_shap_to_wide <- function(
    shap,
    id_col = NULL,
    variable_col = NULL,
    value_col = NULL,
    drop_baseline = TRUE,
    baseline_labels = c("_baseline_", "baseline", "intercept")) {
  shap_dt <- data.table::copy(data.table::as.data.table(shap))

  if (nrow(shap_dt) == 0L) {
    stop("`shap` must contain at least one row.", call. = FALSE)
  }

  nms <- names(shap_dt)

  if (is.null(id_col)) {
    id_candidates <- c(
      "_id_", "id", "row_id", "observation_id", "observation", "case_id"
    )
    id_col <- intersect(id_candidates, nms)[1]
  }
  if (is.null(variable_col)) {
    variable_candidates <- c("_vname_", "variable", "variable_name", "feature")
    variable_col <- intersect(variable_candidates, nms)[1]
  }
  if (is.null(value_col)) {
    value_candidates <- c(
      "_attribution_", "contribution", "phi", "shap", "value"
    )
    value_col <- intersect(value_candidates, nms)[1]
  }

  if (is.na(variable_col) || is.null(variable_col)) {
    stop(
      paste(
        "Could not identify the DALEX feature-name column.",
        "Supply `variable_col`."
      ),
      call. = FALSE
    )
  }
  if (is.na(value_col) || is.null(value_col)) {
    stop(
      "Could not identify the DALEX SHAP-value column. Supply `value_col`.",
      call. = FALSE
    )
  }

  if (is.na(id_col) || is.null(id_col)) {
    shap_dt[[".observation_id__"]] <- 1L
    id_col <- ".observation_id__"
  }

  shap_dt[[variable_col]] <- as.character(shap_dt[[variable_col]])
  shap_dt[[value_col]] <- as.numeric(shap_dt[[value_col]])

  if (isTRUE(drop_baseline)) {
    shap_dt <- shap_dt[!(shap_dt[[variable_col]] %in% baseline_labels), ]
  }

  if (nrow(shap_dt) == 0L) {
    stop(
      "No feature-level SHAP rows remain after dropping baseline rows.",
      call. = FALSE
    )
  }

  quote_name <- function(x) {
    paste0("`", gsub("`", "\\\\`", x), "`")
  }

  wide_dt <- data.table::dcast(
    shap_dt,
    stats::as.formula(paste(quote_name(id_col), "~", quote_name(variable_col))),
    value.var = value_col
  )

  data.table::setorderv(wide_dt, id_col)
  wide_dt[[id_col]] <- NULL
  wide_dt
}

#' Prepare a SHAP table with named numeric columns
#' Ensure that the input SHAP table is a data.table with named numeric columns.
#' If the input is coercible to a data.table but has no column names,
#' assign default names
#' like "feature_1", "feature_2", etc. Validate that all columns are numeric and
#' optionally check for missing values.
#' @param shap A SHAP table to prepare.
#' @param allow_missing Logical scalar. If `TRUE`, allow missing values in
#'   SHAP columns. If `FALSE`, trigger an error if any SHAP column contains
#'   missing values.
#' @return A data.table with named numeric columns representing SHAP features.
#' @details This function is used internally to standardize SHAP tables
#'   before decomposition. It ensures that the SHAP data is in a consistent
#'   format with appropriate column names and types.
#' @export
.prepare_named_shap_dt <- function(shap, allow_missing = FALSE) {
  shap_dt <- tryCatch(
    data.table::copy(data.table::as.data.table(shap)),
    error = function(e) NULL
  )

  if (is.null(shap_dt)) {
    stop("`shap` must be coercible to a rectangular table.", call. = FALSE)
  }

  if (is.null(names(shap_dt))) {
    data.table::setnames(shap_dt, paste0("feature_", seq_len(ncol(shap_dt))))
  } else {
    data.table::setnames(
      shap_dt,
      make.unique(ifelse(names(shap_dt) == "", "feature", names(shap_dt)))
    )
  }

  .validate_shap_table(shap_dt, allow_missing = allow_missing)
}

#' Validate a SHAP table
#' Ensure that the input SHAP table is a data.table with at least one row and
#' one numeric column. Optionally check for missing values and trigger an error
#' any are found.
#' @param shap_dt A data.table representing SHAP values to validate.
#' @param allow_missing Logical scalar. If `TRUE`, allow missing values in
#'   SHAP columns. If `FALSE`, trigger an error if any SHAP column contains
#'   missing values.
#' @return The input `shap_dt` if it passes validation checks.
#' @details This function is used internally to ensure that SHAP tables are in
#'   a consistent format with appropriate types before decomposition. It checks
#'   that the input is a data.table (or coercible to one), contains at least
#'   one row and one column, that all columns are numeric, and optionally that
#'   there are no missing values.
#' @export
.validate_shap_table <- function(shap_dt, allow_missing = FALSE) {
  if (!data.table::is.data.table(shap_dt)) {
    shap_dt <- tryCatch(
      data.table::as.data.table(shap_dt),
      error = function(e) NULL
    )
    if (is.null(shap_dt) || !data.table::is.data.table(shap_dt)) {
      stop("`shap_dt` must be a data.table or coercible to one.", call. = FALSE)
    }
  }

  if (nrow(shap_dt) == 0L) {
    stop("`shap_dt` must contain at least one row.", call. = FALSE)
  }
  if (ncol(shap_dt) == 0L) {
    stop(
      "`shap_dt` must contain at least one SHAP feature column.",
      call. = FALSE
    )
  }

  is_numeric_col <- vapply(shap_dt, is.numeric, logical(1L))
  if (!all(is_numeric_col)) {
    bad_cols <- names(shap_dt)[!is_numeric_col]
    stop(
      sprintf(
        "All SHAP columns must be numeric. Non-numeric columns: %s",
        paste(bad_cols, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  has_missing <- vapply(shap_dt, anyNA, logical(1L))
  if (!allow_missing && any(has_missing)) {
    bad_cols <- names(shap_dt)[has_missing]
    stop(
      sprintf(
        "SHAP columns must not contain missing values. Columns with NA: %s",
        paste(bad_cols, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  shap_dt
}
