# WARNING - Generated by {fusen} from dev/ci_split_search.Rmd: do not edit by hand # nolint: line_length_linter.

#' Find the best factor split by concentration-index gain
#'
#' Evaluate cumulative binary splits of a factor predictor after ordering the
#' observed levels by weighted mean outcome, and return the split with the
#' largest weighted concentration-index gain.
#'
#' Only levels present among the kept observations are scored, but the returned
#' split keeps the full level mapping so it can be used with
#' [partykit::partysplit()].
#'
#' @param x_full A factor predictor containing all original levels.
#' @param keep A logical vector selecting the observations currently available
#'   for splitting.
#' @param y_full A two-column numeric matrix whose first column is the
#'   socioeconomic ranking variable and whose second column is the health
#'   outcome.
#' @param wt_full A numeric vector of case weights for all observations.
#' @param varid Integer identifier of the splitting variable, passed to
#'   [partykit::partysplit()].
#' @param ctrl A list-like control object containing `minbucket` and `minprob`.
#' @param ci_fun A concentration-index scoring function, typically created by
#'   [ci_factory()].
#' @param return Either `"split"` to return only a [partykit::partysplit()]
#'   object, or `"candidate"` to also return the gain and left-child routing
#'   needed by the greedy tree builder.
#'
#' @return A `partysplit` object describing the best admissible split of the
#'   observed factor levels, or `NULL` if fewer than two levels are present
#'   after subsetting or if all candidate splits violate the control
#'   constraints.
#' @export
#' @examples
#' x_full <- factor(
#'   c("low", "mid", "high", "low", "mid", "high"),
#'   levels = c("low", "mid", "high", "unused")
#' )
#' keep <- rep(TRUE, 6)
#' y_full <- cbind(
#'   ses = c(10, 20, 30, 40, 50, 60),
#'   health = c(1, 2, 5, 1, 2, 5)
#' )
#' wt_full <- rep(1, 6)
#' ctrl <- list(minbucket = 1, minprob = 0)
#'
#' split <- best_factor_split(
#'   x_full = x_full,
#'   keep = keep,
#'   y_full = y_full,
#'   wt_full = wt_full,
#'   varid = 1,
#'   ctrl = ctrl,
#'   ci_fun = ci_factory("CI")
#' )
#' split$index
best_factor_split <- function(
    x_full, keep, y_full, wt_full, varid, ctrl, ci_fun,
    return = c("split", "candidate")) {
  return <- match.arg(return)
  # keep full level mapping for partysplit()
  full_levels <- levels(x_full)
  x <- x_full[keep]
  y <- y_full[keep, , drop = FALSE]
  wt <- wt_full[keep]

  present_levels <- full_levels[full_levels %in% unique(as.character(x))]
  if (length(present_levels) <= 1L) return(NULL)

  ci_parent <- ci_fun(y, wt)

  # order factor levels by weighted mean outcome, then search cumulative
  # binary splits
  level_score <- sapply(
    present_levels,
    function(lv) {
      idx <- as.character(x) == lv
      stats::weighted.mean(y[idx, 2], wt[idx])
    }
  )

  ord_levels <- present_levels[order(level_score)]
  level_weight <- sapply(
    ord_levels,
    function(lv) {
      sum(wt[as.character(x) == lv], na.rm = TRUE)
    }
  )
  cum_level_weight <- cumsum(level_weight)
  total_weight <- cum_level_weight[length(cum_level_weight)]
  gains <- rep(-Inf, length(ord_levels) - 1L)

  for (k in seq_len(length(ord_levels) - 1L)) {
    wl <- cum_level_weight[k]
    wr <- total_weight - wl

    if (wl < ctrl$minbucket || wr < ctrl$minbucket) next
    if ((wl / total_weight) < ctrl$minprob ||
        (wr / total_weight) < ctrl$minprob) {
      next
    }

    left_levels <- ord_levels[seq_len(k)]
    left <- as.character(x) %in% left_levels
    gains[k] <- .weighted_ci_gain_from_parent(
      y = y,
      wt = wt,
      left = left,
      ci_fun = ci_fun,
      ci_parent = ci_parent
    )
  }

  if (!any(is.finite(gains))) return(NULL)

  best_k <- which.max(gains)
  left_levels <- ord_levels[seq_len(best_k)]
  right_levels <- ord_levels[-seq_len(best_k)]
  left <- as.character(x) %in% left_levels

  index <- rep(NA_integer_, length(full_levels))
  index[match(left_levels,  full_levels)] <- 1L
  index[match(right_levels, full_levels)] <- 2L

  sp <- partykit::partysplit(
    varid = as.integer(varid),
    index = index
  )

  if (identical(return, "split")) {
    return(sp)
  }

  list(
    gain = gains[best_k],
    varid = as.integer(varid),
    partysplit = sp,
    split = sp,
    left = left,
    type = "factor",
    left_levels = left_levels,
    right_levels = right_levels
  )
}


#' Find the globally best greedy concentration-index split
#'
#' Search across all supplied variables and their admissible split points, then
#' return the variable-split pair with the largest concentration-index gain.
#'
#' @param x A data frame or list of predictors.
#' @param y A two-column numeric response matrix.
#' @param wt Case weights.
#' @param ctrl A control list created by [ci_tree_control()] or compatible.
#' @param ci_fun Concentration-index scoring function.
#' @param vars Optional integer variable ids to search. Defaults to all columns
#'   of `x`.
#'
#' @return A split candidate list, or `NULL` when no variable has an admissible
#'   gain above `control$min_gain`.
#'
#' @export
best_global_ci_split <- function(x,
                                 y,
                                 wt,
                                 ctrl,
                                 ci_fun,
                                 vars = seq_along(x)) {
  stopifnot(is.matrix(y), nrow(y) == length(wt))
  ctrl <- .ci_tree_normalize_control(ctrl)

  vars <- as.integer(vars)
  vars <- vars[vars %in% seq_along(x)]

  if (!length(vars)) {
    return(NULL)
  }

  if (!is.null(ctrl$mtry)) {
    vars <- sample(vars, min(ctrl$mtry, length(vars)))
  }

  best <- NULL

  for (j in vars) {
    candidate <- best_split_for_one_variable(
      x = x[[j]],
      y = y,
      wt = wt,
      varid = j,
      ctrl = ctrl,
      ci_fun = ci_fun
    )

    if (!is.null(candidate) &&
        (is.null(best) || candidate$gain > best$gain)) {
      best <- candidate
    }
  }

  if (is.null(best) ||
      !is.finite(best$gain) ||
      best$gain <= ctrl$min_gain) {
    return(NULL)
  }

  best
}

#' Find the best numeric split by concentration-index gain
#'
#' Evaluate all admissible cutpoints of a numeric predictor and return the
#' split with the largest weighted concentration-index gain.
#'
#' Candidate cutpoints are formed at midpoints between distinct sorted values of
#' `x`. Each candidate is filtered using `ctrl$minbucket` and `ctrl$minprob`
#' before being scored with [weighted_ci_gain()].
#'
#' @param x A numeric predictor vector.
#' @param y A two-column numeric matrix whose first column is the socioeconomic
#'   ranking variable and whose second column is the health outcome.
#' @param wt A numeric vector of case weights with the same length as `x`.
#' @param varid Integer identifier of the splitting variable, passed to
#'   [partykit::partysplit()].
#' @param ctrl A list-like control object containing `minbucket` and `minprob`.
#' @param ci_fun A concentration-index scoring function, typically created by
#'   [ci_factory()].
#' @param return Either `"split"` to return only a [partykit::partysplit()]
#'   object, or `"candidate"` to also return the gain and left-child routing
#'   needed by the greedy tree builder.
#'
#' @return A `partysplit` object describing the best admissible binary split, or
#'   `NULL` if no split is available because all `x` values are tied or all
#'   candidate splits violate the control constraints.
#'
#' @export
#' @examples
#' x <- c(2, 4, 6, 8, 10)
#' y <- cbind(
#'   ses = c(10, 20, 30, 40, 50),
#'   health = c(1, 0, 1, 0, 1)
#' )
#' wt <- rep(1, 5)
#' ctrl <- list(minbucket = 1, minprob = 0)
#'
#' split <- best_numeric_split(
#'   x = x,
#'   y = y,
#'   wt = wt,
#'   varid = 1,
#'   ctrl = ctrl,
#'   ci_fun = ci_factory("CI")
#' )
#' split$breaks
best_numeric_split <- function(
    x,
    y,
    wt,
    varid,
    ctrl,
    ci_fun,
    return = c("split", "candidate")) {
  return <- match.arg(return)
  ord <- order(x)
  x <- x[ord]
  y <- y[ord, , drop = FALSE]
  wt <- wt[ord]

  cut_pos <- which(diff(x) != 0)
  if (!length(cut_pos)) {
    return(NULL)
  }

  gains <- rep(-Inf, length(cut_pos))
  ci_parent <- ci_fun(y, wt)
  cum_wt <- cumsum(wt)
  total_wt <- cum_wt[length(cum_wt)]
  row_id <- seq_along(x)

  for (k in seq_along(cut_pos)) {
    pos <- cut_pos[k]
    wl <- cum_wt[pos]
    wr <- total_wt - wl

    if (wl < ctrl$minbucket || wr < ctrl$minbucket) next
    if ((wl / total_wt) < ctrl$minprob ||
        (wr / total_wt) < ctrl$minprob) {
      next
    }

    left <- row_id <= pos
    gains[k] <- .weighted_ci_gain_from_parent(
      y = y,
      wt = wt,
      left = left,
      ci_fun = ci_fun,
      ci_parent = ci_parent
    )
  }

  if (!any(is.finite(gains))) {
    return(NULL)
  }

  best_k <- cut_pos[which.max(gains)]
  cut <- (x[best_k] + x[best_k + 1L]) / 2
  left <- row_id <= best_k
  left_original <- logical(length(left))
  left_original[ord] <- left

  sp <- partykit::partysplit(
    varid = as.integer(varid),
    breaks = cut,
    index = 1:2
  )

  if (identical(return, "split")) {
    return(sp)
  }

  list(
    gain = gains[which.max(gains)],
    varid = as.integer(varid),
    partysplit = sp,
    split = sp,
    left = left_original,
    type = "numeric",
    cutpoint = cut
  )
}

#' Find the best CI split for one variable
#'
#' @param x A predictor vector.
#' @param y A two-column numeric response matrix.
#' @param wt Case weights.
#' @param varid Integer variable id used by [partykit::partysplit()].
#' @param ctrl A control list created by [ci_tree_control()] or compatible.
#' @param ci_fun Concentration-index scoring function.
#'
#' @return A split candidate list containing the gain, `partysplit`, and left
#'   child membership, or `NULL` when no admissible split exists.
#'
#' @export
best_split_for_one_variable <- function(x, y, wt, varid, ctrl, ci_fun) {
  stopifnot(length(x) == nrow(y), length(wt) == nrow(y))
  ctrl <- .ci_tree_normalize_control(ctrl)

  keep <- stats::complete.cases(y) & !is.na(x) & !is.na(wt) & wt > 0
  if (sum(wt[keep], na.rm = TRUE) < ctrl$minsplit) {
    return(NULL)
  }

  candidate <- NULL

  if (is.numeric(x) || is.integer(x)) {
    candidate <- best_numeric_split(
      x = x[keep],
      y = y[keep, , drop = FALSE],
      wt = wt[keep],
      varid = varid,
      ctrl = ctrl,
      ci_fun = ci_fun,
      return = "candidate"
    )
  } else if (is.factor(x) || is.ordered(x)) {
    candidate <- best_factor_split(
      x_full = x,
      keep = keep,
      y_full = y,
      wt_full = wt,
      varid = varid,
      ctrl = ctrl,
      ci_fun = ci_fun,
      return = "candidate"
    )
  }

  if (is.null(candidate)) {
    return(NULL)
  }

  left <- rep(FALSE, length(x))
  left[keep] <- candidate$left
  candidate$left <- left
  candidate
}
