# WARNING - Generated by {fusen} from dev/ci_tree_models.Rmd: do not edit by hand # nolint: line_length_linter.

#' Normalize controls for a greedy CI forest
#'
#' @noRd
.ci_forest_control <- function(control, mtry = NULL) {
  ctrl <- .ci_tree_normalize_control(control)

  if (!is.null(mtry)) {
    if (length(mtry) != 1L || is.na(mtry) || mtry <= 0) {
      stop("`mtry` must be `NULL` or a positive number.", call. = FALSE)
    }
    ctrl$mtry <- as.integer(ceiling(mtry))
  }

  ctrl
}

#' Draw row indices for one greedy CI forest tree
#'
#' @noRd
.ci_forest_sample <- function(n, perturb) {
  if (is.null(perturb)) {
    perturb <- list(replace = FALSE, fraction = 0.632)
  }

  replace <- isTRUE(perturb$replace)
  fraction <- perturb$fraction
  if (is.null(fraction)) {
    fraction <- if (replace) 1 else 0.632
  }

  if (length(fraction) != 1L ||
      is.na(fraction) ||
      !is.finite(fraction) ||
      fraction <= 0) {
    stop("`perturb$fraction` must be a positive finite number.",
      call. = FALSE
    )
  }

  size <- max(1L, as.integer(ceiling(n * fraction)))
  if (!replace) {
    size <- min(size, n)
  }

  sample.int(n, size = size, replace = replace)
}

#' Predict terminal summaries for one greedy CI tree
#'
#' @noRd
.ci_tree_terminal_predict <- function(fit,
                                      train_data,
                                      new_data,
                                      rank_name,
                                      outcome_name,
                                      weights,
                                      FUN = NULL) {
  train_nodes <- stats::predict(fit, newdata = train_data, type = "node")
  new_nodes <- stats::predict(fit, newdata = new_data, type = "node")

  y <- cbind(
    train_data[[rank_name]],
    train_data[[outcome_name]]
  )
  colnames(y) <- c(rank_name, outcome_name)

  if (is.null(FUN)) {
    FUN <- function(y, w) {
      stats::weighted.mean(y[, outcome_name], w, na.rm = TRUE)
    }
  }

  node_ids <- unique(train_nodes)
  node_values <- stats::setNames(
    vapply(
      node_ids,
      function(node_id) {
        idx <- train_nodes == node_id
        as.numeric(FUN(y[idx, , drop = FALSE], weights[idx]))
      },
      numeric(1)
    ),
    as.character(node_ids)
  )

  global_value <- as.numeric(FUN(y, weights))
  pred <- unname(node_values[as.character(new_nodes)])
  pred[is.na(pred)] <- global_value
  as.numeric(pred)
}

#' Fit a greedy concentration-index forest
#'
#' Grow an ensemble of greedy concentration-index trees. Each tree uses the same
#' greedy tree builder as [ci_tree()] on a perturbed sample of the training
#' data, so the split at each node is chosen by directly maximizing
#' concentration-index gain over candidate variables and split points. The
#' optional `mtry` control randomly samples candidate variables at each node
#' inside the greedy split search.
#'
#' @details `ci_forest()` is an ensemble of greedy CI trees, not a
#' conditional-inference forest. Randomness enters through row perturbation and,
#' optionally, through `mtry`, which restricts the number of predictors searched
#' at each node. Within each tree, the split rule is the same direct
#' maximization of concentration-index gain used by [ci_tree()]. Predictions are
#' aggregated across trees by averaging terminal-node summaries. The fitted
#' object retains the member trees in `object$trees`; model-selection helpers
#' use those internal tree partitions to compute forest-native validation gain.
#'
#' @param formula A model formula, typically with a two-column response such as
#'   `cbind(rank, outcome) ~ x1 + x2`.
#' @param data A data frame containing the variables in `formula`.
#' @param rank_name Name of the socioeconomic rank variable.
#' @param outcome_name Name of the outcome variable.
#' @param weights Optional non-negative case weights.
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"` selecting the
#'   inequality index used for split scoring. `"L"` uses observed
#'   socioeconomic levels in the first response column rather than fractional
#'   ranks.
#' @param control A control object created by [ci_tree_control()]. Objects from
#'   [partykit::ctree_control()] are accepted for their shared controls, but
#'   conditional-inference test controls such as `mincriterion` are ignored by
#'   the greedy tree builder.
#' @param ntree Number of trees to grow.
#' @param mtry Optional number of variables randomly tried at each split.
#' @param perturb Resampling specification. `replace` controls whether rows are
#'   sampled with replacement and `fraction` controls the sample size relative
#'   to the complete analysis data.
#' @param parallel Logical; grow trees with [future.apply::future_lapply()].
#'   The future backend is controlled by the user outside `ci_forest()`, for
#'   example with `future::plan()`.
#' @param future.seed Passed to [future.apply::future_lapply()] when
#'   `parallel = TRUE`.
#' @param na.action A function for handling missing values.
#' @param ... Currently ignored; retained for backwards compatibility.
#'
#' @return A fitted `ci_forest` object containing the greedy trees, in-bag
#'   indicators, fitted values, and forest controls.
#'
#' @examples
#' if (requireNamespace("future", quietly = TRUE) &&
#'     requireNamespace("future.apply", quietly = TRUE)) {
#'   old_plan <- future::plan()
#'   on.exit(future::plan(old_plan), add = TRUE)
#'   future::plan(future::sequential)
#'
#'   fit <- ci_forest(
#'     cbind(rank, outcome) ~ income,
#'     data = data.frame(
#'       rank = c(10, 20, 30, 40, 50, 60),
#'       outcome = c(1, 0, 1, 0, 1, 1),
#'       income = c(2, 4, 6, 8, 10, 12)
#'     ),
#'     rank_name = "rank",
#'     outcome_name = "outcome",
#'     ntree = 3,
#'     parallel = TRUE,
#'     control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
#'   )
#'
#'   nrow(stats::fitted(fit))
#' }
#'
#' @references
#' Breiman L (2001). "Random Forests." *Machine Learning*, 45, 5-32.
#'
#' Breiman L, Friedman JH, Olshen RA, Stone CJ (1984). *Classification and
#' Regression Trees*. Wadsworth.
#'
#' Hothorn T, Zeileis A (2015). "partykit: A Modular Toolkit for Recursive
#' Partytioning in R." *Journal of Machine Learning Research*, 16, 3905-3909.
#' https://jmlr.org/papers/v16/hothorn15a.html.
#'
#' @export

ci_forest <- function(formula,
                      data,
                      rank_name,
                      outcome_name,
                      weights = NULL,
                      type = c("CI", "CIg", "CIc", "L"),
                      control = ci_tree_control(),
                      ntree = 500L,
                      mtry = NULL,
                      perturb = list(replace = FALSE, fraction = 0.632),
                      parallel = FALSE,
                      future.seed = TRUE,
                      na.action = stats::na.omit,
                      ...) {
  type <- match.arg(type)
  call <- match.call()
  extra_args <- list(...)

  if (length(extra_args) > 0L) {
    warning("Additional arguments in `...` are ignored by greedy `ci_forest()`.",
      call. = FALSE
    )
  }
  if (!is.logical(parallel) || length(parallel) != 1L || is.na(parallel)) {
    stop("`parallel` must be a single non-missing logical value.", call. = FALSE)
  }
  parallel <- isTRUE(parallel)

  data <- as.data.frame(data)
  mf <- stats::model.frame(
    formula = formula,
    data = data,
    na.action = na.action,
    drop.unused.levels = FALSE
  )
  omitted <- attr(mf, "na.action")
  keep_rows <- seq_len(nrow(data))
  if (!is.null(omitted)) {
    keep_rows <- keep_rows[-as.integer(omitted)]
  }

  forest_data <- data[keep_rows, , drop = FALSE]
  n <- nrow(forest_data)
  if (n <= 1L) {
    stop("`data` must contain at least two complete rows.", call. = FALSE)
  }

  if (is.null(weights)) {
    weights <- rep(1, n)
  } else {
    if (length(weights) == nrow(data)) {
      weights <- weights[keep_rows]
    }
    if (length(weights) != n) {
      stop("`weights` must have the same length as the analysis data.",
        call. = FALSE
      )
    }
    if (anyNA(weights)) {
      stop("`weights` must not contain missing values.", call. = FALSE)
    }
    if (any(weights < 0, na.rm = TRUE)) {
      stop("`weights` must be non-negative.", call. = FALSE)
    }
    weights <- as.numeric(weights)
  }

  if (!any(weights > 0, na.rm = TRUE)) {
    stop("at least one weight must be positive.", call. = FALSE)
  }

  ntree <- as.integer(ntree)
  if (length(ntree) != 1L || is.na(ntree) || ntree <= 0L) {
    stop("`ntree` must be a positive integer.", call. = FALSE)
  }

  ctrl <- .ci_forest_control(control, mtry)
  terms_object <- stats::terms(mf)
  y_full <- .ci_tree_response(mf, rank_name, outcome_name)
  response_id <- attr(terms_object, "response")
  predictor_ids <- setdiff(seq_along(mf), response_id)

  if (!length(predictor_ids)) {
    stop("`formula` must contain at least one splitting variable.",
      call. = FALSE
    )
  }

  for (j in predictor_ids) {
    if (is.character(mf[[j]])) {
      mf[[j]] <- factor(mf[[j]])
    }
  }

  grow_one_tree <- function(b) {
    sample_rows <- .ci_forest_sample(n, perturb)
    sample_weights <- weights[sample_rows]
    sample_data <- forest_data[sample_rows, , drop = FALSE]

    list(
      fit = .fit_ci_tree_from_frame(
        mf = mf[sample_rows, , drop = FALSE],
        y_full = y_full[sample_rows, , drop = FALSE],
        weights = sample_weights,
        terms_object = terms_object,
        predictor_ids = predictor_ids,
        ctrl = ctrl,
        type = type,
        rank_name = rank_name,
        outcome_name = outcome_name,
        call = call
      ),
      rows = sample_rows,
      data = sample_data,
      weights = sample_weights
    )
  }

  trees <- if (parallel) {
    future.apply::future_lapply(
      seq_len(ntree),
      grow_one_tree,
      future.seed = future.seed
    )
  } else {
    lapply(seq_len(ntree), grow_one_tree)
  }

  inbag <- matrix(0L, nrow = n, ncol = ntree)
  for (b in seq_len(ntree)) {
    inbag[, b] <- tabulate(trees[[b]]$rows, nbins = n)
  }

  fit <- list(
    call = call,
    formula = formula,
    trees = trees,
    data = forest_data,
    weights = weights,
    inbag = inbag,
    rank_name = rank_name,
    outcome_name = outcome_name,
    type = type,
    control = ctrl,
    ntree = ntree,
    perturb = perturb
  )
  class(fit) <- "ci_forest"

  fitted_values <- stats::predict(fit, type = "response", OOB = FALSE)
  fit$fitted <- data.frame(
    `(fitted)` = fitted_values,
    `(response)` = forest_data[[outcome_name]],
    `(weights)` = weights,
    check.names = FALSE
  )

  fit
}

#' Compatibility alias for `ci_forest()`
#'
#' `cf_ci()` is kept for existing code. New code should use [ci_forest()],
#' because the current forest is an ensemble of greedy concentration-index
#' trees rather than a conditional-inference forest.
#'
#' @return A fitted `ci_forest` object.
#' @rdname ci_forest
#' @export
cf_ci <- function(...) {
  ci_forest(...)
}

#' Predict from a greedy concentration-index forest
#'
#' @param object A fitted `ci_forest` object from [ci_forest()].
#' @param newdata Optional data for prediction. If omitted, the training data
#'   stored in `object` are used.
#' @param type Prediction type. `"response"` returns averaged terminal-node
#'   summaries. `"node"` returns terminal node ids for each tree.
#' @param OOB Should predictions for training rows use only trees where the row
#'   was out-of-bag?
#' @param FUN Optional function with signature `function(y, w)` used to
#'   summarize terminal nodes. By default, the weighted mean of `outcome_name`
#'   is used.
#' @param ... Currently ignored.
#'
#' @return A numeric vector for `type = "response"` or an integer matrix for
#'   `type = "node"`.
#'
#' @export
predict.ci_forest <- function(object,
                              newdata = NULL,
                              type = c("response", "node"),
                              OOB = FALSE,
                              FUN = NULL,
                              ...) {
  type <- match.arg(type)
  use_training_data <- is.null(newdata)

  if (use_training_data) {
    newdata <- object$data
  } else {
    newdata <- as.data.frame(newdata)
  }

  pred_mat <- matrix(NA_real_,
    nrow = nrow(newdata),
    ncol = object$ntree
  )

  for (b in seq_len(object$ntree)) {
    tree <- object$trees[[b]]

    if (identical(type, "node")) {
      pred_mat[, b] <- stats::predict(
        tree$fit,
        newdata = newdata,
        type = "node"
      )
    } else {
      pred_mat[, b] <- .ci_tree_terminal_predict(
        fit = tree$fit,
        train_data = tree$data,
        new_data = newdata,
        rank_name = object$rank_name,
        outcome_name = object$outcome_name,
        weights = tree$weights,
        FUN = FUN
      )
    }
  }

  if (identical(type, "node")) {
    colnames(pred_mat) <- paste0("tree_", seq_len(object$ntree))
    return(pred_mat)
  }

  if (isTRUE(OOB)) {
    if (!use_training_data && nrow(newdata) != nrow(object$data)) {
      stop("`OOB = TRUE` is only available for training-data predictions.",
        call. = FALSE
      )
    }

    oob_mat <- pred_mat
    oob_mat[object$inbag > 0L] <- NA_real_
    pred <- rowMeans(oob_mat, na.rm = TRUE)

    no_oob <- is.nan(pred)
    if (any(no_oob)) {
      pred[no_oob] <- rowMeans(pred_mat[no_oob, , drop = FALSE],
        na.rm = TRUE
      )
    }
    return(as.numeric(pred))
  }

  as.numeric(rowMeans(pred_mat, na.rm = TRUE))
}

#' Extract fitted values from a greedy concentration-index forest
#'
#' @param object A fitted `ci_forest` object from [ci_forest()].
#' @param ... Currently ignored.
#'
#' @return A data frame with fitted values, response values, and weights.
#'
#' @export
fitted.ci_forest <- function(object, ...) {
  object$fitted
}

#' @noRd
.ci_party_info <- function(object) {
  info <- unclass(object)[["info"]]
  if (is.null(info)) {
    info <- list()
  }
  info
}

#' @noRd
.ci_or_na <- function(x) {
  if (is.null(x) || length(x) == 0L) {
    return("NA")
  }
  x[[1L]]
}

#' @noRd
.ci_node_info_scalar <- function(info, name) {
  value <- info[[name]]
  if (is.null(value) || length(value) == 0L) {
    return(NA_real_)
  }
  value[[1L]]
}

#' @noRd
.ci_tree_size_summary <- function(object) {
  node_ids <- partykit::nodeids(object)
  terminal_ids <- partykit::nodeids(object, terminal = TRUE)
  node_info <- partykit::nodeapply(
    object,
    ids = node_ids,
    FUN = partykit::info_node
  )
  depth <- vapply(
    node_info,
    function(info) as.numeric(.ci_node_info_scalar(info, "depth")),
    numeric(1)
  )

  list(
    inner_nodes = length(setdiff(node_ids, terminal_ids)),
    terminal_nodes = length(terminal_ids),
    max_depth = if (all(is.na(depth))) NA_integer_ else max(depth, na.rm = TRUE)
  )
}

#' @noRd
.ci_rule_piece <- function(var_name, label) {
  display_name <- tree_pretty_var_name(var_name)
  label <- gsub("\\s+", " ", trimws(as.character(label)))

  if (grepl("^(<=|>=|<|>|=)", label)) {
    return(paste(display_name, label))
  }

  paste0(display_name, " in {", label, "}")
}

#' @noRd
.ci_collect_terminal_rules <- function(node, meta, path = character()) {
  if (partykit::is.terminal(node)) {
    rule <- if (length(path) == 0L) {
      "all observations"
    } else {
      paste(path, collapse = " & ")
    }

    return(data.table::data.table(
      node = as.integer(partykit::id_node(node)),
      rule = rule
    ))
  }

  split_info <- partykit::character_split(partykit::split_node(node), meta)
  kids <- partykit::kids_node(node)

  data.table::rbindlist(lapply(seq_along(kids), function(i) {
    .ci_collect_terminal_rules(
      node = kids[[i]],
      meta = meta,
      path = c(path, .ci_rule_piece(split_info$name, split_info$levels[[i]]))
    )
  }))
}

#' @noRd
.ci_format_scalar <- function(x, digits = 3L) {
  if (length(x) == 0L || is.na(x)) {
    return("NA")
  }
  format(round(as.numeric(x), digits), nsmall = digits, trim = TRUE)
}

#' @noRd
.ci_format_percent <- function(x, digits = 1L) {
  if (length(x) == 0L || is.na(x)) {
    return("NA")
  }
  paste0(format(round(100 * as.numeric(x), digits), nsmall = digits), "%")
}

#' Summarize terminal nodes from a greedy concentration-index tree
#'
#' @description
#' Extracts a compact table of terminal-node diagnostics from a fitted
#' [ci_tree()] model. The table reports node sample size, weighted size,
#' depth, node concentration index, the node-level mean outcome, and the
#' decision rule defining each terminal subgroup.
#'
#' @param object A fitted `ci_tree` object.
#'
#' @return A `data.table` with one row per terminal node.
#'
#' @examples
#' toy_data <- data.frame(
#'   rank = c(10, 20, 30, 40, 50, 60),
#'   outcome = c(1, 0, 1, 0, 1, 1),
#'   income = c(2, 4, 6, 8, 10, 12)
#' )
#' fit <- ci_tree(
#'   cbind(rank, outcome) ~ income,
#'   data = toy_data,
#'   rank_name = "rank",
#'   outcome_name = "outcome",
#'   control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
#' )
#' ci_tree_terminal_summary(fit)
#'
#' data(kenya, package = "ineqTrees")
#'
#' kenya_model_vars <- c(
#'   "wealth",
#'   "deadu5_num",
#'   "rural",
#'   "ed",
#'   "reg",
#'   "unskilled"
#' )
#'
#' kenya_model_data <- kenya[
#'   stats::complete.cases(kenya[, kenya_model_vars]),
#'   kenya_model_vars
#' ]
#'
#' set.seed(20260512)
#' kenya_model_data <- kenya_model_data[
#'   sample.int(nrow(kenya_model_data), 800L),
#'   ,
#'   drop = FALSE
#' ]
#'
#' set.seed(20260512)
#' forest_fit <- ci_forest(
#'   formula = cbind(wealth, deadu5_num) ~ rural + ed + reg + unskilled,
#'   data = kenya_model_data,
#'   rank_name = "wealth",
#'   outcome_name = "deadu5_num",
#'   ntree = 10L,
#'   mtry = 2L,
#'   control = ci_tree_control(
#'     minsplit = 100,
#'     minbucket = 50,
#'     minprob = 0.05,
#'     maxdepth = 3
#'   )
#' )
#'
#' ci_forest_summary(forest_fit)
#' head(stats::predict(forest_fit, OOB = FALSE))
#' @export
ci_tree_terminal_summary <- function(object) {
  if (!inherits(object, "ci_tree")) {
    stop("`object` must be a fitted `ci_tree`.", call. = FALSE)
  }

  terminal_ids <- partykit::nodeids(object, terminal = TRUE)
  node_info <- partykit::nodeapply(
    object,
    ids = terminal_ids,
    FUN = partykit::info_node
  )
  rules <- .ci_collect_terminal_rules(
    node = partykit::node_party(object),
    meta = partykit::data_party(object)
  )

  out <- data.table::rbindlist(lapply(seq_along(terminal_ids), function(i) {
    info <- node_info[[i]]
    outcome_mean <- as.numeric(.ci_node_info_scalar(info, "outcome_mean"))
    data.table::data.table(
      node = as.integer(terminal_ids[[i]]),
      n = as.integer(.ci_node_info_scalar(info, "n")),
      weight = as.numeric(.ci_node_info_scalar(info, "weight")),
      depth = as.integer(.ci_node_info_scalar(info, "depth")),
      ci = as.numeric(.ci_node_info_scalar(info, "ci")),
      outcome_mean = outcome_mean,
      outcome_percent = 100 * outcome_mean
    )
  }), fill = TRUE)

  out <- merge(out, rules, by = "node", all.x = TRUE, sort = FALSE)
  data.table::setorderv(out, "node")
  out
}

#' Summarize a greedy concentration-index forest
#'
#' @description
#' Computes a one-row diagnostic summary for a fitted [ci_forest()] forest,
#' including ensemble size, tree complexity, observed outcome, fitted
#' prediction, and concentration index of both the observed and fitted outcome.
#'
#' @param object A fitted `ci_forest` object.
#'
#' @return A one-row `data.table`.
#'
#' @examples
#' toy_data <- data.frame(
#'   rank = c(10, 20, 30, 40, 50, 60),
#'   outcome = c(1, 0, 1, 0, 1, 1),
#'   income = c(2, 4, 6, 8, 10, 12)
#' )
#' fit <- ci_forest(
#'   cbind(rank, outcome) ~ income,
#'   data = toy_data,
#'   rank_name = "rank",
#'   outcome_name = "outcome",
#'   ntree = 3,
#'   control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
#' )
#' ci_forest_summary(fit)
#'
#' @export
ci_forest_summary <- function(object) {
  if (!inherits(object, "ci_forest")) {
    stop("`object` must be a fitted `ci_forest`.", call. = FALSE)
  }

  tree_sizes <- lapply(object$trees, function(tree) {
    .ci_tree_size_summary(tree$fit)
  })
  terminal_nodes <- vapply(tree_sizes, `[[`, numeric(1), "terminal_nodes")
  max_depth <- vapply(tree_sizes, `[[`, numeric(1), "max_depth")

  observed <- object$data[[object$outcome_name]]
  fitted <- stats::predict(object, OOB = FALSE)
  weights <- object$weights
  ci_fun <- ci_factory(object$type)

  observed_ci <- ci_fun(
    cbind(object$data[[object$rank_name]], observed),
    weights
  )
  fitted_ci <- ci_fun(
    cbind(object$data[[object$rank_name]], fitted),
    weights
  )

  data.table::data.table(
    ntree = object$ntree,
    mtry = if (is.null(object$control$mtry)) NA_integer_ else object$control$mtry,
    type = object$type,
    n = nrow(object$data),
    mean_outcome = stats::weighted.mean(observed, weights, na.rm = TRUE),
    mean_prediction = stats::weighted.mean(fitted, weights, na.rm = TRUE),
    outcome_ci = as.numeric(observed_ci),
    prediction_ci = as.numeric(fitted_ci),
    mean_terminal_nodes = mean(terminal_nodes, na.rm = TRUE),
    mean_max_depth = mean(max_depth, na.rm = TRUE)
  )
}

#' Print a greedy concentration-index tree
#'
#' @param x A fitted `ci_tree` object.
#' @param ... Currently ignored.
#' @param nodes Number of terminal nodes to show in the console summary.
#' @param digits Number of digits used for printed numeric summaries.
#'
#' @return `x`, invisibly.
#'
#' @export
print.ci_tree <- function(x, ..., nodes = 10L, digits = 3L) {
  info <- .ci_party_info(x)
  root <- partykit::info_node(partykit::node_party(x))
  size <- .ci_tree_size_summary(x)
  terminal <- ci_tree_terminal_summary(x)

  cat("Greedy concentration-index tree\n\n")
  cat("Formula:\n")
  cat("  ", paste(deparse(stats::formula(x)), collapse = " "), "\n\n", sep = "")
  cat("Criterion: ", .ci_or_na(info$type), "\n", sep = "")
  cat("Observations: ", .ci_node_info_scalar(root, "n"), "\n", sep = "")
  cat("Inner nodes: ", size$inner_nodes, "\n", sep = "")
  cat("Terminal nodes: ", size$terminal_nodes, "\n", sep = "")
  cat("Max depth: ", size$max_depth, "\n\n", sep = "")
  cat("Root node:\n")
  cat("  mean outcome = ",
    .ci_format_percent(.ci_node_info_scalar(root, "outcome_mean"), 1L),
    "\n",
    sep = ""
  )
  cat("  ", .ci_or_na(info$type), " = ",
    .ci_format_scalar(.ci_node_info_scalar(root, "ci"), digits),
    "\n\n",
    sep = ""
  )

  cat("Terminal node summary (highest criterion first):\n")
  terminal_print <- data.table::copy(terminal)
  data.table::setorderv(terminal_print, c("ci", "weight", "node"), c(-1L, -1L, 1L))
  terminal_print <- as.data.frame(utils::head(terminal_print, nodes))
  names(terminal_print)[names(terminal_print) == "ci"] <- .ci_or_na(info$type)
  terminal_print[[.ci_or_na(info$type)]] <- round(terminal_print[[.ci_or_na(info$type)]], digits)
  terminal_print$outcome_mean <- round(terminal_print$outcome_mean, digits)
  terminal_print$outcome_percent <- round(terminal_print$outcome_percent, 1L)
  print(terminal_print, row.names = FALSE)
  if (nrow(terminal) > nodes) {
    cat("... ", nrow(terminal) - nodes, " more terminal nodes\n", sep = "")
  }

  invisible(x)
}

#' Print a greedy concentration-index forest
#'
#' @param x A fitted `ci_forest` object.
#' @param ... Currently ignored.
#' @param digits Number of digits used for printed numeric summaries.
#'
#' @return `x`, invisibly.
#'
#' @export
print.ci_forest <- function(x, ..., digits = 3L) {
  summary <- ci_forest_summary(x)
  perturb <- x$perturb
  replace <- isTRUE(perturb$replace)
  fraction <- if (is.null(perturb$fraction)) NA_real_ else perturb$fraction

  cat("Greedy concentration-index forest\n\n")
  cat("Formula:\n")
  cat("  ", paste(deparse(x$formula), collapse = " "), "\n\n", sep = "")
  cat("Criterion: ", x$type, "\n", sep = "")
  cat("Trees: ", x$ntree, "\n", sep = "")
  cat("mtry: ",
    if (is.null(x$control$mtry)) "all variables" else x$control$mtry,
    "\n",
    sep = ""
  )
  cat("Resampling: fraction = ",
    .ci_format_scalar(fraction, 3L),
    ", replace = ",
    replace,
    "\n\n",
    sep = ""
  )

  out <- as.data.frame(summary)
  numeric_cols <- vapply(out, is.numeric, logical(1))
  out[numeric_cols] <- lapply(out[numeric_cols], round, digits = digits)
  print(out, row.names = FALSE)

  invisible(x)
}

#' Knit-print a greedy concentration-index tree
#'
#' @param x A fitted `ci_tree` object.
#' @param ... Currently ignored.
#'
#' @return A `knitr` as-is output object.
#'
#' @exportS3Method knitr::knit_print
knit_print.ci_tree <- function(x, ...) {
  if (!requireNamespace("knitr", quietly = TRUE)) {
    return(utils::capture.output(print(x)))
  }

  info <- .ci_party_info(x)
  size <- .ci_tree_size_summary(x)
  terminal <- ci_tree_terminal_summary(x)
  data.table::setorderv(terminal, c("ci", "weight", "node"), c(-1L, -1L, 1L))
  names(terminal)[names(terminal) == "ci"] <- .ci_or_na(info$type)
  terminal[[.ci_or_na(info$type)]] <- round(terminal[[.ci_or_na(info$type)]], 3L)
  terminal$outcome_mean <- round(terminal$outcome_mean, 3L)
  terminal$outcome_percent <- round(terminal$outcome_percent, 1L)

  text <- c(
    "### Greedy concentration-index tree",
    "",
    paste0("**Formula:** `", paste(deparse(stats::formula(x)), collapse = " "), "`"),
    paste0("**Criterion:** ", .ci_or_na(info$type)),
    paste0(
      "**Tree size:** ",
      size$inner_nodes,
      " inner nodes, ",
      size$terminal_nodes,
      " terminal nodes, max depth ",
      size$max_depth
    ),
    "",
    knitr::kable(terminal, caption = "Terminal-node summary with subgroup rules")
  )

  knitr::asis_output(paste(text, collapse = "\n"))
}

#' Knit-print a greedy concentration-index forest
#'
#' @param x A fitted `ci_forest` object.
#' @param ... Currently ignored.
#'
#' @return A `knitr` as-is output object.
#'
#' @exportS3Method knitr::knit_print
knit_print.ci_forest <- function(x, ...) {
  if (!requireNamespace("knitr", quietly = TRUE)) {
    return(utils::capture.output(print(x)))
  }

  summary <- ci_forest_summary(x)
  summary <- as.data.frame(summary)
  numeric_cols <- vapply(summary, is.numeric, logical(1))
  summary[numeric_cols] <- lapply(summary[numeric_cols], round, digits = 3L)

  text <- c(
    "### Greedy concentration-index forest",
    "",
    paste0("**Formula:** `", paste(deparse(x$formula), collapse = " "), "`"),
    paste0("**Criterion:** ", x$type),
    paste0("**Trees:** ", x$ntree),
    "",
    knitr::kable(summary, caption = "Forest summary")
  )

  knitr::asis_output(paste(text, collapse = "\n"))
}
