# WARNING - Generated by {fusen} from dev/tidymodels_bridge.Rmd: do not edit by hand # nolint: line_length_linter.

utils::globalVariables(c("object", "new_data"))

#' Convert parsnip formulas to the two-column CI response
#'
#' @noRd
.ci_parsnip_formula <- function(formula, data, rank_name, outcome_name) {
  response_vars <- all.vars(formula[[2L]])
  response_call <- formula[[2L]]
  is_ci_response <- is.call(response_call) &&
    identical(as.character(response_call[[1L]]), "cbind") &&
    length(response_vars) >= 2L

  if (is_ci_response) {
    return(list(formula = formula, outcome_name = outcome_name))
  }

  if (!rank_name %in% names(data)) {
    stop("`data` must contain `rank_name` when using a single-outcome formula.",
      call. = FALSE
    )
  }

  actual_outcome_name <- outcome_name
  if (!actual_outcome_name %in% names(data) &&
      length(response_vars) &&
      response_vars[[1L]] %in% names(data)) {
    actual_outcome_name <- response_vars[[1L]]
  }
  if (!actual_outcome_name %in% names(data)) {
    stop(
      "`data` must contain `outcome_name` when using a single-outcome formula.",
      call. = FALSE
    )
  }

  term_labels <- attr(stats::terms(formula, data = data), "term.labels")
  if (identical(term_labels, ".")) {
    predictor_names <- names(data)
  } else {
    predictor_names <- term_labels
  }
  predictor_names <- setdiff(
    predictor_names,
    c(rank_name, outcome_name, actual_outcome_name)
  )
  if (!length(predictor_names)) {
    stop("`formula` must contain at least one predictor besides `rank_name`.",
      call. = FALSE
    )
  }

  rhs <- paste(predictor_names, collapse = " + ")
  formula <- stats::as.formula(
    paste0("cbind(", rank_name, ", ", outcome_name, ") ~ ", rhs),
    env = environment(formula)
  )
  if (!identical(actual_outcome_name, outcome_name)) {
    formula <- stats::as.formula(
      paste0("cbind(", rank_name, ", ", actual_outcome_name, ") ~ ", rhs),
      env = environment(formula)
    )
  }

  list(formula = formula, outcome_name = actual_outcome_name)
}

#' Fit a greedy CI tree from parsnip
#'
#' @description
#' A small wrapper used by the `ineqTrees` parsnip engine for
#' `parsnip::decision_tree()`. The formula can be either the native
#' `cbind(rank, outcome) ~ predictors` response or the usual tidymodels
#' `outcome ~ predictors` response when `rank_name` and `outcome_name` are
#' supplied through `set_engine()`.
#'
#' @param formula A model formula, typically
#'   `cbind(rank, outcome) ~ predictors`.
#' @param data A data frame containing the variables in `formula`.
#' @param weights Optional case weights supplied by parsnip/hardhat.
#' @param rank_name Name of the socioeconomic rank variable.
#' @param outcome_name Name of the outcome variable.
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"`.
#' @param tree_depth Optional parsnip tree-depth value.
#' @param minbucket Minimum weighted child-node size.
#' @param minsplit Minimum weighted parent-node size.
#' @param minprob Minimum child-node weight proportion.
#' @param maxdepth Maximum tree depth. When supplied through `set_engine()`,
#'   this overrides `tree_depth`.
#' @param min_gain Minimum concentration-index gain required to split.
#' @param na.action Function for handling missing values.
#' @param ... Additional arguments passed to [ci_tree()].
#'
#' @return A fitted `ci_tree` object.
#'
#' @export
ci_tree_parsnip <- function(formula,
                            data,
                            weights = NULL,
                            rank_name = "wealth",
                            outcome_name = "deadu5_num",
                            type = "CIg",
                            tree_depth = NULL,
                            minbucket = 100L,
                            minsplit = 200L,
                            minprob = 0.01,
                            maxdepth = 4L,
                            min_gain = 0,
                            na.action = stats::na.omit,
                            ...) {
  if (!is.null(weights)) {
    weights <- as.numeric(weights)
  }

  if (!missing(maxdepth)) {
    depth <- maxdepth
  } else if (!is.null(tree_depth)) {
    depth <- tree_depth
  } else {
    depth <- maxdepth
  }

  control <- ci_tree_control(
    minsplit = as.integer(minsplit),
    minbucket = as.integer(minbucket),
    minprob = minprob,
    maxdepth = as.integer(depth),
    min_gain = min_gain
  )

  prepared <- .ci_parsnip_formula(
    formula = formula,
    data = data,
    rank_name = rank_name,
    outcome_name = outcome_name
  )
  formula <- prepared$formula
  outcome_name <- prepared$outcome_name

  ci_tree(
    formula = formula,
    data = data,
    rank_name = rank_name,
    outcome_name = outcome_name,
    weights = weights,
    type = type,
    control = control,
    na.action = na.action,
    ...
  )
}

#' Fit a greedy CI forest from parsnip
#'
#' @description
#' A small wrapper used by the `ineqTrees` parsnip engine for
#' `parsnip::rand_forest()`.
#'
#' @inheritParams ci_tree_parsnip
#' @param ntree Number of trees to grow.
#' @param mtry Optional number of variables tried at each split.
#' @param perturb Resampling specification passed to [ci_forest()].
#'
#' @return A fitted `ci_forest` object.
#'
#' @export
ci_forest_parsnip <- function(formula,
                              data,
                              weights = NULL,
                              rank_name = "wealth",
                              outcome_name = "deadu5_num",
                              type = "CIg",
                              ntree = 500L,
                              mtry = NULL,
                              minbucket = 100L,
                              minsplit = 200L,
                              minprob = 0.01,
                              maxdepth = 4L,
                              min_gain = 0,
                              perturb = list(replace = FALSE, fraction = 0.632),
                              na.action = stats::na.omit,
                              ...) {
  if (!is.null(weights)) {
    weights <- as.numeric(weights)
  }

  control <- ci_tree_control(
    minsplit = as.integer(minsplit),
    minbucket = as.integer(minbucket),
    minprob = minprob,
    maxdepth = as.integer(maxdepth),
    min_gain = min_gain
  )

  prepared <- .ci_parsnip_formula(
    formula = formula,
    data = data,
    rank_name = rank_name,
    outcome_name = outcome_name
  )
  formula <- prepared$formula
  outcome_name <- prepared$outcome_name

  ci_forest(
    formula = formula,
    data = data,
    rank_name = rank_name,
    outcome_name = outcome_name,
    weights = weights,
    type = type,
    control = control,
    ntree = as.integer(ntree),
    mtry = mtry,
    perturb = perturb,
    na.action = na.action,
    ...
  )
}

#' Register `ineqTrees` parsnip engines
#'
#' @description
#' Registers `ineqTrees` as a regression engine for
#' `parsnip::decision_tree()` and `parsnip::rand_forest()`.
#'
#' @return Invisibly, `TRUE`.
#'
#' @examples
#' if (requireNamespace("parsnip", quietly = TRUE)) {
#'   register_ineqtrees_parsnip()
#' }
#'
#' @export
register_ineqtrees_parsnip <- function() {
  register_ineqtrees_decision_tree()
  register_ineqtrees_rand_forest()
  invisible(TRUE)
}

#' Register the `decision_tree()` `ineqTrees` engine
#'
#' @return Invisibly, `TRUE`.
#'
#' @export
register_ineqtrees_decision_tree <- function() {
  if (!any(parsnip::show_engines("decision_tree")$engine == "ineqTrees")) {
    parsnip::set_model_engine(
      model = "decision_tree",
      mode = "regression",
      eng = "ineqTrees"
    )
  }

  parsnip::set_dependency("decision_tree", eng = "ineqTrees", pkg = "ineqTrees")

  parsnip::set_model_arg(
    model = "decision_tree",
    eng = "ineqTrees",
    parsnip = "tree_depth",
    original = "tree_depth",
    func = list(pkg = "dials", fun = "tree_depth"),
    has_submodel = FALSE
  )

  parsnip::set_model_arg(
    model = "decision_tree",
    eng = "ineqTrees",
    parsnip = "min_n",
    original = "minbucket",
    func = list(pkg = "dials", fun = "min_n"),
    has_submodel = FALSE
  )

  parsnip::set_encoding(
    model = "decision_tree",
    mode = "regression",
    eng = "ineqTrees",
    options = list(
      predictor_indicators = "none",
      compute_intercept = FALSE,
      remove_intercept = FALSE,
      allow_sparse_x = FALSE
    )
  )

  parsnip::set_fit(
    model = "decision_tree",
    mode = "regression",
    eng = "ineqTrees",
    value = list(
      interface = "formula",
      data = c(formula = "formula", data = "data", weights = "weights"),
      protect = c("formula", "data", "weights"),
      func = c(pkg = "ineqTrees", fun = "ci_tree_parsnip"),
      defaults = list()
    )
  )

  parsnip::set_pred(
    model = "decision_tree",
    mode = "regression",
    eng = "ineqTrees",
    type = "numeric",
    value = list(
      pre = NULL,
      post = function(results, object) {
        tibble::tibble(.pred = as.numeric(results))
      },
      func = c(fun = "predict"),
      args = list(
        object = rlang::expr(object$fit),
        newdata = rlang::expr(new_data),
        type = "response"
      )
    )
  )

  parsnip::set_pred(
    model = "decision_tree",
    mode = "regression",
    eng = "ineqTrees",
    type = "raw",
    value = list(
      pre = NULL,
      post = function(results, object) {
        tibble::tibble(.node = as.integer(results))
      },
      func = c(fun = "predict"),
      args = list(
        object = rlang::expr(object$fit),
        newdata = rlang::expr(new_data),
        type = "node"
      )
    )
  )

  invisible(TRUE)
}

#' Register the `rand_forest()` `ineqTrees` engine
#'
#' @return Invisibly, `TRUE`.
#'
#' @export
register_ineqtrees_rand_forest <- function() {
  if (!any(parsnip::show_engines("rand_forest")$engine == "ineqTrees")) {
    parsnip::set_model_engine(
      model = "rand_forest",
      mode = "regression",
      eng = "ineqTrees"
    )
  }

  parsnip::set_dependency("rand_forest", eng = "ineqTrees", pkg = "ineqTrees")

  parsnip::set_model_arg(
    model = "rand_forest",
    eng = "ineqTrees",
    parsnip = "trees",
    original = "ntree",
    func = list(pkg = "dials", fun = "trees"),
    has_submodel = FALSE
  )

  parsnip::set_model_arg(
    model = "rand_forest",
    eng = "ineqTrees",
    parsnip = "mtry",
    original = "mtry",
    func = list(pkg = "dials", fun = "mtry"),
    has_submodel = FALSE
  )

  parsnip::set_model_arg(
    model = "rand_forest",
    eng = "ineqTrees",
    parsnip = "min_n",
    original = "minbucket",
    func = list(pkg = "dials", fun = "min_n"),
    has_submodel = FALSE
  )

  parsnip::set_encoding(
    model = "rand_forest",
    mode = "regression",
    eng = "ineqTrees",
    options = list(
      predictor_indicators = "none",
      compute_intercept = FALSE,
      remove_intercept = FALSE,
      allow_sparse_x = FALSE
    )
  )

  parsnip::set_fit(
    model = "rand_forest",
    mode = "regression",
    eng = "ineqTrees",
    value = list(
      interface = "formula",
      data = c(formula = "formula", data = "data", weights = "weights"),
      protect = c("formula", "data", "weights"),
      func = c(pkg = "ineqTrees", fun = "ci_forest_parsnip"),
      defaults = list()
    )
  )

  parsnip::set_pred(
    model = "rand_forest",
    mode = "regression",
    eng = "ineqTrees",
    type = "numeric",
    value = list(
      pre = NULL,
      post = function(results, object) {
        tibble::tibble(.pred = as.numeric(results))
      },
      func = c(fun = "predict"),
      args = list(
        object = rlang::expr(object$fit),
        newdata = rlang::expr(new_data),
        type = "response"
      )
    )
  )

  parsnip::set_pred(
    model = "rand_forest",
    mode = "regression",
    eng = "ineqTrees",
    type = "raw",
    value = list(
      pre = NULL,
      post = function(results, object) {
        tibble::as_tibble(as.data.frame(results))
      },
      func = c(fun = "predict"),
      args = list(
        object = rlang::expr(object$fit),
        newdata = rlang::expr(new_data),
        type = "node"
      )
    )
  )

  invisible(TRUE)
}

#' @noRd
.onLoad <- function(libname, pkgname) {
  register_ineqtrees_parsnip()
}

#' Concentration-index gain for a prediction partition
#'
#' @description
#' Computes the concentration-index impurity reduction from a root partition to
#' groups defined by terminal-node ids or another supplied partition column.
#' This is the yardstick-compatible counterpart to [ci_tree_validation_gain()].
#'
#' @param truth Numeric or logical observed outcomes.
#' @param estimate Numeric predictions. Used as the partition only when `node`
#'   is `NULL`.
#' @param rank Socioeconomic rank values.
#' @param node Optional terminal-node or partition ids. True CI gain requires a
#'   partition; using predictions as a fallback is only an approximation.
#' @param case_weights Optional non-negative case weights.
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"`.
#' @param root_impurity Optional pre-computed root impurity.
#' @param na_rm Should incomplete rows be removed?
#' @param ... Not used.
#'
#' @importFrom yardstick new_numeric_metric
#' @return A numeric concentration-index gain.
#'
#' @export
ci_gain_vec <- function(truth,
                        estimate,
                        rank,
                        node = NULL,
                        case_weights = NULL,
                        type = "CIg",
                        root_impurity = NULL,
                        na_rm = TRUE,
                        ...) {
  truth <- .ci_outcome_numeric(truth, "truth")
  estimate <- as.numeric(estimate)
  rank <- as.numeric(rank)

  if (length(truth) != length(estimate) || length(truth) != length(rank)) {
    stop(
      "`truth`, `estimate`, and `rank` must have the same length.",
      call. = FALSE
    )
  }

  case_weights <- .ci_validate_weights(
    case_weights,
    length(truth),
    "case_weights"
  )

  if (is.null(node)) {
    node <- estimate
  }
  if (length(node) != length(truth)) {
    stop("`node` must have the same length as `truth`.", call. = FALSE)
  }

  keep <- stats::complete.cases(truth, estimate, rank, node, case_weights) &
    case_weights > 0

  if (!na_rm && any(!keep)) {
    return(NA_real_)
  }
  if (!any(keep)) {
    return(NA_real_)
  }

  truth <- truth[keep]
  rank <- rank[keep]
  node <- node[keep]
  case_weights <- case_weights[keep]

  ci_fun <- ci_factory(type)
  y <- cbind(rank = rank, outcome = truth)

  if (is.null(root_impurity)) {
    root_impurity <- ci_fun(y, case_weights)
  }

  total_weight <- sum(case_weights)
  node_indices <- split(seq_along(truth), node)

  child_impurity <- sum(vapply(
    node_indices,
    function(idx) {
      node_weight <- sum(case_weights[idx])
      (node_weight / total_weight) *
        ci_fun(y[idx, , drop = FALSE], case_weights[idx])
    },
    numeric(1)
  ))

  as.numeric(root_impurity - child_impurity)
}

#' Concentration-index gain metric
#'
#' @param data A data frame.
#' @param ... Arguments passed to methods.
#'
#' @return A yardstick metric tibble.
#'
#' @export
ci_gain <- function(data, ...) {
  UseMethod("ci_gain")
}

ci_gain <- yardstick::new_numeric_metric(ci_gain, direction = "maximize")

#' @export
ci_gain.data.frame <- function(data,
                               truth,
                               estimate,
                               rank,
                               node = NULL,
                               case_weights = NULL,
                               type = "CIg",
                               root_impurity = NULL,
                               na_rm = TRUE,
                               ...) {
  truth <- rlang::enquo(truth)
  estimate <- rlang::enquo(estimate)
  rank <- rlang::enquo(rank)
  node <- rlang::enquo(node)
  case_weights <- rlang::enquo(case_weights)

  truth_vec <- rlang::eval_tidy(truth, data)
  estimate_vec <- rlang::eval_tidy(estimate, data)
  rank_vec <- rlang::eval_tidy(rank, data)

  node_vec <- if (rlang::quo_is_null(node)) {
    NULL
  } else {
    rlang::eval_tidy(node, data)
  }

  weight_vec <- if (rlang::quo_is_null(case_weights)) {
    NULL
  } else {
    rlang::eval_tidy(case_weights, data)
  }

  tibble::tibble(
    .metric = "ci_gain",
    .estimator = "standard",
    .estimate = ci_gain_vec(
      truth = truth_vec,
      estimate = estimate_vec,
      rank = rank_vec,
      node = node_vec,
      case_weights = weight_vec,
      type = type,
      root_impurity = root_impurity,
      na_rm = na_rm
    )
  )
}

#' Concentration index of predictions
#'
#' @description
#' Computes the concentration index of fitted risks or predicted outcomes. This
#' is not split gain, but it is useful for comparing inequality in predictions.
#'
#' @inheritParams ci_gain_vec
#'
#' @return A numeric concentration-index value.
#'
#' @export
ci_prediction_index_vec <- function(estimate,
                                    rank,
                                    case_weights = NULL,
                                    type = "CIg") {
  estimate <- as.numeric(estimate)
  rank <- as.numeric(rank)

  if (length(estimate) != length(rank)) {
    stop("`estimate` and `rank` must have the same length.", call. = FALSE)
  }

  case_weights <- .ci_validate_weights(
    case_weights,
    length(estimate),
    "case_weights"
  )

  keep <- stats::complete.cases(estimate, rank, case_weights) & case_weights > 0
  if (!any(keep)) {
    return(NA_real_)
  }

  ci_factory(type)(
    cbind(rank = rank[keep], outcome = estimate[keep]),
    case_weights[keep]
  )
}

#' Concentration-index prediction metric
#'
#' @param data A data frame.
#' @param ... Arguments passed to methods.
#'
#' @return A yardstick metric tibble.
#'
#' @export
ci_prediction_index <- function(data, ...) {
  UseMethod("ci_prediction_index")
}

ci_prediction_index <- yardstick::new_numeric_metric(
  ci_prediction_index,
  direction = "maximize"
)

#' @export
ci_prediction_index.data.frame <- function(data,
                                           truth,
                                           estimate,
                                           rank,
                                           case_weights = NULL,
                                           type = "CIg",
                                           ...) {
  estimate <- rlang::enquo(estimate)
  rank <- rlang::enquo(rank)
  case_weights <- rlang::enquo(case_weights)

  estimate_vec <- rlang::eval_tidy(estimate, data)
  rank_vec <- rlang::eval_tidy(rank, data)
  weight_vec <- if (rlang::quo_is_null(case_weights)) {
    NULL
  } else {
    rlang::eval_tidy(case_weights, data)
  }

  tibble::tibble(
    .metric = "ci_prediction_index",
    .estimator = "standard",
    .estimate = ci_prediction_index_vec(
      estimate = estimate_vec,
      rank = rank_vec,
      case_weights = weight_vec,
      type = type
    )
  )
}
