# WARNING - Generated by {fusen} from dev/ci_tree_models.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fit a greedy CI tree from a prepared model frame
#'
#' @noRd
.fit_ci_tree_from_frame <- function(mf,
                                    y_full,
                                    weights,
                                    terms_object,
                                    predictor_ids,
                                    ctrl,
                                    type,
                                    rank_name,
                                    outcome_name,
                                    call = NULL) {
  if (!length(predictor_ids)) {
    stop("`formula` must contain at least one splitting variable.",
      call. = FALSE
    )
  }

  if (nrow(y_full) != nrow(mf) || length(weights) != nrow(mf)) {
    stop("prepared tree inputs must have the same number of rows.",
      call. = FALSE
    )
  }

  ci_fun <- ci_factory(type)

  tree <- .build_ci_tree(
    data = mf,
    y = y_full,
    wt = weights,
    vars = predictor_ids,
    ctrl = ctrl,
    ci_fun = ci_fun
  )

  fitted <- data.frame(
    `(fitted)` = tree$fitted,
    `(response)` = y_full[, 2],
    `(weights)` = weights,
    check.names = FALSE
  )

  fit <- partykit::party(
    node = tree$node,
    data = mf,
    fitted = fitted,
    terms = terms_object,
    info = list(
      call = call,
      control = ctrl,
      type = type,
      rank_name = rank_name,
      outcome_name = outcome_name,
      greedy = TRUE
    )
  )
  class(fit) <- unique(c("ci_tree", "constparty", class(fit)))
  fit
}

#' Convert non-negative weights to integer case weights
#'
#' Rescale a non-negative weight vector so that its total is approximately
#' `scale`, then round to integers for use with fitting routines that require
#' integer case weights.
#'
#' @param w A numeric vector of non-negative weights.
#' @param scale Target total for the rescaled integer case weights.
#'
#' @return An integer vector of case weights on the same scale as `w`.
#'
#' @examples
#' as_caseweights(c(1, 2, 3), scale = 60L)
#' as_caseweights(c(0.2, 0.3, 0.5))
#'
#' as_caseweights(c(1, 2, 3), scale = 60L)
#' as_caseweights(c(0.2, 0.3, 0.5))
#' @export

as_caseweights <- function(w, scale = 10000L) {
  stopifnot(all(w >= 0, na.rm = TRUE))
  if (!any(w > 0, na.rm = TRUE)) stop("all weights are zero")
  out <- round(w / sum(w, na.rm = TRUE) * scale)
  as.integer(out)
}

#' Create a concentration-index split function
#'
#' Build a split-selection function for inequality-aware tree fitting. The
#' returned function evaluates candidate predictors by the reduction in
#' within-node concentration index produced by each admissible split.
#'
#' The split function can recover the two-column response either from a matrix-
#' like response in the first model-frame column, or from separate columns named
#' by `rank_name` and `outcome_name`.
#'
#' @param rank_name Name of the socioeconomic rank variable in the model frame
#'   when the response is not supplied as a two-column matrix.
#' @param outcome_name Name of the outcome variable in the model frame when the
#'   response is not supplied as a two-column matrix.
#' @param type One of `"CI"`, `"CIg"`, or `"CIc"` selecting the concentration
#'   index variant used for split scoring.
#'
#' @return A function with signature
#'   `function(model, trafo, data, subset, weights, whichvar, ctrl)` suitable
#'   for tree-splitting workflows. It returns the first admissible `partysplit`
#'   found among `whichvar`, or `NULL` if no candidate variable yields a valid
#'   split.
#'
#' @export 
#' @examples
#' splitfun <- ci_splitfun(
#'   rank_name = "rank",
#'   outcome_name = "outcome",
#'   type = "CI"
#' )
#'
#' toy_data <- data.frame(
#'   rank = c(10, 20, 30, 40, 50),
#'   outcome = c(1, 0, 1, 0, 1),
#'   income = c(2, 4, 6, 8, 10)
#' )
#'
#' ctrl <- list(minsplit = 1, minbucket = 1, minprob = 0)
#'
#' split <- splitfun(
#'   model = NULL,
#'   trafo = NULL,
#'   data = toy_data,
#'   subset = seq_len(nrow(toy_data)),
#'   weights = rep(1, nrow(toy_data)),
#'   whichvar = 3,
#'   ctrl = ctrl
#' )
#' split$breaks

ci_splitfun <- function(rank_name, outcome_name, type = c("CI", "CIg", "CIc")) {
  type <- match.arg(type)
  ci_fun <- ci_factory(type)

  function(model, trafo, data, subset, weights, whichvar, ctrl) {
    mf <- stats::model.frame(data)

    if (is.null(weights) || length(weights) == 0L) {
      weights <- rep.int(1L, nrow(mf))
    }

    # For formulas like cbind(rank, outcome) ~ x1 + x2, the response may arrive
    # as a matrix-like object in the first model-frame column.
    response <- mf[[1L]]
    y_full <- NULL

    if (is.matrix(response) || is.data.frame(response)) {
      response_mat <- tryCatch(as.matrix(response), error = function(e) NULL)
      if (!is.null(response_mat) && is.matrix(response_mat) &&
          ncol(response_mat) >= 2L) {
        y_full <- response_mat[, 1:2, drop = FALSE]
      }
    }

    if (is.null(y_full)) {
      rank_vec <- mf[[rank_name]]
      outcome_vec <- mf[[outcome_name]]

      if (!is.null(rank_vec) && !is.null(outcome_vec)) {
        y_full <- cbind(rank = rank_vec, outcome = outcome_vec)
      }
    }

    if (is.null(y_full) || !is.matrix(y_full) || ncol(y_full) != 2L) {
      stop(
        "Unable to recover the two-column response expected by `ci_tree()`. ",
        "Use a response like `cbind(rank, outcome) ~ ...`."
      )
    }

    colnames(y_full) <- c("rank", "outcome")

    # extree/.split may pass several candidate vars in ranked order
    for (j in whichvar) {
      x_full <- mf[[j]]

      keep <- subset[
        !is.na(x_full[subset]) &
        !is.na(y_full[subset, 1]) &
        !is.na(y_full[subset, 2]) &
        weights[subset] > 0
      ]

      if (!length(keep)) next

      w_node <- sum(weights[keep], na.rm = TRUE)
      if (w_node < ctrl$minsplit) next

      x_subset <- x_full[keep]

      sp <- NULL

      if (is.numeric(x_subset)) {
        sp <- best_numeric_split(
          x     = x_subset,
          y     = y_full[keep, , drop = FALSE],
          wt    = weights[keep],
          varid = j,
          ctrl  = ctrl,
          ci_fun = ci_fun
        )
      } else if (is.factor(x_subset) || is.ordered(x_subset)) {
        # use full x_full to preserve full level mapping in partysplit()
        sp <- best_factor_split(
          x_full = if (is.factor(x_full)) x_full else factor(x_full),
          keep   = keep,
          y_full = y_full,
          wt_full = weights,
          varid  = j,
          ctrl   = ctrl,
          ci_fun = ci_fun
        )
      }

      if (!is.null(sp)) return(sp)
    }

    NULL
  }
}

#' Fit a greedy concentration-index tree
#'
#' Grow a binary tree by directly maximizing concentration-index gain across
#' all candidate variables and split points at each node, while storing the
#' result as a standard [partykit::party()] object.
#'
#' This helper is intended for inequality-aware tree fitting where the response
#' contains a socioeconomic ranking variable and a health outcome. Unlike
#' [partykit::ctree()], it does not use conditional-inference tests for
#' first-stage variable selection.
#'
#' @details At each non-terminal node `t`, `ci_tree()` searches across all
#' candidate variables and all admissible split points, then selects the pair
#' with the largest concentration-index gain:
#' \deqn{(j^*, s^*) =
#' \arg\max_{j \in \mathcal{J}_t,\ s \in \mathcal{S}_{jt}}
#' G_m(t, j, s).}
#' The gain `G_m` is computed by [weighted_ci_gain()] from the selected
#' concentration-index impurity `m`, one of `"CI"`, `"CIg"`, or `"CIc"`.
#'
#' The fitted object uses [partykit::party()] for storage, traversal,
#' prediction, and plotting, but the tree-growing rule is the package's greedy
#' concentration-index rule rather than the conditional-inference test-based
#' rule used by [partykit::ctree()].
#'
#' Stopping rules operate in three places. First, a node is searched only when
#' it satisfies `minsplit` and has not reached `maxdepth`. Second, candidate
#' splits are admissible only when both child nodes satisfy `minbucket` and
#' `minprob`. Third, after all admissible splits are scored, the best split is
#' accepted only when its gain is finite and greater than `min_gain`.
#'
#' @param formula A model formula, typically with a two-column response such as
#'   `cbind(rank, outcome) ~ x1 + x2`.
#' @param data A data frame containing the variables in `formula`.
#' @param rank_name Name of the socioeconomic rank variable.
#' @param outcome_name Name of the outcome variable.
#' @param weights Optional non-negative numeric case weights.
#' @param type One of `"CI"`, `"CIg"`, or `"CIc"` selecting the concentration
#'   index variant used for split scoring.
#' @param control A control object created by [ci_tree_control()]. Objects from
#'   [partykit::ctree_control()] are also accepted for shared controls such as
#'   `minsplit`, `minbucket`, `minprob`, `maxdepth`, and `mtry`.
#' @param na.action A function for handling missing values.
#' @param ... Currently ignored; retained for backwards compatibility.
#'
#' @return A fitted `ci_tree` object inheriting from `constparty` and `party`.
#'
#' @references
#' Breiman L, Friedman JH, Olshen RA, Stone CJ (1984). *Classification and
#' Regression Trees*. Wadsworth.
#'
#' Hothorn T, Zeileis A (2015). "partykit: A Modular Toolkit for Recursive
#' Partytioning in R." *Journal of Machine Learning Research*, 16, 3905-3909.
#' https://jmlr.org/papers/v16/hothorn15a.html.
#'
#' Wagstaff A, van Doorslaer E, Watanabe N (2003). "On Decomposing the Causes
#' of Health Sector Inequalities with an Application to Malnutrition
#' Inequalities in Vietnam." *Journal of Econometrics*, 112(1), 207-223.
#' doi:10.1016/S0304-4076(02)00161-6.
#'
#' @export
ci_tree <- function(formula,
                    data,
                    rank_name,
                    outcome_name,
                    weights = NULL,
                    type = c("CI", "CIg", "CIc"),
                    control = ci_tree_control(),
                    na.action = stats::na.omit,
                    ...) {
  type <- match.arg(type)
  call <- match.call()
  extra_args <- list(...)

  if (length(extra_args) > 0L) {
    warning("Additional arguments in `...` are ignored by greedy `ci_tree()`.",
      call. = FALSE
    )
  }

  ctrl <- .ci_tree_normalize_control(control)

  mf <- stats::model.frame(
    formula = formula,
    data = data,
    na.action = na.action,
    drop.unused.levels = FALSE
  )
  terms_object <- stats::terms(mf)

  if (!is.null(weights)) {
    if (any(weights < 0, na.rm = TRUE)) {
      stop("weights must be non-negative")
    }
    if (anyNA(weights)) {
      stop("weights must not contain missing values")
    }

    if (length(weights) == nrow(data)) {
      omitted <- attr(mf, "na.action")
      if (!is.null(omitted)) {
        weights <- weights[-as.integer(omitted)]
      }
    }
  } else {
    weights <- rep(1, nrow(mf))
  }

  if (length(weights) != nrow(mf)) {
    stop("weights must have the same length as the fitted model frame")
  }

  weights <- as.numeric(weights)
  if (!any(weights > 0, na.rm = TRUE)) {
    stop("at least one weight must be positive")
  }

  y_full <- .ci_tree_response(mf, rank_name, outcome_name)
  response_id <- attr(terms_object, "response")
  predictor_ids <- setdiff(seq_along(mf), response_id)

  if (!length(predictor_ids)) {
    stop("`formula` must contain at least one splitting variable.",
      call. = FALSE
    )
  }

  for (j in predictor_ids) {
    if (is.character(mf[[j]])) {
      mf[[j]] <- factor(mf[[j]])
    }
  }

  .fit_ci_tree_from_frame(
    mf = mf,
    y_full = y_full,
    weights = weights,
    terms_object = terms_object,
    predictor_ids = predictor_ids,
    ctrl = ctrl,
    type = type,
    rank_name = rank_name,
    outcome_name = outcome_name,
    call = call
  )
}

#' Compatibility alias for `ci_tree()`
#'
#' `ctree_ci()` is kept for existing code. New code should use [ci_tree()],
#' because the current tree-growing method is greedy concentration-index
#' splitting rather than conditional-inference splitting.
#'
#' @return A fitted `ci_tree` object inheriting from `constparty` and `party`.
#' @rdname ci_tree
#' @export
#' @examples
#' toy_data <- data.frame(
#'   rank = c(10, 20, 30, 40, 50, 60),
#'   outcome = c(1, 0, 1, 0, 1, 1),
#'   income = c(2, 4, 6, 8, 10, 12),
#'   group = factor(c("low", "low", "mid", "mid", "high", "high"))
#' )
#'
#' fit <- ci_tree(
#'   formula = cbind(rank, outcome) ~ income + group,
#'   data = toy_data,
#'   rank_name = "rank",
#'   outcome_name = "outcome",
#'   control = ci_tree_control(minsplit = 1, minbucket = 1, maxdepth = 1)
#' )
#'
#' inherits(fit, "party")
ctree_ci <- function(...) {
  ci_tree(...)
}
