# WARNING - Generated by {fusen} from dev/shap_decomposition.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute fractional ranks
#'
#' Convert a numeric ranking variable to fractional ranks in `(0, 1)` using
#' average ranks for ties. This is the standard rank definition used in
#' concentration-index calculations.
#'
#' @param x An atomic vector to rank.
#' @param ties_method Tie-handling method passed to `data.table::frankv()`.
#'   Only `"average"` is supported.
#' @param na_rm Logical scalar. If `TRUE`, missing values are dropped before
#'   ranking. If `FALSE`, missing values trigger an error.
#'
#' @return A numeric vector of fractional ranks with length equal to the number
#'   of retained observations.
#'
#' @export
#' @examples
#' fractional_rank(c(10, 20, 20, 40))
#' fractional_rank(c(1, NA, 3), na_rm = TRUE)
fractional_rank <- function(
    x,
    ties_method = "average",
    na_rm = FALSE) {
  .assert_data_table_available()
  .assert_scalar_flag(na_rm, "na_rm")

  if (!identical(ties_method, "average")) {
    stop(
      paste(
        "`ties_method` must be \"average\" to preserve the standard",
        "fractional-rank definition."
      ),
      call. = FALSE
    )
  }
  if (!is.atomic(x)) {
    stop("`x` must be an atomic vector.", call. = FALSE)
  }

  if (na_rm) {
    x <- x[!is.na(x)]
  } else if (anyNA(x)) {
    stop(
      paste(
        "`x` contains missing values.",
        "Set `na_rm = TRUE` to drop them."
      ),
      call. = FALSE
    )
  }

  n <- length(x)
  if (n == 0L) {
    stop("`x` must contain at least one non-missing value.", call. = FALSE)
  }

  (data.table::frankv(x, ties.method = ties_method) - 0.5) / n
}
