# WARNING - Generated by {fusen} from dev/ci_ranking.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fast concentration-index score for internal repeated scoring
#'
#' @description
#' Computes the same concentration-index variants as [ci_factory()], but avoids
#' constructing temporary data frames and avoids [stats::cov.wt()]. The weighted
#' covariance is the population-style descriptive covariance computed from
#' normalized weights.
#'
#' @param y A two-column numeric matrix with rank variable and outcome.
#' @param wt Non-negative case weights.
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"`.
#'
#' @return A single non-negative concentration-index score.
#'
#' @noRd
#' @examples
#' ci <- ci_factory("CI")
#' y <- cbind(c(10, 20, 30), c(1, 0, 1))
#' ci(y, c(1, 1, 2))
#' cig <- ci_factory("CIg")
#' cig(y, c(1, 1, 2))
#' cic <- ci_factory("CIc")
#' cic(y, c(1, 1, 2))
#' l_index <- ci_factory("L")
#' l_index(y, c(1, 1, 2))
.ci_fast_score <- function(y, wt, type) {
  ok <- stats::complete.cases(y) & !is.na(wt) & wt > 0
  if (!any(ok) || sum(ok) <= 1L) {
    return(0)
  }

  rank <- y[ok, 1]
  outcome <- y[ok, 2]
  wt <- wt[ok]

  total_wt <- sum(wt)
  if (!is.finite(total_wt) || total_wt <= 0) {
    return(0)
  }

  if (type == "L") {
    mu_s <- stats::weighted.mean(rank, wt)
    if (!is.finite(mu_s) || abs(mu_s) <= .Machine$double.eps) {
      return(0)
    }

    p <- wt / total_wt
    l_index <- sum(p * ((rank - mu_s) / mu_s) * outcome)
    if (!is.finite(l_index)) {
      return(0)
    }

    return(abs(l_index))
  }

  wt_norm <- wt / total_wt
  rank_w <- .rank_wt_retained(rank, wt)

  mean_rank <- sum(wt_norm * rank_w)
  mean_outcome <- sum(wt_norm * outcome)
  cov12 <- sum(wt_norm * (rank_w - mean_rank) *
    (outcome - mean_outcome))

  if (type == "CI") {
    if (!is.finite(mean_outcome) ||
        abs(mean_outcome) <= .Machine$double.eps) {
      return(0)
    }
    return(abs(2 * cov12 / mean_outcome))
  }

  if (type == "CIg") {
    return(abs(2 * cov12))
  }

  rng <- max(outcome, na.rm = TRUE) - min(outcome, na.rm = TRUE)
  if (!is.finite(rng) || rng <= .Machine$double.eps) {
    return(0)
  }

  4 * abs(2 * cov12) / rng
}

#' Track session-level CI warnings
#'
#' @noRd
.ci_warning_state <- new.env(parent = emptyenv())
.ci_warning_state$negative_l <- FALSE

#' Warn once when L is used with negative socioeconomic levels
#'
#' @param ses Numeric socioeconomic level variable.
#'
#' @return `TRUE` when a warning was issued, otherwise `FALSE`.
#'
#' @noRd
.ci_warn_negative_l_levels <- function(ses) {
  if (isTRUE(.ci_warning_state$negative_l)) {
    return(FALSE)
  }

  if (!any(is.finite(ses) & ses < 0, na.rm = TRUE)) {
    return(FALSE)
  }

  warning(
    paste(
      '`type = "L"` uses observed socioeconomic levels rather than',
      "fractional ranks. The first response column contains negative values;",
      "the Erreygers-Kessels level-dependent index is intended for meaningful",
      "ratio-scale socioeconomic levels such as income, consumption, or",
      "expenditure. Centered wealth-index scores with negative values may be",
      "inappropriate for this criterion. See",
      "https://doi.org/10.3390/ijerph14070673.",
      "This warning is shown once per R session."
    ),
    call. = FALSE
  )
  .ci_warning_state$negative_l <- TRUE
  TRUE
}

#' Create concentration-index scoring functions
#'
#' Build a function that computes a weighted concentration-index criterion from
#' a two-column response matrix. The first column is treated as the
#' socioeconomic ranking variable and the second as the health outcome.
#'
#' This factory is intended for inequality-aware split scoring, where different
#' concentration-index variants can be swapped in while keeping a common
#' `function(y, wt)` interface.
#'
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"`. `"L"` selects the
#'   Erreygers-Kessels level-dependent bivariate index. For `"L"`, the first
#'   response column is used as a socioeconomic level variable, not converted
#'   to ranks.
#'
#' @return A function with signature `function(y, wt)` where `y` is a two-column
#'   numeric matrix and `wt` is a vector of positive case weights. The returned
#'   function drops incomplete rows and non-positive weights, then returns a
#'   single non-negative concentration-index value. It returns `0` when fewer
#'   than two valid observations remain or when the required denominator is
#'   degenerate.
#'
#' @details `"CI"`, `"CIg"`, and `"CIc"` are rank-dependent indices. For these
#'   scores, the returned function first converts `y[, 1]` to weighted
#'   fractional ranks using [rank_wt()]. It then computes the weighted
#'   covariance between rank and outcome and maps it to the requested index:
#'   `"CI"` divides by the weighted mean of the outcome, `"CIg"` returns the
#'   generalized form, and `"CIc"` applies an Erreygers-style range correction.
#'   Absolute values are returned.
#'
#'   `"L"` is level-dependent. It uses the observed socioeconomic levels in
#'   `y[, 1]` directly, together with the health outcome in `y[, 2]`:
#'   \deqn{L = \sum_i p_i \left(\frac{s_i - \mu_s}{\mu_s}\right)y_i}
#'   where `p_i = w_i / sum_i w_i` and `mu_s = sum_i p_i s_i`. The returned
#'   value is `abs(L)`.
#'
#'   Methodological warning: `"L"` requires the first response column to be a
#'   meaningful socioeconomic level variable, ideally income, consumption,
#'   expenditure, or another non-negative ratio-scale SES measure. It should
#'   not be used naively with a centered PCA wealth-index score whose mean may
#'   be close to zero or whose level scale has no direct interpretation. If
#'   using DHS wealth scores, treat `"L"` as a sensitivity analysis unless a
#'   defensible level interpretation exists.
#'
#'   In mathematical notation, for weighted fractional rank `R`, outcome `Y`,
#'   weighted outcome mean `mu`, and weighted covariance `cov_w`, the three
#'   implemented scores are:
#'   \deqn{CI = \left|2 cov_w(R, Y) / \mu\right|}
#'   \deqn{CIg = \left|2 cov_w(R, Y)\right|}
#'   \deqn{CIc = 4\left|2 cov_w(R, Y)\right| / (max(Y) - min(Y))}
#'
#'   These scores are used as non-negative within-node inequality impurities in
#'   the greedy tree and forest. A value closer to zero means less
#'   socioeconomic-related inequality in the outcome within that node.
#'
#' @references
#' Wagstaff A, van Doorslaer E, Watanabe N (2003). "On Decomposing the Causes
#' of Health Sector Inequalities with an Application to Malnutrition
#' Inequalities in Vietnam." *Journal of Econometrics*, 112(1), 207-223.
#' doi:10.1016/S0304-4076(02)00161-6.
#'
#' Wagstaff A (2011). "The concentration index of a binary outcome revisited."
#' *Health Economics*, 20(10), 1155-1160. doi:10.1002/hec.1752.
#'
#' Erreygers G (2009). "Correcting the concentration index." *Journal of Health
#' Economics*, 28(2), 504-515. doi:10.1016/j.jhealeco.2008.02.003.
#'
#' Erreygers G, Kessels R (2017). "Regression-Based Decompositions of Rank-
#' Dependent Indicators of Socioeconomic Inequality of Health." *International
#' Journal of Environmental Research and Public Health*, 14(7), 673.
#' doi:10.3390/ijerph14070673.
#' @export 

ci_factory <- function(type = c("CI", "CIg", "CIc", "L")) {
  type <- match.arg(type)

  function(y, wt) {
    stopifnot(is.matrix(y), ncol(y) == 2L, length(wt) == nrow(y))
    if (type == "L") {
      .ci_warn_negative_l_levels(y[, 1])
    }
    .ci_fast_score(y = y, wt = wt, type = type)
  }
}

#' Compute weighted midpoint ranks from retained observations
#'
#' @param x A numeric vector without missing values.
#' @param wt A positive numeric weight vector with the same length as `x`.
#'
#' @return Weighted fractional ranks in the original order of `x`.
#'
#' @noRd
#' @examples
#' rank_wt(c(10, 20, 30), c(1, 1, 2))
#' rank_wt(c(1, 2, NA, 3), c(1, 0, 1, 2))
.rank_wt_retained <- function(x, wt) {
  n <- length(x)
  if (!n) {
    return(numeric(0))
  }

  o <- order(x)
  x_ord <- x[o]
  wt_ord <- wt[o] / sum(wt)

  tie_blocks <- rle(x_ord)
  block_end <- cumsum(tie_blocks$lengths)
  block_start <- block_end - tie_blocks$lengths + 1L
  cumulative_wt <- c(0, cumsum(wt_ord))
  block_wt <- cumulative_wt[block_end + 1L] -
    cumulative_wt[block_start]
  rank_ord <- rep(
    cumulative_wt[block_start] + block_wt / 2,
    tie_blocks$lengths
  )

  out <- numeric(n)
  out[o] <- rank_ord
  out
}

#' Compute weighted fractional ranks
#'
#' Compute midpoint fractional ranks after sorting `x` in ascending order and
#' normalizing positive weights to sum to one. Observations with the same `x`
#' value share the weighted midpoint rank of their combined tied block.
#'
#' Observations with missing `x`, missing `wt`, or non-positive `wt` are
#' removed before ranking. The resulting ranks are useful as a low-level
#' building block for concentration-index calculations and related inequality
#' measures.
#'
#' @param x A numeric vector to rank.
#' @param wt A numeric vector of case weights with the same length as `x`.
#'
#' @return A numeric vector of weighted fractional ranks in `(0, 1)`, one for
#'   each retained observation. The output is ordered like the retained inputs
#'   after removing cases with missing `x`, missing `wt`, or `wt <= 0`.
#'
#' @export
rank_wt <- function(x, wt) {
  stopifnot(length(x) == length(wt))
  ok <- !is.na(x) & !is.na(wt) & wt > 0
  x <- x[ok]
  wt <- wt[ok]

  if (!length(x)) {
    return(numeric(0))
  }

  .rank_wt_retained(x, wt)
}

#' Compute weighted concentration-index gain from a cached parent impurity
#'
#' @description
#' Internal helper used by split-search routines after the parent node
#' concentration index has already been computed. This avoids recomputing the
#' parent impurity for every candidate split in the same node.
#'
#' @param y A matrix with two columns: SES rank variable and health outcome.
#' @param wt A numeric vector of weights.
#' @param left A logical vector indicating the left split.
#' @param ci_fun A function to compute the concentration index.
#' @param ci_parent Precomputed concentration index for the parent node.
#'
#' @return The weighted concentration-index gain.
#'
#' @noRd
#' @examples
#' y <- cbind(
#'   ses = c(10, 20, 30, 40, 50, 60),
#'   health = c(1, 0, 1, 0, 1, 1)
#' )
#' wt <- rep(1, 6)
#'
#' # A candidate split evaluated outside any tree-fitting routine
#' left <- c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
#'
#' weighted_ci_gain(y, wt, left, ci_factory("CI"))
.weighted_ci_gain_from_parent <- function(y, wt, left, ci_fun, ci_parent) {
  stopifnot(length(left) == nrow(y), length(wt) == nrow(y))

  wl <- sum(wt[left], na.rm = TRUE)
  wr <- sum(wt[!left], na.rm = TRUE)
  wtot <- wl + wr

  if (wl <= 0 || wr <= 0 || wtot <= 0) return(-Inf)

  ci_left <- ci_fun(y[left,  , drop = FALSE], wt[left])
  ci_right <- ci_fun(y[!left, , drop = FALSE], wt[!left])

  ci_parent - ((wl / wtot) * ci_left + (wr / wtot) * ci_right)
}

#' Compute weighted concentration-index gain for a binary split
#'
#' Compute the reduction in concentration-index impurity obtained by splitting
#' a parent node into left and right child nodes. The gain is the parent node's
#' concentration-index score minus the weighted average of the two child-node
#' scores.
#'
#' @param y A matrix with two columns: SES rank variable and health outcome.
#' @param wt A numeric vector of weights.
#' @param left A logical vector indicating the left split.
#' @param ci_fun A function to compute the concentration index.
#' @return The weighted concentration-index gain.
#'
#' @details For concentration-index impurity `I_m(.)` based on index variant
#'   `m`, parent node `t`, and a candidate split creating left and right child
#'   nodes `t_L` and `t_R`, the gain is
#'   \deqn{G_m(t, j, s) =
#'   I_m(t) - \frac{W_L}{W_t} I_m(t_L) -
#'   \frac{W_R}{W_t} I_m(t_R)}
#'   where `W_t`, `W_L`, and `W_R` are the total case weights in the parent,
#'   left child, and right child. Positive gain means the split reduces the
#'   weighted within-node concentration-index impurity.
#'
#'   In the greedy tree builder, the selected split at node `t` is the
#'   admissible variable-split pair with the largest gain:
#'   \deqn{(j^*, s^*) =
#'   \arg\max_{j \in \mathcal{J}_t,\ s \in \mathcal{S}_{jt}}
#'   G_m(t, j, s).}
#'
#' @references
#' Breiman L, Friedman JH, Olshen RA, Stone CJ (1984). *Classification and
#' Regression Trees*. Wadsworth.
#'
#' Wagstaff A, van Doorslaer E, Watanabe N (2003). "On Decomposing the Causes
#' of Health Sector Inequalities with an Application to Malnutrition
#' Inequalities in Vietnam." *Journal of Econometrics*, 112(1), 207-223.
#' doi:10.1016/S0304-4076(02)00161-6.
#' @export
weighted_ci_gain <- function(y, wt, left, ci_fun) {
  stopifnot(length(left) == nrow(y), length(wt) == nrow(y))

  ci_parent <- ci_fun(y, wt)
  .weighted_ci_gain_from_parent(
    y = y,
    wt = wt,
    left = left,
    ci_fun = ci_fun,
    ci_parent = ci_parent
  )
}

#' Compute gain relative to the parent-node impurity
#'
#' @param gain Raw impurity reduction.
#' @param parent_impurity Impurity of the node being split.
#' @param tolerance Numeric zero guard for the parent-node impurity.
#'
#' @return A scalar ratio, or `NA_real_` when the denominator is degenerate.
#'
#' @noRd
.ci_relative_gain <- function(gain,
                              parent_impurity,
                              tolerance = .Machine$double.eps) {
  if (!is.finite(gain) ||
      !is.finite(parent_impurity) ||
      abs(parent_impurity) <= tolerance) {
    return(NA_real_)
  }

  gain / abs(parent_impurity)
}
