# WARNING - Generated by {fusen} from dev/ci_ranking.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create concentration-index scoring functions
#'
#' Build a function that computes a weighted concentration-index criterion from
#' a two-column response matrix. The first column is treated as the
#' socioeconomic ranking variable and the second as the health outcome.
#'
#' This factory is intended for inequality-aware split scoring, where different
#' concentration-index variants can be swapped in while keeping a common
#' `function(y, wt)` interface.
#'
#' @param type One of `"CI"`, `"CIg"`, or `"CIc"` selecting the standard,
#'   generalized, or corrected concentration index.
#'
#' @return A function with signature `function(y, wt)` where `y` is a two-column
#'   numeric matrix and `wt` is a vector of positive case weights. The returned
#'   function drops incomplete rows and non-positive weights, then returns a
#'   single non-negative concentration-index value. It returns `0` when fewer
#'   than two valid observations remain or when the required denominator is
#'   degenerate.
#'
#' @details The returned function first converts `y[, 1]` to weighted
#'   fractional ranks using [rank_wt()]. It then computes the weighted
#'   covariance between rank and outcome and maps it to the requested index:
#'   `"CI"` divides by the weighted mean of the outcome, `"CIg"` returns the
#'   generalized form, and `"CIc"` applies an Erreygers-style range correction.
#'   Absolute values are returned.
#' @export 
#' @examples
#' ci <- ci_factory("CI")
#' y <- cbind(c(10, 20, 30), c(1, 0, 1))
#' ci(y, c(1, 1, 2))
#' cig <- ci_factory("CIg")
#' cig(y, c(1, 1, 2))
#' cic <- ci_factory("CIc")
#' cic(y, c(1, 1, 2))

ci_factory <- function(type = c("CI", "CIg", "CIc")) {
  type <- match.arg(type)

  function(y, wt) {
    stopifnot(is.matrix(y), ncol(y) == 2L, length(wt) == nrow(y))

    ok <- stats::complete.cases(y) & !is.na(wt) & wt > 0
    y <- y[ok, , drop = FALSE]
    wt <- wt[ok]

    if (nrow(y) <= 1L) {
      return(0)
    }

    # column 1 = SES rank variable, column 2 = health outcome
    y[, 1] <- rank_wt(y[, 1], wt)

    cov12 <- stats::cov.wt(
      x = as.matrix(data.frame(y1 = y[, 1], y2 = y[, 2])),
      wt = wt
    )$cov[1, 2]

    if (type == "CI") {
      mu <- stats::weighted.mean(y[, 2], wt)
      if (isTRUE(all.equal(mu, 0))) {
        return(0)
      }
      return(abs(2 * cov12 / mu))
    }

    if (type == "CIg") {
      return(abs(2 * cov12))
    }

    # CIc = Erreygers-style corrected version
    rng <- max(y[, 2], na.rm = TRUE) - min(y[, 2], na.rm = TRUE)
    if (isTRUE(all.equal(rng, 0))) {
      return(0)
    }
    4 * abs(2 * cov12) / rng
  }
}

#' Compute weighted fractional ranks
#'
#' Compute midpoint fractional ranks after sorting `x` in ascending order and
#' normalizing positive weights to sum to one.
#'
#' Observations with missing `x`, missing `wt`, or non-positive `wt` are
#' removed before ranking. The resulting ranks are useful as a low-level
#' building block for concentration-index calculations and related inequality
#' measures.
#'
#' @param x A numeric vector to rank.
#' @param wt A numeric vector of case weights with the same length as `x`.
#'
#' @return A numeric vector of weighted fractional ranks in `(0, 1)`, one for
#'   each retained observation. The output is ordered like the retained inputs
#'   after removing cases with missing `x`, missing `wt`, or `wt <= 0`.
#'
#' @export
#' @examples
#' rank_wt(c(10, 20, 30), c(1, 1, 2))
#' rank_wt(c(1, 2, NA, 3), c(1, 0, 1, 2))
rank_wt <- function(x, wt) {
  stopifnot(length(x) == length(wt))
  ok <- !is.na(x) & !is.na(wt) & wt > 0
  x <- x[ok]
  wt <- wt[ok]

  if (!length(x)) {
    return(numeric(0))
  }

  o <- order(x)
  x <- x[o]
  wt <- wt[o] / sum(wt)

  r <- numeric(length(x))
  if (length(x) == 1L) {
    r[1L] <- 0.5
  } else {
    r <- c(0, cumsum(wt[-length(wt)])) + wt / 2
  }

  out <- numeric(sum(ok))
  out[o] <- r
  out
}

#' Compute weighted concentration-index gain for a binary split
#' It computes the gain in concentration index from splitting 
#'  a node into left and right parts, weighted by the case weights. 
#'  The gain is calculated as the difference between the parent node's
#'  concentration index and the weighted average of the left and right 
#'  child nodes' concentration indices.
#' @param y A matrix with two columns: SES rank variable and health outcome.
#' @param wt A numeric vector of weights.
#' @param left A logical vector indicating the left split.
#' @param ci_fun A function to compute the concentration index.
#' @return The weighted concentration-index gain.
#' @export
#' @examples
#' y <- cbind(
#'   ses = c(10, 20, 30, 40, 50, 60),
#'   health = c(1, 0, 1, 0, 1, 1)
#' )
#' wt <- rep(1, 6)
#'
#' # A candidate split evaluated outside any tree-fitting routine
#' left <- c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
#'
#' weighted_ci_gain(y, wt, left, ci_factory("CI"))
weighted_ci_gain <- function(y, wt, left, ci_fun) {
  stopifnot(length(left) == nrow(y), length(wt) == nrow(y))

  wl <- sum(wt[left], na.rm = TRUE)
  wr <- sum(wt[!left], na.rm = TRUE)
  wtot <- wl + wr

  if (wl <= 0 || wr <= 0 || wtot <= 0) return(-Inf)

  ci_parent <- ci_fun(y, wt)
  ci_left   <- ci_fun(y[left,  , drop = FALSE], wt[left])
  ci_right  <- ci_fun(y[!left, , drop = FALSE], wt[!left])

  ci_parent - ((wl / wtot) * ci_left + (wr / wtot) * ci_right)
}
