# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ci_best_numeric_split_cpp_engine <- function(x, y, wt, minbucket, minprob, type) {
    .Call(`_ineqTrees_ci_best_numeric_split_cpp_engine`, x, y, wt, minbucket, minprob, type)
}

ci_best_factor_split_cpp_engine <- function(code, y, wt, n_levels, minbucket, minprob, type) {
    .Call(`_ineqTrees_ci_best_factor_split_cpp_engine`, code, y, wt, n_levels, minbucket, minprob, type)
}

ci_best_factor_split_cpp_engine_controlled <- function(code, y, wt, n_levels, minbucket, minprob, type, factor_split, max_factor_levels_partition, max_factor_partitions) {
    .Call(`_ineqTrees_ci_best_factor_split_cpp_engine_controlled`, code, y, wt, n_levels, minbucket, minprob, type, factor_split, max_factor_levels_partition, max_factor_partitions)
}

