# WARNING - Generated by {fusen} from dev/shap_decomposition.Rmd: do not edit by hand # nolint: line_length_linter.

#' Decompose a concentration index using SHAP values
#'
#' Compute SHAP-based feature contributions to the concentration index of a
#' predicted outcome. The SHAP table can be supplied either in wide format
#' (one row per observation, one column per feature) or in DALEX-like long
#' format and reshaped internally.
#'
#' @param shap A rectangular SHAP table. By default this should be a wide table
#'   with one numeric feature column per SHAP contributor. If `from_dalex =
#'   TRUE`, `shap` should instead be a long DALEX-like table containing
#'   observation IDs, feature names, and SHAP values.
#' @param rank A numeric vector giving the socioeconomic ranking variable for
#'   each observation.
#' @param prediction Optional numeric vector of model predictions. If omitted,
#'   predictions are reconstructed as `baseline + rowSums(shap)`.
#' @param baseline Optional scalar baseline prediction. Required when
#'   `prediction` is not supplied.
#' @param from_dalex Logical scalar. If `TRUE`, reshape a DALEX-like long SHAP
#'   table to wide format before decomposition.
#' @param dalex_id_col Optional column name identifying observations in the
#'   DALEX-like input.
#' @param dalex_variable_col Optional column name containing feature names in
#'   the DALEX-like input.
#' @param dalex_value_col Optional column name containing SHAP values in the
#'   DALEX-like input.
#' @param na_rm Logical scalar. If `TRUE`, drop rows with missing values in
#'   required inputs before computing the decomposition.
#' @param sort Logical scalar. If `TRUE`, order output features by decreasing
#'   absolute SHAP contribution.
#' @param tolerance Numeric tolerance used to detect numerically zero mean
#'   predictions or concentration indices.
#'
#' @return A list of class `"shap_ci_decomposition"` with two components:
#'   `diagnostics`, a one-row `data.table` of decomposition diagnostics, and
#'   `contributions`, a `data.table` containing one row per SHAP feature with
#'   columns `feature`, `D_k_SHAP`, `pct_contribution`, and
#'   `abs_contribution`.
#'
#' @details For each feature `k`, `D_k_SHAP` is computed as
#'   `2 / (n * mu_hat)` times the sum of `phi_ik * (R_i - 0.5)` across
#'   observations, where `phi_ik` is the SHAP value for feature `k`, `R_i` is
#'   the fractional rank of the socioeconomic ordering variable, and `mu_hat`
#'   is the mean predicted outcome.
#'
#' @export
#' @examples
#' shap <- data.frame(
#'   education = c(1, 0, -1),
#'   water = c(0, 1, 1)
#' )
#' rank <- c(1, 2, 3)
#'
#' res <- shap_conc_decomp(
#'   shap = shap,
#'   rank = rank,
#'   baseline = 2
#' )
#' res$diagnostics
#' res$contributions
#'
#' dalex_like <- data.frame(
#'   "_id_" = rep(1:3, each = 3),
#'   "_vname_" = rep(c("_baseline_", "education", "water"), times = 3),
#'   "_attribution_" = c(2, 1, 0, 2, 0, 1, 2, -1, 1),
#'   check.names = FALSE
#' )
#'
#' shap_conc_decomp(
#'   shap = dalex_like,
#'   rank = rank,
#'   baseline = 2,
#'   from_dalex = TRUE
#' )$contributions
shap_conc_decomp <- function(
    shap,
    rank,
    prediction = NULL,
    baseline = NULL,
    from_dalex = FALSE,
    dalex_id_col = NULL,
    dalex_variable_col = NULL,
    dalex_value_col = NULL,
    na_rm = FALSE,
    sort = TRUE,
    tolerance = sqrt(.Machine$double.eps)) {
  .assert_data_table_available()
  .assert_scalar_flag(from_dalex, "from_dalex")
  .assert_scalar_flag(na_rm, "na_rm")
  .assert_scalar_flag(sort, "sort")
  .assert_scalar_numeric(tolerance, "tolerance")

  if (isTRUE(from_dalex)) {
    shap <- .dalex_shap_to_wide(
      shap = shap,
      id_col = dalex_id_col,
      variable_col = dalex_variable_col,
      value_col = dalex_value_col
    )
  }

  shap_dt <- .prepare_named_shap_dt(shap, allow_missing = na_rm)
  n <- nrow(shap_dt)

  if (length(rank) != n) {
    stop("`rank` must have length equal to nrow(`shap`).", call. = FALSE)
  }
  if (!is.null(prediction) && length(prediction) != n) {
    stop("`prediction` must have length equal to nrow(`shap`).", call. = FALSE)
  }
  if (is.null(prediction)) {
    if (is.null(baseline)) {
      stop(
        "Supply either `prediction` or `baseline` so predictions can",
        " be identified.",
        call. = FALSE
      )
    }
    .assert_scalar_numeric(baseline, "baseline")
  } else if (!is.numeric(prediction)) {
    stop("`prediction` must be numeric.", call. = FALSE)
  } else if (anyNA(prediction) && !na_rm) {
    stop(
      "`prediction` contains missing values. Set `na_rm = TRUE` to drop ",
      "incomplete rows.",
      call. = FALSE
    )
  }

  if (anyNA(rank) && !na_rm) {
    stop(
      "`rank` contains missing values. Set `na_rm = TRUE` to drop ",
      "incomplete rows.",
      call. = FALSE
    )
  }

  working_dt <- data.table::copy(shap_dt)
  working_dt[["rank__"]] <- rank

  if (!is.null(prediction)) {
    working_dt[["prediction__"]] <- as.numeric(prediction)
  }

  if (na_rm) {
    required_cols <- c(
      names(shap_dt),
      "rank__",
      if (!is.null(prediction)) "prediction__"
    )
    keep <- stats::complete.cases(working_dt[, required_cols, with = FALSE])
    working_dt <- working_dt[keep, ]
  }

  if (nrow(working_dt) == 0L) {
    stop("No complete cases remain after applying `na_rm`.", call. = FALSE)
  }

  if (is.null(prediction)) {
    working_dt[["prediction__"]] <- rowSums(
      working_dt[, names(shap_dt), with = FALSE]
    ) + baseline
    prediction_source <- "baseline + rowSums(shap)"
  } else {
    prediction_source <- "prediction"
  }

  n_complete <- nrow(working_dt)
  rank_vector <- working_dt[["rank__"]]
  rank_fraction <- fractional_rank(
    rank_vector, ties_method = "average", na_rm = FALSE
  )
  centered_rank <- rank_fraction - 0.5
  prediction_vector <- working_dt[["prediction__"]]
  mu_hat <- mean(prediction_vector)

  if (abs(mu_hat) <= tolerance) {
    stop(
      paste(
        "The mean prediction is numerically zero, so the",
        "concentration index is undefined."
      ),
      call. = FALSE
    )
  }

  scale_factor <- 2 / (n_complete * mu_hat)

  contribution_wide <- data.table::as.data.table(
    as.list(vapply(
      names(shap_dt),
      function(col) scale_factor * sum(working_dt[[col]] * centered_rank),
      numeric(1L)
    ))
  )

  contributions <- data.table::melt(
    contribution_wide,
    measure.vars = names(contribution_wide),
    variable.name = "feature",
    value.name = "D_k_SHAP",
    variable.factor = FALSE
  )

  total_ci <- scale_factor * sum(prediction_vector * centered_rank)
  shap_total <- sum(contributions[["D_k_SHAP"]])

  contributions[["pct_contribution"]] <- if (abs(total_ci) <= tolerance) {
    rep(NA_real_, nrow(contributions))
  } else {
    100 * contributions[["D_k_SHAP"]] / total_ci
  }
  contributions[["abs_contribution"]] <- abs(contributions[["D_k_SHAP"]])

  if (sort) {
    data.table::setorderv(
      contributions,
      cols = c("abs_contribution", "feature"),
      order = c(-1L, 1L)
    )
  }

  diagnostics <- data.table::data.table(
    n = n_complete,
    mean_prediction = mu_hat,
    concentration_index = total_ci,
    shap_sum = shap_total,
    additivity_gap = total_ci - shap_total,
    centered_rank_sum = sum(centered_rank),
    prediction_source = prediction_source
  )

  structure(
    list(
      diagnostics = diagnostics,
      contributions = contributions[]
    ),
    class = "shap_ci_decomposition"
  )
}
