# WARNING - Generated by {fusen} from dev/shap_decomposition.Rmd: do not edit by hand # nolint: line_length_linter.

#' Decompose a concentration index using SHAP values
#'
#' Compute SHAP-based feature contributions to the concentration index of a
#' predicted outcome. The SHAP table can be supplied either in wide format
#' (one row per observation, one column per feature) or in DALEX-like long
#' format and reshaped internally.
#'
#' @param shap A rectangular SHAP table. By default this should be a wide table
#'   with one numeric feature column per SHAP contributor. If `from_dalex =
#'   TRUE`, `shap` should instead be a long DALEX-like table containing
#'   observation IDs, feature names, and SHAP values.
#' @param rank A numeric vector giving the socioeconomic ranking variable for
#'   each observation. When `type = "L"`, this is interpreted as the observed
#'   socioeconomic level variable.
#' @param type One of `"CI"`, `"CIg"`, `"CIc"`, or `"L"` selecting the
#'   decomposition target. The first three are rank-dependent concentration
#'   indices scored consistently with [ci_factory()]. `"L"` uses the
#'   Erreygers--Kessels level-dependent bivariate index based on observed
#'   socioeconomic levels.
#' @param prediction Optional numeric vector of model predictions. If omitted,
#'   predictions are reconstructed as `baseline + rowSums(shap)`.
#' @param baseline Optional scalar baseline prediction. Required when
#'   `prediction` is not supplied.
#' @param weights Optional numeric vector of non-negative case weights. If
#'   omitted, equal weights are used. Observations with non-positive weights do
#'   not contribute to the decomposition.
#' @param from_dalex Logical scalar. If `TRUE`, reshape a DALEX-like long SHAP
#'   table to wide format before decomposition.
#' @param dalex_id_col Optional column name identifying observations in the
#'   DALEX-like input.
#' @param dalex_variable_col Optional column name containing feature names in
#'   the DALEX-like input.
#' @param dalex_value_col Optional column name containing SHAP values in the
#'   DALEX-like input.
#' @param na_rm Logical scalar. If `TRUE`, drop rows with missing values in
#'   required inputs before computing the decomposition.
#' @param sort Logical scalar. If `TRUE`, order output features by decreasing
#'   absolute SHAP contribution.
#' @param tolerance Numeric tolerance used to detect numerically zero mean
#'   predictions or concentration indices.
#'
#' @return A list of class `"shap_ci_decomposition"` with two components:
#'   `diagnostics`, a one-row `data.table` of decomposition diagnostics, and
#'   `contributions`, a `data.table` containing one row per SHAP feature with
#'   columns `feature`, `D_k_SHAP`, `pct_contribution`, and
#'   `abs_contribution`.
#'
#' @details The total `concentration_index` reported in `diagnostics` is the
#'   non-negative score returned by `ci_factory(type)`. Feature contributions
#'   are computed on the signed linear scale for the selected index and then
#'   oriented so they sum to the non-negative factory score when the SHAP values
#'   reconstruct the prediction.
#'
#'   For rank-dependent types, weighted fractional ranks and the same unbiased
#'   weighted covariance convention used by [ci_factory()] are used. `"CI"`
#'   divides feature covariances by the weighted mean prediction, `"CIg"` uses
#'   the generalized covariance form, and `"CIc"` applies the prediction-range
#'   correction.
#'
#'   For `type = "L"`, `rank` is treated as an observed socioeconomic level
#'   `s_i`. The decomposition uses the weighted mean of
#'   `((s_i - mu_s) / mu_s) * phi_ik` for each feature, where `mu_s` is the
#'   weighted mean socioeconomic level.
#'
#' @export
#' @examples
#' shap <- data.frame(
#'   education = c(1, 0, -1),
#'   water = c(0, 1, 1)
#' )
#' rank <- c(1, 2, 3)
#'
#' res <- shap_conc_decomp(
#'   shap = shap,
#'   rank = rank,
#'   baseline = 2
#' )
#' res$diagnostics
#' res$contributions
#'
#' dalex_like <- data.frame(
#'   "_id_" = rep(1:3, each = 3),
#'   "_vname_" = rep(c("_baseline_", "education", "water"), times = 3),
#'   "_attribution_" = c(2, 1, 0, 2, 0, 1, 2, -1, 1),
#'   check.names = FALSE
#' )
#'
#' shap_conc_decomp(
#'   shap = dalex_like,
#'   rank = rank,
#'   baseline = 2,
#'   from_dalex = TRUE
#' )$contributions
shap_conc_decomp <- function(
    shap,
    rank,
    type = c("CI", "CIg", "CIc", "L"),
    prediction = NULL,
    baseline = NULL,
    weights = NULL,
    from_dalex = FALSE,
    dalex_id_col = NULL,
    dalex_variable_col = NULL,
    dalex_value_col = NULL,
    na_rm = FALSE,
    sort = TRUE,
    tolerance = sqrt(.Machine$double.eps)) {
  .assert_data_table_available()
  .assert_scalar_flag(from_dalex, "from_dalex")
  .assert_scalar_flag(na_rm, "na_rm")
  .assert_scalar_flag(sort, "sort")
  .assert_scalar_numeric(tolerance, "tolerance")
  type <- match.arg(type)

  if (isTRUE(from_dalex)) {
    shap <- .dalex_shap_to_wide(
      shap = shap,
      id_col = dalex_id_col,
      variable_col = dalex_variable_col,
      value_col = dalex_value_col
    )
  }

  shap_dt <- .prepare_named_shap_dt(shap, allow_missing = na_rm)
  n <- nrow(shap_dt)

  if (length(rank) != n) {
    stop("`rank` must have length equal to nrow(`shap`).", call. = FALSE)
  }
  if (!is.null(prediction) && length(prediction) != n) {
    stop("`prediction` must have length equal to nrow(`shap`).", call. = FALSE)
  }
  if (is.null(weights)) {
    weights <- rep.int(1, n)
  } else if (!is.numeric(weights) || length(weights) != n) {
    stop("`weights` must be numeric with length equal to nrow(`shap`).",
      call. = FALSE
    )
  } else if (any(!is.finite(weights) & !is.na(weights))) {
    stop("`weights` must contain only finite values or NA.", call. = FALSE)
  } else if (anyNA(weights) && !na_rm) {
    stop(
      "`weights` contains missing values. Set `na_rm = TRUE` to drop ",
      "incomplete rows.",
      call. = FALSE
    )
  }
  if (is.null(prediction)) {
    if (is.null(baseline)) {
      stop(
        "Supply either `prediction` or `baseline` so predictions can",
        " be identified.",
        call. = FALSE
      )
    }
    .assert_scalar_numeric(baseline, "baseline")
  } else if (!is.numeric(prediction)) {
    stop("`prediction` must be numeric.", call. = FALSE)
  } else if (anyNA(prediction) && !na_rm) {
    stop(
      "`prediction` contains missing values. Set `na_rm = TRUE` to drop ",
      "incomplete rows.",
      call. = FALSE
    )
  }

  if (anyNA(rank) && !na_rm) {
    stop(
      "`rank` contains missing values. Set `na_rm = TRUE` to drop ",
      "incomplete rows.",
      call. = FALSE
    )
  }

  working_dt <- data.table::copy(shap_dt)
  working_dt[["rank__"]] <- rank
  working_dt[["weights__"]] <- as.numeric(weights)

  if (!is.null(prediction)) {
    working_dt[["prediction__"]] <- as.numeric(prediction)
  }

  if (na_rm) {
    required_cols <- c(
      names(shap_dt),
      "rank__",
      "weights__",
      if (!is.null(prediction)) "prediction__"
    )
    keep <- stats::complete.cases(working_dt[, required_cols, with = FALSE])
    working_dt <- working_dt[keep, ]
  }

  if (nrow(working_dt) == 0L) {
    stop("No complete cases remain after applying `na_rm`.", call. = FALSE)
  }

  working_dt <- working_dt[working_dt[["weights__"]] > 0, ]

  if (nrow(working_dt) == 0L) {
    stop("No positive-weight complete cases remain.", call. = FALSE)
  }

  if (is.null(prediction)) {
    working_dt[["prediction__"]] <- rowSums(
      working_dt[, names(shap_dt), with = FALSE]
    ) + baseline
    prediction_source <- "baseline + rowSums(shap)"
  } else {
    prediction_source <- "prediction"
  }

  n_complete <- nrow(working_dt)
  rank_vector <- working_dt[["rank__"]]
  prediction_vector <- working_dt[["prediction__"]]
  weight_vector <- working_dt[["weights__"]]
  weight_sum <- sum(weight_vector)
  weight_prob <- weight_vector / weight_sum
  mu_hat <- stats::weighted.mean(prediction_vector, weight_vector)

  if (type %in% c("CI", "CIg", "CIc")) {
    rank_fraction <- rank_wt(rank_vector, weight_vector)
    mean_rank <- sum(weight_prob * rank_fraction)
    index_weight <- rank_fraction - mean_rank
    cov_denom <- 1 - sum(weight_prob^2)

    weighted_cov_with_rank <- function(values) {
      if (!is.finite(cov_denom) || cov_denom <= tolerance) {
        return(0)
      }
      mean_value <- sum(weight_prob * values)
      sum(weight_prob * index_weight * (values - mean_value)) / cov_denom
    }

    if (type == "CI" && abs(mu_hat) <= tolerance) {
      stop(
        paste(
          "The mean prediction is numerically zero, so the",
          "concentration index is undefined."
        ),
        call. = FALSE
      )
    }

    prediction_range <- diff(range(prediction_vector))
    if (type == "CIc" &&
        (!is.finite(prediction_range) || prediction_range <= tolerance)) {
      stop(
        paste(
          "The prediction range is numerically zero, so the",
          "corrected concentration index is undefined."
        ),
        call. = FALSE
      )
    }

    scale_factor <- switch(type,
      CI = 2 / mu_hat,
      CIg = 2,
      CIc = 8 / prediction_range
    )
    contribution_score <- function(values) {
      scale_factor * weighted_cov_with_rank(values)
    }
    signed_total_ci <- contribution_score(prediction_vector)
  } else {
    mu_s <- stats::weighted.mean(rank_vector, weight_vector)
    if (!is.finite(mu_s) || abs(mu_s) <= tolerance) {
      stop(
        paste(
          "The mean socioeconomic level is numerically zero, so the",
          "level-dependent index is undefined."
        ),
        call. = FALSE
      )
    }

    index_weight <- (rank_vector - mu_s) / mu_s
    contribution_score <- function(values) {
      sum(weight_prob * index_weight * values)
    }
    signed_total_ci <- contribution_score(prediction_vector)
  }

  ci_fun <- ci_factory(type)
  ci_score <- ci_fun(cbind(rank = rank_vector, outcome = prediction_vector),
    weight_vector
  )

  score_direction <- if (signed_total_ci < 0) -1 else 1
  contribution_wide <- data.table::as.data.table(
    as.list(vapply(
      names(shap_dt),
      function(col) score_direction * contribution_score(working_dt[[col]]),
      numeric(1L)
    ))
  )

  contributions <- data.table::melt(
    contribution_wide,
    measure.vars = names(contribution_wide),
    variable.name = "feature",
    value.name = "D_k_SHAP",
    variable.factor = FALSE
  )

  shap_total <- sum(contributions[["D_k_SHAP"]])

  contributions[["pct_contribution"]] <- if (abs(ci_score) <= tolerance) {
    rep(NA_real_, nrow(contributions))
  } else {
    100 * contributions[["D_k_SHAP"]] / ci_score
  }
  contributions[["abs_contribution"]] <- abs(contributions[["D_k_SHAP"]])

  if (sort) {
    data.table::setorderv(
      contributions,
      cols = c("abs_contribution", "feature"),
      order = c(-1L, 1L)
    )
  }

  diagnostics <- data.table::data.table(
    n = n_complete,
    weight_sum = weight_sum,
    type = type,
    mean_prediction = mu_hat,
    concentration_index = ci_score,
    signed_concentration_index = signed_total_ci,
    score_direction = score_direction,
    shap_sum = shap_total,
    additivity_gap = ci_score - shap_total,
    centered_rank_sum = sum(weight_prob * index_weight),
    prediction_source = prediction_source
  )

  structure(
    list(
      diagnostics = diagnostics,
      contributions = contributions[]
    ),
    class = "shap_ci_decomposition"
  )
}
