# WARNING - Generated by {fusen} from dev/model_selection.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compatibility alias for `tune_ci_tree()`
#'
#' @return A `ci_tree_tuning` object.
#' @rdname tune_ci_tree
#' @export
tune_ctree_ci <- function(...) {
  tune_ci_tree(...)
}

#' Evaluate one forest tuning task
#'
#' @noRd
.ci_tune_forest_task <- function(task,
                                 formula,
                                 data,
                                 rank_name,
                                 outcome_name,
                                 weights,
                                 outcome,
                                 metrics,
                                 tuning_grid,
                                 root_table,
                                 surrogate_control,
                                 prediction_name,
                                 ntree,
                                 perturb,
                                 parallel_over,
                                 forest_future.seed,
                                 na.action,
                                 control,
                                 extra_args = list()) {
  g <- task$grid_id
  grid_row <- task$grid_row
  tree_control <- .ci_control_from_grid_row(grid_row)
  surr_control <- .ci_surrogate_control(tree_control, surrogate_control)
  this_ntree <- .ci_forest_ntree_from_row(grid_row, ntree)
  this_type <- as.character(grid_row$type[1L])
  fold <- task$resample$fold_id
  train_idx <- task$resample$train_idx
  test_idx <- task$resample$test_idx
  notes <- list()

  fit_result <- .ci_capture({
    if (!is.null(task$seed)) {
      set.seed(task$seed)
    }
    forest <- do.call(
      ci_forest,
      c(
        list(
          formula = formula,
          data = data[train_idx, , drop = FALSE],
          rank_name = rank_name,
          outcome_name = outcome_name,
          weights = weights[train_idx],
          type = this_type,
          control = tree_control,
          ntree = this_ntree,
          perturb = perturb,
          parallel = identical(parallel_over, "forest"),
          future.seed = forest_future.seed,
          na.action = na.action
        ),
        extra_args
      )
    )
    surrogate <- .ci_fit_forest_surrogate(
      forest = forest,
      data = data[train_idx, , drop = FALSE],
      formula = formula,
      rank_name = rank_name,
      prediction_name = prediction_name,
      weights = weights[train_idx],
      type = this_type,
      control = surr_control,
      na.action = na.action
    )
    list(forest = forest, surrogate = surrogate)
  })

  notes[[length(notes) + 1L]] <- .ci_notes_dt(
    g, fold, this_type, stage = "fit", messages = fit_result$warnings
  )
  if (!isTRUE(fit_result$ok)) {
    notes[[length(notes) + 1L]] <- .ci_notes_dt(
      g, fold, this_type, stage = "fit", messages = fit_result$error, class = "error"
    )
  }

  score_rows <- vector("list", length(metrics))
  prediction_rows <- data.table::data.table()
  extract_rows <- data.table::data.table()
  fit_rows <- data.table::data.table()
  pred <- NULL
  valid_data <- data[test_idx, , drop = FALSE]
  n_terminal <- NA_real_
  train_gain <- NA_real_
  fold_validation_gain <- NA_real_
  train_relative_gain <- NA_real_
  fold_validation_relative_gain <- NA_real_
  relative_generalization_gap <- NA_real_
  train_root_impurity <- NA_real_
  validation_root_impurity <- NA_real_

  if (isTRUE(fit_result$ok)) {
    pred_result <- .ci_capture({
      stats::predict(fit_result$value$forest, newdata = valid_data, OOB = FALSE)
    })
    notes[[length(notes) + 1L]] <- .ci_notes_dt(
      g, fold, this_type, stage = "predict", messages = pred_result$warnings
    )
    if (isTRUE(pred_result$ok)) {
      pred <- as.numeric(pred_result$value)
      valid_data[[prediction_name]] <- pred
      if (isTRUE(control$save_pred)) {
        prediction_rows <- data.table::data.table(
          grid_id = g,
          fold_id = fold,
          type = this_type,
          row_id = test_idx,
          outcome = outcome[test_idx],
          weight = weights[test_idx],
          .pred = pred
        )
      }
    } else {
      notes[[length(notes) + 1L]] <- .ci_notes_dt(
        g, fold, this_type, stage = "predict", messages = pred_result$error,
        class = "error"
      )
    }

    n_terminal <- .ci_forest_mean_terminal_nodes(fit_result$value$forest)

    diagnostic_result <- .ci_capture({
      train_data <- data[train_idx, , drop = FALSE]
      train_root_impurity <- .ci_data_root_impurity(
        data = train_data,
        weights = weights[train_idx],
        rank_name = rank_name,
        outcome_name = outcome_name,
        type = this_type
      )
      validation_root_impurity <- .ci_lookup_root_impurity(
        root_table,
        fold,
        this_type
      )
      if (is.null(validation_root_impurity)) {
        validation_root_impurity <- .ci_data_root_impurity(
          data = valid_data,
          weights = weights[test_idx],
          rank_name = rank_name,
          outcome_name = outcome_name,
          type = this_type
        )
      }

      train_gain <- .ci_score_forest_validation_gain(
        fit = fit_result$value$forest,
        new_data = train_data,
        rank_name = rank_name,
        outcome_name = outcome_name,
        weights = weights[train_idx],
        type = this_type,
        root_impurity = train_root_impurity
      )
      train_relative_gain <- .ci_score_forest_relative_validation_gain(
        fit = fit_result$value$forest,
        new_data = train_data,
        rank_name = rank_name,
        outcome_name = outcome_name,
        weights = weights[train_idx],
        type = this_type,
        root_impurity = train_root_impurity
      )

      fold_validation_gain <- .ci_score_forest_validation_gain(
        fit = fit_result$value$forest,
        new_data = valid_data,
        rank_name = rank_name,
        outcome_name = outcome_name,
        weights = weights[test_idx],
        type = this_type,
        root_impurity = validation_root_impurity
      )
      fold_validation_relative_gain <- .ci_score_forest_relative_validation_gain(
        fit = fit_result$value$forest,
        new_data = valid_data,
        rank_name = rank_name,
        outcome_name = outcome_name,
        weights = weights[test_idx],
        type = this_type,
        root_impurity = validation_root_impurity
      )

      list(
        train_gain = train_gain,
        fold_validation_gain = fold_validation_gain,
        train_relative_gain = train_relative_gain,
        fold_validation_relative_gain = fold_validation_relative_gain,
        relative_generalization_gap =
          train_relative_gain - fold_validation_relative_gain,
        train_root_impurity = train_root_impurity,
        validation_root_impurity = validation_root_impurity
      )
    })
    notes[[length(notes) + 1L]] <- .ci_notes_dt(
      g, fold, this_type, stage = "diagnostic",
      messages = diagnostic_result$warnings
    )
    if (isTRUE(diagnostic_result$ok)) {
      train_gain <- diagnostic_result$value$train_gain
      fold_validation_gain <- diagnostic_result$value$fold_validation_gain
      train_relative_gain <- diagnostic_result$value$train_relative_gain
      fold_validation_relative_gain <-
        diagnostic_result$value$fold_validation_relative_gain
      relative_generalization_gap <-
        diagnostic_result$value$relative_generalization_gap
      train_root_impurity <- diagnostic_result$value$train_root_impurity
      validation_root_impurity <- diagnostic_result$value$validation_root_impurity
    } else {
      notes[[length(notes) + 1L]] <- .ci_notes_dt(
        g, fold, this_type, stage = "diagnostic",
        messages = diagnostic_result$error, class = "error"
      )
    }

    if (!is.null(control$extract)) {
      extract_result <- .ci_capture(control$extract(fit_result$value))
      notes[[length(notes) + 1L]] <- .ci_notes_dt(
        g, fold, this_type, stage = "extract", messages = extract_result$warnings
      )
      if (isTRUE(extract_result$ok)) {
        extract_rows <- data.table::data.table(
          grid_id = g,
          fold_id = fold,
          type = this_type,
          .extracts = list(extract_result$value)
        )
      } else {
        notes[[length(notes) + 1L]] <- .ci_notes_dt(
          g, fold, this_type, stage = "extract", messages = extract_result$error,
          class = "error"
        )
      }
    }

    if (isTRUE(control$save_fit)) {
      fit_rows <- data.table::data.table(
        grid_id = g,
        fold_id = fold,
        type = this_type,
        .fit = list(fit_result$value)
      )
    }
  }

  for (i in seq_along(metrics)) {
    this_metric <- metrics[i]
    score <- NA_real_
    if (isTRUE(fit_result$ok)) {
      score_result <- .ci_capture({
        if (identical(this_metric, "validation_gain")) {
          fold_validation_gain
        } else if (this_metric %in% c(
          "relative_validation_gain", "percent_validation_root_recovered"
        )) {
          fold_validation_relative_gain
        } else if (!this_metric %in% c(
          "validation_gain", "relative_validation_gain",
          "percent_validation_root_recovered"
        ) &&
                   !is.null(pred)) {
          .ci_score_prediction_metric(
            this_metric,
            outcome[test_idx],
            pred,
            weights[test_idx]
          )
        } else {
          NA_real_
        }
      })
      notes[[length(notes) + 1L]] <- .ci_notes_dt(
        g, fold, this_type, metric = this_metric, stage = "score",
        messages = score_result$warnings
      )
      if (isTRUE(score_result$ok)) {
        score <- score_result$value
      } else {
        notes[[length(notes) + 1L]] <- .ci_notes_dt(
          g, fold, this_type, metric = this_metric, stage = "score",
          messages = score_result$error, class = "error"
        )
      }
    }

    score_rows[[i]] <- data.table::data.table(
      grid_id = g,
      fold_id = fold,
      metric = this_metric,
      score = score,
      n_terminal = n_terminal,
      train_gain = train_gain,
      fold_validation_gain = fold_validation_gain,
      train_relative_gain = train_relative_gain,
      fold_validation_relative_gain = fold_validation_relative_gain,
      relative_generalization_gap = relative_generalization_gap,
      train_root_impurity = train_root_impurity,
      validation_root_impurity = validation_root_impurity,
      fit_error = fit_result$error
    )
    for (nm in names(tuning_grid)) {
      score_rows[[i]][[nm]] <- grid_row[[nm]][1L]
    }
    if (!("ntree" %in% names(score_rows[[i]]))) {
      score_rows[[i]]$ntree <- this_ntree
    }

    if (isTRUE(control$verbose)) {
      message(sprintf(
        "[grid %d/%d, fold %s, type %s] %s = %s",
        g,
        nrow(tuning_grid),
        fold,
        this_type,
        this_metric,
        if (is.na(score)) "NA" else format(round(score, 5), nsmall = 5)
      ))
    }
  }

  list(
    fold_results = data.table::rbindlist(score_rows, fill = TRUE),
    predictions = prediction_rows,
    extracts = extract_rows,
    fits = fit_rows,
    notes = data.table::rbindlist(notes, fill = TRUE)
  )
}

#' Tune greedy concentration-index forest controls by cross-validation
#'
#' @description
#' Fits [ci_forest()] across candidate forest controls and concentration-index
#' criteria. Concentration-index validation gain is computed directly from the
#' forest's internal trees by averaging held-out validation gain across member
#' tree partitions. Prediction-oriented metrics are computed from the averaged
#' forest predictions in the same tuning run. When `refit = TRUE`, the selected
#' forest is also summarized by a surrogate greedy [ci_tree()] for
#' interpretation.
#'
#' As in [tune_ci_tree()], relative validation metrics are root-relative model
#' scores, while `min_relative_gain` is a local parent-node relative split
#' threshold.
#'
#' @inheritParams tune_ci_tree
#' @param ntree Number of trees used when `control_grid` does not contain an
#'   `ntree` column.
#' @param surrogate_control Optional [ci_tree_control()] for the surrogate tree.
#'   By default, the selected forest controls are reused with `mtry = NULL` so
#'   the surrogate searches all split variables.
#' @param prediction_name Name of the forest-prediction column added to the
#'   surrogate data.
#' @param perturb Resampling controls passed to [ci_forest()].
#' @param parallel_over Parallelization strategy. `"none"` runs tuning and
#'   forest fitting serially, `"tuning"` evaluates grid/resample tasks with
#'   [future.apply::future_lapply()], and `"forest"` keeps tuning tasks serial
#'   while growing trees inside each [ci_forest()] call with
#'   [future.apply::future_lapply()]. Parallel modes require the suggested
#'   package `future.apply`. The future backend is controlled by the user
#'   outside `tune_ci_forest()`.
#' @param future.seed Passed to [future.apply::future_lapply()] when
#'   `parallel_over` is `"tuning"` or `"forest"`.
#'
#' @return A `ci_forest_tuning` object.
#'
#' @examples
#' if (requireNamespace("future", quietly = TRUE) &&
#'     requireNamespace("future.apply", quietly = TRUE)) {
#'   old_plan <- future::plan()
#'   on.exit(future::plan(old_plan), add = TRUE)
#'   future::plan(future::sequential)
#'
#'   toy_data <- data.frame(
#'     rank = c(10, 20, 30, 40, 50, 60, 70, 80),
#'     outcome = c(1, 0, 1, 0, 1, 1, 0, 1),
#'     income = c(2, 4, 6, 8, 10, 12, 14, 16)
#'   )
#'   grid <- ci_tree_control_grid(
#'     minsplit = 1,
#'     minbucket = 1,
#'     minprob = 0,
#'     maxdepth = 1,
#'     ntree = 3
#'   )
#'   tuned <- tune_ci_forest(
#'     cbind(rank, outcome) ~ income,
#'     data = toy_data,
#'     rank_name = "rank",
#'     outcome_name = "outcome",
#'     control_grid = grid,
#'     v = 2,
#'     parallel_over = "tuning",
#'     refit = FALSE
#'   )
#' }
#'
#' @export
tune_ci_forest <- function(formula,
                           data,
                           rank_name,
                           outcome_name,
                           weights = NULL,
                           type = c("CI", "CIg", "CIc", "L"),
                           control_grid = NULL,
                           ntree = 500L,
                           v = 5L,
                           strata = NULL,
                           fold_id = NULL,
                           resamples = NULL,
                           seed = NULL,
                           metric = c(
                             "validation_gain", "relative_validation_gain",
                             "percent_validation_root_recovered", "brier",
                             "log_loss", "roc_auc"
                           ),
                           metrics = NULL,
                           surrogate_control = NULL,
                           prediction_name = "forest_risk",
                           refit = TRUE,
                           verbose = FALSE,
                           control = NULL,
                           perturb = list(replace = FALSE, fraction = 0.632),
                           parallel_over = c("none", "tuning", "forest"),
                           future.seed = TRUE,
                           na.action = stats::na.omit,
                           ...) {
  type <- .ci_match_type(type)
  parallel_over <- match.arg(parallel_over)
  extra_args <- list(...)
  if (any(c("parallel", "future.seed") %in% names(extra_args))) {
    stop(
      "Use `parallel_over` and `future.seed` to control `tune_ci_forest()` parallelism.",
      call. = FALSE
    )
  }
  metrics <- if (is.null(metrics) && missing(metric)) {
    "validation_gain"
  } else {
    .ci_match_metrics(metric, metrics)
  }
  selection_metric <- metrics[1L]
  control <- .ci_normalize_tune_control(control, verbose = verbose)

  ntree <- as.integer(ntree)
  if (length(ntree) != 1L || is.na(ntree) || ntree <= 0L) {
    stop("`ntree` must be a positive integer.", call. = FALSE)
  }
  perturb <- .ci_normalize_perturb(perturb)

  seed_base <- NULL
  if (!is.null(seed)) {
    had_seed <- exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
    if (had_seed) {
      old_seed <- get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
    }
    on.exit({
      if (had_seed) {
        assign(".Random.seed", old_seed, envir = .GlobalEnv)
      } else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
        rm(".Random.seed", envir = .GlobalEnv)
      }
    }, add = TRUE)
    seed_base <- as.integer(seed)[1L]
  }

  data <- as.data.frame(data)
  n <- nrow(data)
  if (n <= 1L) {
    stop("`data` must contain at least two rows.", call. = FALSE)
  }

  weights <- .ci_default_weights(weights, n)
  outcome <- .ci_outcome_numeric(data[[outcome_name]], outcome_name)
  tuning_grid <- .ci_check_control_grid(
    control_grid,
    type = type,
    model = "forest",
    ntree = ntree,
    seed = seed
  )
  resample_index <- .ci_make_resamples(
    data = data,
    v = v,
    strata = strata,
    fold_id = fold_id,
    resamples = resamples,
    seed = seed
  )
  fold_id_out <- .ci_resample_fold_id(resample_index, n)
  root_table <- .ci_validation_root_table(
    data = data,
    weights = weights,
    resamples = resample_index,
    rank_name = rank_name,
    outcome_name = outcome_name,
    types = unique(tuning_grid$type)
  )
  tasks <- .ci_task_grid(tuning_grid, resample_index, seed = seed)
  task_args <- list(
    formula = formula,
    data = data,
    rank_name = rank_name,
    outcome_name = outcome_name,
    weights = weights,
    outcome = outcome,
    metrics = metrics,
    tuning_grid = tuning_grid,
    root_table = root_table,
    surrogate_control = surrogate_control,
    prediction_name = prediction_name,
    ntree = ntree,
    perturb = perturb,
    parallel_over = parallel_over,
    forest_future.seed = future.seed,
    na.action = na.action,
    control = control,
    extra_args = extra_args
  )

  task_results <- if (identical(parallel_over, "tuning")) {
    .ci_require_future_apply(
      enabled = TRUE,
      when = "`parallel_over = \"tuning\"`",
      disable = "`parallel_over = \"none\"`"
    )
    do.call(
      future.apply::future_lapply,
      c(list(X = tasks, FUN = .ci_tune_forest_task, future.seed = future.seed), task_args)
    )
  } else {
    do.call(lapply, c(list(X = tasks, FUN = .ci_tune_forest_task), task_args))
  }
  fold_results <- data.table::rbindlist(
    lapply(task_results, `[[`, "fold_results"),
    fill = TRUE
  )
  predictions <- data.table::rbindlist(
    lapply(task_results, `[[`, "predictions"),
    fill = TRUE
  )
  extracts <- data.table::rbindlist(lapply(task_results, `[[`, "extracts"), fill = TRUE)
  fits <- data.table::rbindlist(lapply(task_results, `[[`, "fits"), fill = TRUE)
  notes <- data.table::rbindlist(lapply(task_results, `[[`, "notes"), fill = TRUE)

  summary <- .ci_summarize_tuning(fold_results, tuning_grid, selection_metric)
  best_params <- .ci_select_best_params(summary, selection_metric)
  best_control <- NULL
  best_fit <- NULL
  best_surrogate <- NULL
  best_surrogate_data <- NULL
  best_type <- NA_character_

  refit_params <- best_params[is.finite(best_params$mean_score), , drop = FALSE]
  if (nrow(refit_params) > 0L) {
    refit_params <- refit_params[1L, , drop = FALSE]
    best_control <- .ci_control_from_grid_row(refit_params)
    best_type <- as.character(refit_params$type[1L])
    best_ntree <- .ci_forest_ntree_from_row(refit_params, ntree)
    best_surrogate_control <- .ci_surrogate_control(best_control, surrogate_control)

    if (isTRUE(refit)) {
      if (!is.null(seed_base)) {
        set.seed(seed_base + nrow(tuning_grid) * length(resample_index) + 1L)
      }
      best_fit <- ci_forest(
        formula = formula,
        data = data,
        rank_name = rank_name,
        outcome_name = outcome_name,
        weights = weights,
        type = best_type,
        control = best_control,
        ntree = best_ntree,
        perturb = perturb,
        parallel = identical(parallel_over, "forest"),
        future.seed = future.seed,
        na.action = na.action,
        ...
      )
      surrogate <- .ci_fit_forest_surrogate(
        forest = best_fit,
        data = data,
        formula = formula,
        rank_name = rank_name,
        prediction_name = prediction_name,
        weights = weights,
        type = best_type,
        control = best_surrogate_control,
        na.action = na.action
      )
      best_surrogate <- surrogate$fit
      best_surrogate_data <- surrogate$data
    }
  }

  out <- list(
    fold_results = fold_results,
    summary = summary,
    best_params = best_params,
    best_type = best_type,
    best_control = best_control,
    best_fit = best_fit,
    best_surrogate = best_surrogate,
    best_surrogate_data = best_surrogate_data,
    metric = metrics,
    metric_direction = .ci_metric_directions(metrics),
    selection_metric = selection_metric,
    model = "forest",
    fold_id = fold_id_out,
    resamples = resample_index,
    control_grid = data.table::as.data.table(tuning_grid),
    predictions = predictions,
    extracts = extracts,
    fits = fits,
    notes = notes,
    validation_roots = root_table,
    prediction_name = prediction_name,
    control = control
  )
  class(out) <- c("ci_forest_tuning", "ci_tree_tuning", class(out))
  out
}
