# WARNING - Generated by {fusen} from dev/model_selection.Rmd: do not edit by hand # nolint: line_length_linter.

#' Tune greedy concentration-index forest controls by cross-validation
#'
#' `tune_cf_ci()` is kept for existing code. New code should use
#' [tune_ci_forest()].
#'
#' @return A `ci_forest_tuning` object.
#' @name tune_ci_forest
#' @rdname tune_ci_forest
#' @export
tune_cf_ci <- function(...) {
  tune_ci_forest(...)
}
